export type V3={x:number;y:number;z:number};
export type Box={x:number;z:number;w:number;d:number;h:number;kind:'crate'|'shelf'|'table'|'sofa'};
export const HOME={x:-9,z:9};
export const BOXES:Box[]=[
 {x:-4,z:4,w:2.4,d:2.4,h:1.1,kind:'crate'}, {x:2,z:5,w:3,d:2,h:1.4,kind:'table'},
 {x:-7,z:-1,w:2.5,d:4,h:2.5,kind:'shelf'}, {x:-1,z:-4,w:4,d:1.8,h:1.6,kind:'table'},
 {x:6,z:-3,w:2,d:3,h:1.1,kind:'crate'}, {x:7,z:7,w:4.5,d:1.8,h:1.4,kind:'sofa'},
 {x:-8,z:-8,w:4,d:1.8,h:2.8,kind:'shelf'}, {x:5,z:-9,w:4,d:1.5,h:2.6,kind:'shelf'},
 {x:-2,z:-9,w:1.4,d:1.4,h:.6,kind:'crate'}, {x:10,z:0,w:1.8,d:1.8,h:.7,kind:'crate'}
];
export const SNACKS=[{x:-4,y:1.42,z:4},{x:5,y:.35,z:2},{x:10,y:1.02,z:0},{x:9,y:.35,z:-9},{x:-3,y:.35,z:-7},{x:-10,y:.35,z:-4}];
export type Controls={forward:number;strafe:number;jump:boolean;sprint:boolean;fire:boolean};
export type Bot={id:number;x:number;z:number;hp:number;cooldown:number;phase:number;flash:number};
export type Shot=V3&{vx:number;vy:number;vz:number;life:number;enemy:boolean};
export function blocked(x:number,z:number,r=.4){return Math.abs(x)>12.4||Math.abs(z)>12.4||BOXES.some(b=>Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r)}
export function route(from:V3,to:V3):V3[]{const key=(x:number,z:number)=>x+','+z;const sx=Math.round(from.x),sz=Math.round(from.z),gx=Math.round(to.x),gz=Math.round(to.z);const open=[{x:sx,z:sz,g:0,f:0}],came=new Map<string,string>(),cost=new Map<string,number>([[key(sx,sz),0]]);let best=key(sx,sz),distance=Infinity;
 for(let loops=0;open.length&&loops<1200;loops++){open.sort((a,b)=>a.f-b.f);const p=open.shift()!,pk=key(p.x,p.z),d=Math.hypot(p.x-gx,p.z-gz);if(d<distance){distance=d;best=pk}if(d<1.4)break;for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const x=p.x+dx,z=p.z+dz;if(blocked(x,z,.52)||blocked(p.x+dx,p.z,.52)||blocked(p.x,p.z+dz,.52))continue;const k=key(x,z),g=p.g+Math.hypot(dx,dz);if(g>=(cost.get(k)??Infinity))continue;cost.set(k,g);came.set(k,pk);open.push({x,z,g,f:g+Math.hypot(x-gx,z-gz)})}}
 const result:V3[]=[];for(let k=best;k!==key(sx,sz)&&came.has(k);k=came.get(k)!){const[x,z]=k.split(',').map(Number);result.unshift({x,y:0,z})}return result;
}
export class Patrol{
 player={x:HOME.x,y:0,z:HOME.z,yaw:0,pitch:0,vy:0,ground:true};buddy={x:HOME.x+1.5,y:0,z:HOME.z+1,face:0,speed:0};bots:Bot[]=[[-7,3],[5,1],[7,-7],[-3,-6],[-9,-5]].map(([x,z],i)=>({id:i,x,z,hp:3,cooldown:1+i*.3,phase:i*1.7,flash:0}));snacks=SNACKS.map(s=>({...s,taken:false}));shots:Shot[]=[];time=0;playing=false;paused=false;won=false;ammo=12;reload=0;fireCooldown=0;health=100;stamina=100;hurt=0;hit=0;rescues=0;events:string[]=[];message='';messageFor=0;path:V3[]=[];pathTimer=0;walk=0;fired=0;hits=0;
 get found(){return this.snacks.filter(s=>s.taken).length}get disabled(){return this.bots.filter(b=>b.hp<=0).length}
 say(text:string){this.message=text;this.messageFor=4}
 look(dx:number,dy:number){if(this.paused||this.won)return;this.player.yaw-=dx*.0023;this.player.pitch=Math.max(-1.3,Math.min(1.3,this.player.pitch-dy*.0020))}
 startReload(){if(this.playing&&!this.paused&&!this.won&&this.reload===0&&this.ammo<12){this.reload=1.3;this.events.push('reload')}}
 fire(){if(!this.playing||this.paused||this.won||this.fireCooldown>0||this.reload>0)return;if(this.ammo===0){this.startReload();return}const p=this.player,c=Math.cos(p.pitch),dir={x:-Math.sin(p.yaw)*c,y:Math.sin(p.pitch),z:-Math.cos(p.yaw)*c};this.shots.push({x:p.x,y:p.y+1.12,z:p.z,vx:dir.x*28,vy:dir.y*28,vz:dir.z*28,life:1.6,enemy:false});this.ammo--;this.fired++;this.fireCooldown=.19;this.events.push('fire');if(!this.ammo)this.startReload()}
 visible(a:V3,b:V3){const distance=Math.hypot(b.x-a.x,b.z-a.z,b.y-a.y);for(let t=.15;t<distance;t+=.22){const f=t/distance,x=a.x+(b.x-a.x)*f,z=a.z+(b.z-a.z)*f,y=a.y+(b.y-a.y)*f;if(BOXES.some(o=>y<o.h&&Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2))return false}return true}
 moveBody(body:{x:number;z:number},dx:number,dz:number,r:number,y=0){const collides=(x:number,z:number)=>Math.abs(x)>12.35-r||Math.abs(z)>12.35-r||BOXES.some(b=>y<b.h-.04&&Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r);if(!collides(body.x+dx,body.z))body.x+=dx;if(!collides(body.x,body.z+dz))body.z+=dz;}
 step(dt:number,k:Controls){if(!this.playing||this.paused||this.won)return;dt=Math.min(dt,1/30);this.time+=dt;this.messageFor=Math.max(0,this.messageFor-dt);this.fireCooldown=Math.max(0,this.fireCooldown-dt);this.hurt=Math.max(0,this.hurt-dt);this.hit=Math.max(0,this.hit-dt);if(this.reload>0){this.reload=Math.max(0,this.reload-dt);if(this.reload===0){this.ammo=12;this.events.push('ready')}}
 const p=this.player,moving=!!(k.forward||k.strafe),sprint=k.sprint&&moving&&this.stamina>2;this.stamina=Math.max(0,Math.min(100,this.stamina+(sprint?-24:18)*dt));const speed=sprint?6.8:4.25,n=Math.max(1,Math.hypot(k.forward,k.strafe)),dx=(-Math.sin(p.yaw)*k.forward+Math.cos(p.yaw)*k.strafe)/n*speed*dt,dz=(-Math.cos(p.yaw)*k.forward-Math.sin(p.yaw)*k.strafe)/n*speed*dt;this.moveBody(p,dx,dz,.35,p.y);if(moving)this.walk+=dt*(sprint?13:9);if(k.jump&&p.ground){p.vy=7.5;p.ground=false;this.events.push('jump')}const oldY=p.y;p.vy-=20*dt;p.y+=p.vy*dt;p.ground=false;let floor=0;for(const b of BOXES)if(Math.abs(p.x-b.x)<b.w/2+.22&&Math.abs(p.z-b.z)<b.d/2+.22&&oldY>=b.h-.02)floor=Math.max(floor,b.h);if(p.y<=floor){p.y=floor;p.vy=0;p.ground=true}if(k.fire)this.fire();
 for(const s of this.snacks)if(!s.taken&&Math.hypot(p.x-s.x,p.z-s.z)<1.05&&Math.abs(p.y+.7-s.y)<1.2){s.taken=true;this.events.push('snack');this.say(this.found===this.snacks.length?'All snacks found! Bring your buddy back to the purple HOME rug.':`${this.found} / ${this.snacks.length} snacks rescued.`)}
 this.pathTimer-=dt;const buddyDist=Math.hypot(p.x-this.buddy.x,p.z-this.buddy.z);if(this.pathTimer<=0&&buddyDist>2){this.path=route(this.buddy,p);this.pathTimer=.75}this.buddy.speed=0;if(buddyDist>1.7&&this.path.length){const dest=this.path[0],dx=dest.x-this.buddy.x,dz=dest.z-this.buddy.z,d=Math.hypot(dx,dz);if(d<.2)this.path.shift();else{const s=Math.min(d,dt*5.3);this.moveBody(this.buddy,dx/d*s,dz/d*s,.42);this.buddy.face=Math.atan2(-dz,dx);this.buddy.speed=3}}
 for(const b of this.bots){b.flash=Math.max(0,b.flash-dt);if(b.hp<=0)continue;b.cooldown-=dt;const dist=Math.hypot(p.x-b.x,p.z-b.z),safe=Math.hypot(p.x-HOME.x,p.z-HOME.z)<2.3;const los=this.visible({x:b.x,y:.55,z:b.z},{x:p.x,y:p.y+.8,z:p.z});if(dist<8&&!safe&&los){if(dist>3.6)this.moveBody(b,(p.x-b.x)/dist*dt*.95,(p.z-b.z)/dist*dt*.95,.65);if(b.cooldown<=0){const dy=p.y+.75-.55,mag=Math.hypot(p.x-b.x,p.z-b.z,dy);this.shots.push({x:b.x,y:.55,z:b.z,vx:(p.x-b.x)/mag*6,vy:dy/mag*6,vz:(p.z-b.z)/mag*6,enemy:true,life:3});b.cooldown=2.0+b.id*.15;this.events.push('bot')}}else{b.phase+=dt*.35;this.moveBody(b,Math.cos(b.phase)*dt*.4,Math.sin(b.phase)*dt*.4,.65)}}
 for(const shot of this.shots){shot.life-=dt;const pieces=Math.max(1,Math.ceil(Math.hypot(shot.vx,shot.vy,shot.vz)*dt/.13));for(let step=0;step<pieces&&shot.life>0;step++){shot.x+=shot.vx*dt/pieces;shot.y+=shot.vy*dt/pieces;shot.z+=shot.vz*dt/pieces;if(shot.y<.05||Math.abs(shot.x)>12.5||Math.abs(shot.z)>12.5||BOXES.some(b=>shot.y<b.h&&Math.abs(shot.x-b.x)<b.w/2&&Math.abs(shot.z-b.z)<b.d/2)){shot.life=0;break}if(shot.enemy){if(Math.hypot(shot.x-p.x,shot.z-p.z)<.47&&shot.y>p.y&&shot.y<p.y+1.4){shot.life=0;if(this.hurt===0){this.health-=12;this.hurt=.5;this.events.push('hurt')}}}else for(const b of this.bots){if(b.hp>0&&Math.hypot(shot.x-b.x,shot.z-b.z)<.72&&shot.y<1.04){b.hp--;b.flash=.16;shot.life=0;this.hit=.13;this.hits++;this.events.push(b.hp===0?'disabled':'hit');break}}}}
 this.shots=this.shots.filter(s=>s.life>0);if(this.health<=0){this.health=100;this.rescues++;p.x=HOME.x;p.z=HOME.z;p.y=0;p.vy=0;this.buddy.x=HOME.x+1.2;this.buddy.z=HOME.z;this.shots=[];this.path=[];this.hurt=0;this.say('Back in the hideout. Your collected snacks are safe—try again.');this.events.push('rescue')}
 if(Math.hypot(p.x-HOME.x,p.z-HOME.z)<2&&this.health<100)this.health=Math.min(100,this.health+15*dt);
 if(this.found===this.snacks.length&&Math.hypot(p.x-HOME.x,p.z-HOME.z)<2&&Math.hypot(this.buddy.x-HOME.x,this.buddy.z-HOME.z)<3.3){this.won=true;this.events.push('win')}
 }
}
