'use client';
import {useEffect,useRef,useState} from 'react';
import {Game,levels,W,H,FLOOR,type Mode,type Input} from '../../lib/legacy/snack/game';
import {Pause,Play,RotateCcw,Volume2,VolumeX,ArrowLeft,ArrowRight,ArrowUp,Repeat2,Hand,RotateCw,ChevronRight,Heart,Users,HelpCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';

type HUD={active:number;snack:number;held:boolean;msg:string;gate:boolean;together:boolean;won:boolean};
const empty:Input={left:false,right:false,jump:false};
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef<Game|null>(null),keys=useRef(new Set<string>()),touch=useRef({...empty}),audio=useRef<AudioContext|null>(null),mute=useRef(true);
 const [ready,setReady]=useState(false),[error,setError]=useState(false),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[sound,setSound]=useState(false),[mode,setMode]=useState<Mode>('solo'),[level,setLevel]=useState(0),[hud,setHud]=useState<HUD>({active:0,snack:100,held:false,msg:'',gate:false,together:false,won:false});
 const images=useRef<{bg:HTMLImageElement;sprite:HTMLImageElement}|null>(null);
 function tone(event:string){if(mute.current)return;try{if(!audio.current)audio.current=new AudioContext();const ctx=audio.current;void ctx.resume();const o=ctx.createOscillator(),v=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(event==='win'?660:event==='nibble'?480:event==='jump'?310:520,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(event==='win'?1100:180,ctx.currentTime+.16);v.gain.setValueAtTime(.07,ctx.currentTime);v.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);o.connect(v);v.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.23);}catch{}}
 function begin(m:Mode,l=0){const g=new Game(l,m);g.started=true;game.current=g;keys.current.clear();touch.current={...empty};setMode(m);setLevel(l);setStarted(true);setPaused(false);setHud({active:0,snack:100,held:false,msg:'',gate:false,together:false,won:false});}
 function act(a:string){game.current?.action(a);}
 function pause(){const g=game.current;if(g&&!g.won){g.paused=!g.paused;setPaused(g.paused);keys.current.clear();touch.current={...empty};}}
 useEffect(()=>{let cancelled=false;const bg=new Image(),sprite=new Image();let loaded=0;const done=()=>{if(++loaded===2&&!cancelled){images.current={bg,sprite};setReady(true)}};bg.onload=done;sprite.onload=done;bg.onerror=sprite.onerror=()=>setError(true);bg.src='/art/snack-heist/playroom-background.png';sprite.src='/art/snack-heist/chinchilla-atlas.png';return()=>{cancelled=true}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,[role="dialog"]'))return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' ','tab'].includes(k)&&game.current?.started)e.preventDefault();if(e.repeat)return;keys.current.add(k);if(k==='escape'||k==='p')pause();const actions:Record<string,string>={tab:'switch',e:'grab',r:'rotate',n:'nibble',t:'tower',f:'team'};if(actions[k])game.current?.action(actions[k],k==='e'&&game.current?.mode==='duo'?0:game.current?.active);if(k==='enter'&&game.current?.mode==='duo')game.current.action('grab',1);};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();touch.current={...empty};const g=game.current;if(g?.started&&!g.won){g.paused=true;setPaused(true)}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let frame=0,last=0,ui=0;const loop=(now:number)=>{const dt=last?Math.min((now-last)/1000,1/30):1/60;last=now;const g=game.current,k=keys.current;
 if(g){const ins=[{...empty},{...empty}];if(g.mode==='solo'){ins[g.active]={left:k.has('a')||k.has('arrowleft')||touch.current.left,right:k.has('d')||k.has('arrowright')||touch.current.right,jump:k.has('w')||k.has('arrowup')||k.has(' ')||touch.current.jump};}else{ins[0]={left:k.has('a'),right:k.has('d'),jump:k.has('w')};ins[1]={left:k.has('arrowleft'),right:k.has('arrowright'),jump:k.has('arrowup')};ins[g.active].left ||= touch.current.left;ins[g.active].right ||=touch.current.right;ins[g.active].jump ||=touch.current.jump;}
 g.step(dt,ins);for(const e of g.events.splice(0))tone(e);if(now-ui>100){setHud({active:g.active,snack:Math.round(g.snack.length/178*100),held:g.snack.owner>=0,msg:g.messageTime>0?g.message:'',gate:g.gate,together:g.together,won:g.won});ui=now;}}
 draw(ctx,g,images.current,now);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[]);
 const touchButton=(key:keyof Input,icon:React.ReactNode,label:string)=><button className="touch-key" aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current[key]=true;}} onPointerUp={()=>touch.current[key]=false} onPointerCancel={()=>touch.current[key]=false} onLostPointerCapture={()=>touch.current[key]=false}>{icon}</button>;
 return <main className="game-shell"><header className="topbar"><div className="brand">ChinChin<span>THE GREAT SNACK HEIST</span></div><div className="header-right"><span className="chapter">{started?`ROOM ${String(level+1).padStart(2,'0')} / 03`:'A little adventure for two'}</span><button className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{mute.current=!mute.current;setSound(!mute.current);if(!mute.current)tone('switch')}}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><Dialog onOpenChange={open=>{if(open&&game.current?.started&&!game.current.won){game.current.paused=true;setPaused(true);keys.current.clear();}}}><DialogTrigger className="icon-button" aria-label="How to play"><HelpCircle size={19}/></DialogTrigger><DialogContent className="help-dialog"><DialogHeader><DialogTitle>Small paws. Big teamwork.</DialogTitle><DialogDescription>Bring the snack and both chinchillas to the HOME marker in every room.</DialogDescription></DialogHeader><div className="help-copy"><p><b>Solo:</b> A / D or ← / → to move. W, ↑ or Space to jump. Tab switches chinchillas.</p><p><b>Two players:</b> Dora uses A / D / W and E to grab. Enzo uses ← / → / ↑ and Enter to grab. Share the other action keys.</p><p><b>E</b> grab or drop · <b>R</b> rotate the snack · <b>N</b> nibble · <b>T</b> tower boost when close together · <b>F</b> team up while holding the snack. In solo mode, your buddy then follows.</p><p>Dora jumps higher. Enzo can push the crate. Hold jump to keep hopping. No lives, no timer—take your time.</p></div></DialogContent></Dialog></div></header>
 <section className={`stage ${started?'playing':''}`} aria-label="Chinchilla game"><canvas ref={canvas} width={W} height={H} aria-label="Game playroom. Use the movement and action controls below."/>
 {!started&&<div className="welcome"><span className="eyebrow">TWO CHINCHILLAS. ONE BIG SNACK.</span><h1>A very fluffy<br/>getaway.</h1><p>Hop up. Team up. Sneak a nibble.<br/>Get the snack—and each other—home.</p><div className="start-actions"><button className="primary" disabled={!ready} onClick={()=>begin('solo')}>{error?'Artwork could not load':ready?'Play solo':'Getting cozy…'}<ChevronRight size={21}/></button><button className="secondary" disabled={!ready} onClick={()=>begin('duo')}><Users size={18}/> Two players</button></div><span className="start-note">3 little rooms · keyboard or touch · no rush</span><div className="welcome-pets"><span className="pet-art white-art"/><span className="pet-art grey-art"/></div>{error&&<button className="secondary" onClick={()=>window.location.reload()}>Reload game</button>}</div>}
 {started&&<><div className="room-banner"><span className="eyebrow">ROOM {String(level+1).padStart(2,'0')}</span><h2>{levels[level].name}</h2></div><div className="stage-tools"><button className="icon-button" aria-label={paused?'Resume game':'Pause game'} onClick={pause}>{paused?<Play size={18}/>:<Pause size={18}/>}</button><button className="icon-button" aria-label="Restart this room" onClick={()=>begin(mode,level)}><RotateCcw size={18}/></button></div></>}
 {paused&&!hud.won&&<div className="scrim"><div className="pause-card"><span className="eyebrow">A LITTLE BREATHER</span><h2>Taking a fluff break.</h2><button className="primary" onClick={pause}>Keep going <Play size={18}/></button><button className="text-button" onClick={()=>{game.current=null;setStarted(false);setPaused(false)}}>Back to title</button></div></div>}
 {hud.won&&<div className="scrim"><div className="win-card"><Heart className="win-heart" size={36} fill="currentColor"/><span className="eyebrow">{level===2?'THE GREAT SNACK HEIST, COMPLETE':'HOME, SWEET HIDEOUT'}</span><h2>{level===2?'Partners in crumbs.':'Together tastes better.'}</h2><p>Both friends home. {hud.snack}% of the snack saved.<br/>{hud.snack===100?'Perfect heist. Not a nibble missing!':'A little nibble was part of the adventure.'}</p><button className="primary" onClick={()=>begin(mode,level===2?0:level+1)}>{level===2?'Play again':'Next room'}<ChevronRight size={20}/></button><button className="text-button" onClick={()=>{game.current=null;setStarted(false);setHud({...hud,won:false})}}>Back to title</button></div></div>}
 </section>
 {started?<><section className="statusbar" aria-label="Game status"><div className="pet-select"><button className={hud.active===0?'pet-choice selected':'pet-choice'} onClick={()=>{if(game.current)game.current.active=0}}><span className="pet-dot white-dot"/><span>Dora<small>The high hopper</small></span></button><button className={hud.active===1?'pet-choice selected':'pet-choice'} onClick={()=>{if(game.current)game.current.active=1}}><span className="pet-dot grey-dot"/><span>Enzo<small>The little lifter</small></span></button></div><div className="objective" aria-live="polite">{hud.msg||levels[level].hint}</div><div className="snack-stat"><span>{hud.snack}% <small>snack left</small></span><div className="snack-meter"><i style={{width:`${hud.snack}%`}}/></div></div></section><section className="controls" aria-label="Game controls"><div className="movement">{touchButton('left',<ArrowLeft size={20}/>,'Move left')}{touchButton('right',<ArrowRight size={20}/>,'Move right')}{touchButton('jump',<ArrowUp size={20}/>,'Jump')}<span>{mode==='solo'?'A D / arrows · Space to jump':'Dora: A D W · Enzo: arrows'}</span></div><div className="actions"><button onClick={()=>act('switch')}><Repeat2 size={16}/> Switch <kbd>Tab</kbd></button><button onClick={()=>act('grab')}><Hand size={16}/> {hud.held?'Drop':'Grab'} <kbd>E</kbd></button><button onClick={()=>act('tower')}><ArrowUp size={16}/> Tower <kbd>T</kbd></button><button onClick={()=>act('rotate')}><RotateCw size={16}/> Rotate <kbd>R</kbd></button><button onClick={()=>act('nibble')}>Nibble <kbd>N</kbd></button><button className={hud.together?'on':''} onClick={()=>act('team')}><Users size={16}/> Team <kbd>F</kbd></button></div></section></>:<div className="intro-strip"><span><span className="tiny-number">01</span> Dora hops higher</span><span><span className="tiny-number">02</span> Enzo lends a paw</span><span><span className="tiny-number">03</span> Nobody gets left behind</span></div>}
 <footer>Inspired by your two fluffy partners in crime. <span>♡</span></footer></main>
}
function draw(c:CanvasRenderingContext2D,g:Game|null,assets:{bg:HTMLImageElement;sprite:HTMLImageElement}|null,t:number){c.clearRect(0,0,W,H);if(assets)c.drawImage(assets.bg,0,0,W,H);if(!g)return;c.fillStyle='#241a2530';c.fillRect(0,0,W,H);const round=(x:number,y:number,w:number,h:number,r:number,fill:string)=>{c.fillStyle=fill;c.beginPath();c.roundRect(x,y,w,h,r);c.fill()};
 // Solid, high-contrast platforms are the playable collision surfaces.
 for(const p of levels[g.level].platforms){round(p.x+3,p.y+9,p.w,p.h+9,5,'#251c2390');round(p.x,p.y,p.w,p.h,5,'#69472f');round(p.x,p.y,p.w,6,3,'#dfaf70');c.fillStyle='#ab7c4f';c.fillRect(p.x+12,p.y+12,p.w-24,2);}
 c.fillStyle='#76513c';c.fillRect(0,FLOOR,W,9);c.fillStyle='#e6bd83';c.fillRect(0,FLOOR,W,3);
 if(g.level===1){const b=g.crate;round(b.x,b.y,b.w,b.h,5,'#956340');c.strokeStyle='#dfb47c';c.lineWidth=4;c.strokeRect(b.x+7,b.y+7,b.w-14,b.h-14);c.beginPath();c.moveTo(b.x+9,b.y+9);c.lineTo(b.x+b.w-9,b.y+b.h-9);c.stroke();round(430,347,57,10,5,g.gate?'#a5daa8':'#f1bf59');if(!g.gate){round(610,155,20,FLOOR-155,4,'#644f79');c.strokeStyle='#dec0f2';c.setLineDash([7,9]);c.strokeRect(614,159,12,FLOOR-159);c.setLineDash([]);}label(c,g.gate?'OPEN':'BUTTON',456,328,'#fff3c9');}
 if(g.level===2){round(527,200,32,FLOOR-200,12,'#9271b677');c.setLineDash([6,7]);c.strokeStyle='#e3caf5';c.lineWidth=2;c.strokeRect(532,200,22,FLOOR-200);c.setLineDash([]);label(c,'NARROW PASSAGE',544,179,'#fff');}
 round(45,FLOOR+23,160,36,18,'#322631d9');label(c,'♡  HOME',125,FLOOR+47,'#ffdfad');
 const s=g.snack;c.save();c.translate(s.x,s.y);if(s.vertical)c.rotate(Math.PI/2);c.shadowColor='#ffd477';c.shadowBlur=s.owner<0?15+5*Math.sin(t/240):4;round(-s.length/2,-9,s.length,18,8,'#b5803b');c.shadowBlur=0;c.fillStyle='#edc76b';for(let i=0;i<s.length-8;i+=11){c.beginPath();c.ellipse(-s.length/2+6+i,((i%3)-1)*3,4,2.5,i,0,Math.PI*2);c.fill()}c.restore();if(s.owner<0)label(c,'THE SNACK',s.x,s.y-30,'#fff1bc');
 for(let i=0;i<2;i++){const p=g.pets[i];const bounce=p.ground&&p.vx?Math.sin(t/65)*3:0;c.fillStyle='#24182645';c.beginPath();c.ellipse(p.x+20,p.y+p.h+3,35,7,0,0,Math.PI*2);c.fill();if(assets){c.save();c.translate(p.x+24,p.y+p.h-38+bounce);c.scale(p.face,1);c.drawImage(assets.sprite,i*887,0,887,887,-55,-54,108,108);c.restore();}if(i===g.active&&!g.won){c.fillStyle=i===0?'#fff6dc':'#d7bdff';c.beginPath();c.moveTo(p.x+15,p.y-32);c.lineTo(p.x+33,p.y-32);c.lineTo(p.x+24,p.y-21);c.fill();}if(g.mode==='duo')label(c,i===0?'P1':'P2',p.x+24,p.y-42,'#fff');}
 if(g.together)label(c,'TEAM UP ♥',(g.pets[0].x+g.pets[1].x)/2+24,Math.min(g.pets[0].y,g.pets[1].y)-55,'#fff0c1');
 if(g.won){for(let i=0;i<20;i++){const x=(i*73+t*.025)%W,y=(i*97+t*.035)%H;c.fillStyle=['#ffcd83','#dcbaff','#fff5cc'][i%3];c.fillRect(x,y,5,9)}}
}
function label(c:CanvasRenderingContext2D,text:string,x:number,y:number,color:string){c.font='bold 14px Arial';c.textAlign='center';c.lineWidth=4;c.strokeStyle='#362632aa';c.strokeText(text,x,y);c.fillStyle=color;c.fillText(text,x,y)}
