'use client';
import {useEffect,useRef,useState} from 'react';
import {KartGame,ITEMS,CIRCUIT,LAPS} from '../../lib/kart-game';
import type {KartScene} from '../../lib/kart-scene';
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new KartGame()),scene=useRef<KartScene|null>(null),keys=useRef(new Set<string>()),[tick,setTick]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState('');const g=game.current;
 function start(){game.current=new KartGame();game.current.start();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function pause(){game.current.pause();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 useEffect(()=>{let dead=false,raf=0,last=0,acc=0,ui=0;const resize=()=>scene.current?.resize();import('../../lib/kart-scene').then(({KartScene})=>{if(dead||!canvas.current)return;try{scene.current=new KartScene(canvas.current);setReady(true);const loop=(now:number)=>{acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){game.current.step(1/120,{gas:keys.current.has('w')||keys.current.has('arrowup'),brake:keys.current.has('s')||keys.current.has('arrowdown'),steer:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),drift:keys.current.has('shift')});acc-=1/120}scene.current!.render(game.current,now/1000);if(now-ui>70){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setError('Enable WebGL 2 and hardware acceleration, then reload.')}}).catch(()=>setError('The circuit could not load. Please reload.'));const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k===' ')game.current.useItem();if(k==='p'||k==='escape')pause()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();if(game.current.state==='racing'||game.current.state==='countdown')game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{dead=true;cancelAnimationFrame(raf);scene.current?.dispose();window.removeEventListener('resize',resize);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 const racers=[{name:'Dora & Enzo',s:g.s,finish:g.state==='finished'?g.finishTime:null},...g.rivals].sort((a,b)=>a.finish!==null&&b.finish!==null?a.finish-b.finish:a.finish!==null?-1:b.finish!==null?1:b.s-a.s);void tick;
 const hold=(key:string,label:string)=><button aria-label={label} onPointerDown={e=>{e.preventDefault();keys.current.add(key);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)} onLostPointerCapture={()=>keys.current.delete(key)}>{label}</button>;
 return <main className="kart-shell"><header className="kart-header"><a href="/">← MAIN ARCADE <span>PAWPRINT GRAND PRIX</span></a><button onClick={pause} disabled={!['racing','paused','countdown'].includes(g.state)}>{g.state==='paused'?'Resume':'Pause'} · P</button></header><div className="kart-layout"><section className="kart-stage" aria-label="Pawprint Grand Prix race"><canvas ref={canvas} tabIndex={0} aria-label="Hold W to accelerate, A D to steer, Shift to drift, Space to use item"/><div className="kart-top"><strong>{g.place}<small> / 5</small></strong><span>LAP <b>{g.lap} / {LAPS}</b></span><span>TIME <b>{g.time.toFixed(1)}s</b></span></div>
 {g.state==='countdown'&&<div className="kart-count">{Math.ceil(g.countdown)}</div>}
 {g.messageTime>0&&g.state==='racing'&&<div className="kart-message">{g.message}</div>}
 <div className="kart-speed"><b>{Math.round(g.speed*3.6)}</b><span>KM/H</span><small>{g.offroad?'OFF ROAD':g.boost>0?'TURBO':g.drifting?'DRIFTING':'PAW POWER'}</small><div className="kart-charge"><i style={{width:Math.min(100,g.drift/.65*100)+'%'}}/></div></div>
 {(g.state==='ready'||g.state==='paused'||g.state==='finished'||error)&&<div className="kart-overlay"><div><span className="kart-eyebrow">{error?'CIRCUIT UNAVAILABLE':g.state==='finished'?'CHEQUERED FLAG':g.state==='paused'?'PIT STOP':'ANDES · DUST VALLEY CIRCUIT'}</span><h1>{error?'A little engine trouble.':g.state==='finished'?`${g.finishPlace===1?'First place!':'Finished '+g.finishPlace+' of 5'}`:g.state==='paused'?'Catch your breath.':'Two fluffs.\nFull throttle.'}</h1><p>{error|| (g.state==='finished'?`Dora and Enzo finished three laps in ${g.finishTime.toFixed(1)} seconds.`:g.state==='paused'?'Your racing line is waiting.':'Dora drives. Enzo rides shotgun. Race four predators, charge your drifts, and grab a little fluffy firepower.')}</p><button className="kart-primary" disabled={!ready||!!error} onClick={g.state==='paused'?pause:start}>{g.state==='paused'?'Back to the race →':g.state==='finished'?'Race again →':ready?'Start your engines →':'Building the circuit…'}</button>{g.state==='ready'&&<small>Hold W / ↑ to accelerate after the countdown.</small>}</div></div>}
 </section><aside className="kart-sidebar"><span className="kart-eyebrow">YOUR CO-DRIVERS</span><h2>Dora & Enzo</h2><p>One kart. Double the fluff.</p><img src="/art/the-original-duo.jpg" alt="Dora and Enzo cuddling"/><div className="kart-item"><span className="kart-eyebrow">ITEM POCKET</span><h3>{g.item?ITEMS[g.item].name:'Ready for a pickup'}</h3><p>{g.item?ITEMS[g.item].description:'Drive through the mint crystals near the center of the road.'}</p><button disabled={!g.item||g.state!=='racing'} onClick={()=>{g.useItem();canvas.current?.focus()}}>Use item · SPACE</button></div><div className="kart-standings"><span className="kart-eyebrow">RUNNING ORDER</span>{racers.map((r,i)=><div key={r.name} className={r.name==='Dora & Enzo'?'you':''}><b>{i+1}</b><span>{r.name}</span></div>)}</div><svg className="kart-map" viewBox="0 0 120 90" aria-label="Circuit map"><ellipse cx="60" cy="45" rx="44" ry="29" fill="none" stroke="#708887" strokeWidth="8"/>{[...g.rivals,{s:g.s,name:'Dora & Enzo'}].map(r=><circle key={r.name} cx={60+Math.sin(r.s/CIRCUIT*Math.PI*2)*44} cy={45+Math.cos(r.s/CIRCUIT*Math.PI*2)*29} r={r.name==='Dora & Enzo'?5:3} fill={r.name==='Dora & Enzo'?'#f1c46e':'#d7dbd1'}/>)}</svg></aside></div><div className="kart-bottom"><div><b>W / ↑</b> Accelerate <b>S / ↓</b> Brake <b>A D / ← →</b> Racing line</div><div><b>SHIFT + steer</b> Charge drift <b>Release</b> Boost <b>SPACE</b> Item</div></div><div className="kart-touch">{hold('a','←')}{hold('d','→')}{hold('w','GAS')}{hold('s','BRAKE')}{hold('shift','DRIFT')}</div><p className="kart-tip">The kart follows the circuit’s bends. Steer across the road to overtake, collect items, and hit the gold boost strips. Stay on the asphalt for full speed.</p></main>
}
