import assert from 'node:assert/strict';
import {EscapeGame,TARGETS,BLOCKS,within,occluded,PLATFORMS,PAIR_HEIGHT,MAX_DECOYS,SEARCH_TIME} from '../.checks/escape-game.js';
const fresh=()=>{const g=new EscapeGame();g.start();return g};
const tick=(g,t,input)=>{for(let i=0;i<t*120;i++)g.step(1/120,input)};
const travel=(g,x,z,sneak=false)=>{for(let i=0;i<120*25&&g.active&&Math.hypot(g.x-x,g.z-z)>.08;i++){const dx=x-g.x,dz=z-g.z,d=Math.hypot(dx,dz);g.step(1/120,{x:dx/d,z:dz/d,sneak})}assert(g.active,'route stays undetected');assert(Math.hypot(g.x-x,g.z-z)<.1,'target reachable')};
const hop=(g,x,z,height)=>{assert(g.jump(),'jump from supported surface');for(let i=0;i<240;i++){const dx=x-g.x,dz=z-g.z,d=Math.hypot(dx,dz);g.step(1/120,{x:d>.04?dx/d:0,z:d>.04?dz/d:0,sneak:false});if(i>30&&d<.08&&g.grounded)break}assert(Math.hypot(g.x-x,g.z-z)<.1,'landing target reachable');assert(Math.abs(g.y-height)<.03,`expected landing ${height}, got ${g.y}`);assert(g.grounded)};
const g=fresh();assert(!g.interact());travel(g,-1,1.65);assert(!g.interact(),'cannot interact from below a shelf');hop(g,-3,1,.65);assert(g.interact());assert(g.tunnelRolled);assert(!g.stick);tick(g,1);assert(g.interact());assert(g.stick);assert(g.switchLeader());assert(!g.jump()||g.vy>0);while(!g.grounded||g.vy>0)g.step(1/120);hop(g,-3,-1.35,1.35);hop(g,-.65,-1.5,2.05);hop(g,-.6,-3.1,2.75);assert(g.interact());assert(g.clip);tick(g,1);hop(g,2.8,-1.2,2.05);hop(g,3,1.2,1.35);assert(g.interact());assert(g.key);tick(g,1);hop(g,0,3,0);assert(g.interact());assert.equal(g.phase,'room');function spyEscape(g,wait=0){const start=g.time;let stage=0;const route=[[-9,-7],[-1,-7],[-1,-6],[-1,-7],[8,-7],[8,-6],[10.5,-7]];for(let i=0;i<120*60&&g.active;i++){if(g.time-start<wait){g.step(1/120);continue}if(g.noticed&&g.alert>.12){if(!g.stun()&&g.decoys&&!g.decoy){g.face={x:0,z:1};g.distract()}}if((stage===3&&!g.badge)||(stage===6&&!g.intel)){if(!g.boxed)g.toggleBox();if(!g.searching&&!g.hacking)g.interact();g.step(1/120);continue}if(g.boxed)g.toggleBox();const [x,z]=route[stage]??[10.5,-7],dx=x-g.x,dz=z-g.z,d=Math.hypot(dx,dz);if(d<.08){stage++;if(stage===7)g.interact()}else g.step(1/120,{x:dx/d,z:dz/d,sneak:false})}return g.state}
spyEscape(g);
assert.equal(g.state,'won');console.log(`Complete vertical cage puzzles and stealth escape: ${g.time.toFixed(1)}s.`);
const ledge=fresh();ledge.x=-1;ledge.z=1.65;hop(ledge,-3,1,.65);assert(ledge.jump());assert(!ledge.jump(),'no double jumps');tick(ledge,1);ledge.x=-.6;ledge.z=-3.1;ledge.y=2.75;travel(ledge,-.6,-.5);tick(ledge,1);assert(ledge.y<2.75,'walking off a shelf falls to the next surface');

const collision=fresh();collision.phase='room';collision.x=-5;collision.z=0;tick(collision,.4,{x:1,z:0,sneak:false});assert(!BLOCKS.some(b=>within(collision,b,.54)));
const sight=fresh();sight.phase='room';sight.x=0;sight.z=2;assert(sight.sees({x:0,z:4,angle:Math.PI,target:0,distracted:0}));assert(!sight.sees({x:0,z:4,angle:0,target:0,distracted:0}));assert(occluded({x:-5,z:0},{x:1,z:0}));sight.x=-8;sight.z=0;sight.sneaking=true;assert(sight.hidden);assert(!sight.sees({x:-8,z:3,angle:Math.PI,target:0,distracted:0}));
const capture=fresh();capture.phase='room';capture.x=-5;capture.z=-3;capture.guards=[{x:-5,z:-4,angle:0,target:2,distracted:10}];capture.decoy={x:-5,z:0};capture.decoyTime=10;tick(capture,2);assert.equal(capture.state,'caught');capture.retry();assert.equal(capture.state,'playing');assert.equal(capture.alert,0);assert.equal(capture.decoys,MAX_DECOYS);assert(!capture.badge);
const puff=fresh();assert(!puff.distract());puff.phase='room';puff.x=-8;puff.z=-4;puff.face={x:1,z:0};assert(puff.distract());assert.equal(puff.decoys,MAX_DECOYS-1);assert(puff.guards.some(g=>g.distracted>0));puff.distract();puff.distract();assert(!puff.distract());
const pause=fresh();pause.pause();tick(pause,1);assert.equal(pause.time,0);pause.pause();assert(pause.jump());tick(pause,.1);assert(pause.y>0);tick(pause,1);assert.equal(pause.y,0);
console.log('Passed puzzle order/range, full route, cabinet collisions, sight direction/occlusion, hiding, capture/retry, decoys, pause and hops.');

const underside=fresh();underside.x=-.6;underside.z=-3.1;underside.y=1.4;underside.vy=5;let peak=underside.y;for(let i=0;i<120;i++){underside.step(1/120);peak=Math.max(peak,underside.y)}assert(peak+PAIR_HEIGHT<=2.62+.001,'head stops beneath solid shelf');
const wall=fresh();wall.x=-1;wall.z=1;tick(wall,.6,{x:-1,z:0,sneak:false});assert(wall.x>-1.23,'shelf side stops grounded movement');
const feeder=fresh();feeder.x=.8;feeder.z=1.65;hop(feeder,3,1.2,1.35);feeder.stick=true;feeder.clip=true;feeder.leader='Dora';assert(feeder.interact(),'pink hay feeder reachable directly from floor');
console.log('Solid shelf sides/undersides and direct hay-feeder jump passed.');

const search=fresh();search.phase='room';search.x=-1;search.z=-6;search.guards=[];assert(search.interact());assert(!search.badge);tick(search,1);assert(!search.badge);search.step(1/120,{x:1,z:0,sneak:false});assert.equal(search.searchProgress,0);assert(!search.searching);assert(search.interact());search.pause();tick(search,3);assert.equal(search.searchProgress,0);search.pause();tick(search,SEARCH_TIME+.02);assert(search.badge);
const pace=fresh();pace.phase='room';pace.x=-9;pace.z=-5;const before=pace.guards[0].x;tick(pace,.5);assert(pace.guards[0].x-before>.8);assert.equal(pace.guards.length,3);
console.log('Harder escape remains winnable; interrupted search, pause, patrol count and pace passed.');

const role=fresh();role.x=-3;role.z=1;role.y=.65;role.leader='Dora';assert(!role.interact());assert(!role.tunnelRolled);role.switchLeader();assert(role.interact());assert(role.tunnelRolled);assert(!role.interact(),'cannot collect during roll');tick(role,1);assert(role.interact());assert(role.stick);role.x=-.6;role.z=-3.1;role.y=2.75;assert(!role.interact(),'Enzo cannot squeeze');role.switchLeader();assert(role.interact());assert(role.clip);
const hay=fresh();assert(!hay.hideInHay());hay.x=3;hay.z=1.2;hay.y=1.35;assert(hay.hideInHay());const hz=hay.z;tick(hay,.5,{x:0,z:-1,sneak:false});assert.equal(hay.z,hz);assert(hay.hidden);assert(!hay.jump());assert(hay.hideInHay());assert(hay.dustBath());assert(!hay.jump());tick(hay,1.2);assert(hay.jump());
const edge=fresh();edge.x=-3.79;edge.z=-3.1;edge.y=2.75;edge.step(1/120,{x:-1,z:0,sneak:false});assert(!edge.grounded);assert(edge.jump(),'grace period at shelf edge');assert(!edge.jump(),'grace cannot double jump');
const buffered=fresh();buffered.y=.04;buffered.vy=-1;assert(!buffered.jump());tick(buffered,.1);assert(buffered.vy>0,'early jump press buffered until landing');assert.equal(feeder.surfaceBelow(3,1.2,2),1.35);
console.log('Leader-specific abilities, rolling props, hay hiding, dust rolls, jump grace and buffering passed.');

const gadget=fresh();gadget.phase='room';gadget.x=0;gadget.z=3;gadget.guards=[{x:0,z:5,angle:Math.PI,target:1,distracted:0}];assert(gadget.stun());assert.equal(gadget.stunCharges,1);assert(!gadget.sees(gadget.guards[0]));const gz=gadget.guards[0].z;tick(gadget,2);assert.equal(gadget.guards[0].z,gz);gadget.pause();tick(gadget,5);assert(gadget.guards[0].stunned>1);gadget.pause();tick(gadget,2.1);assert.equal(gadget.guards[0].stunned,0);assert(gadget.guards[0].z!==gz);
const miss=fresh();miss.phase='room';miss.x=-11;miss.z=8;assert(!miss.stun());assert.equal(miss.stunCharges,2);miss.x=-5;miss.z=0;miss.guards=[{x:0,z:0,angle:0,target:0,distracted:0}];assert(!miss.stun(),'cabinets stop pocket dust');
const box=fresh();box.phase='room';box.x=0;box.z=3;box.guards=[];assert(box.toggleBox());box.step(1/120);assert(box.hidden);assert(!box.jump());assert(!box.stun());box.step(1/120,{x:1,z:0,sneak:false});assert(!box.hidden,'moving disguise is visible');box.step(1/120);assert(!box.sees({x:box.x,z:box.z+2,angle:Math.PI,target:0,distracted:0}));assert(box.sees({x:box.x,z:box.z+.4,angle:Math.PI,target:0,distracted:0}));
const intel=fresh();intel.phase='room';intel.badge=true;intel.guards=[];intel.x=10.5;intel.z=-7;assert(!intel.interact(),'exit requires intel');intel.x=8;intel.z=-6;assert(intel.interact());tick(intel,1);assert(!intel.intel);intel.step(1/120,{x:1,z:0,sneak:true});assert.equal(intel.hackProgress,0);assert(intel.interact());tick(intel,3.1);assert(intel.intel);intel.state='caught';intel.retry();assert(!intel.intel);assert.equal(intel.stunCharges,2);assert(!intel.boxed);
const investigate=fresh();investigate.phase='room';investigate.x=0;investigate.z=3;investigate.guards=[{x:0,z:5,angle:Math.PI,target:0,distracted:0}];tick(investigate,.2);assert(investigate.guards[0].lastKnown);investigate.x=-10;investigate.z=-8;tick(investigate,.1);assert.equal(investigate.security,'SEARCHING');tick(investigate,3.2);assert.equal(investigate.security,'PATROL');
console.log('Spy mission, box visibility, stun range/occlusion/recovery, intel gating/reset and investigations passed.');
