import assert from 'node:assert/strict';
import {PitGame,RECIPES} from '../.checks/pit-game.js';
const fresh=(seed=42)=>{const g=new PitGame(seed);g.playing=true;g.auto=false;return g};
const tick=(g,t,input)=>{for(let i=0;i<t*120;i++)g.step(1/120,input)};
const enemy=(g,x,z,boss=false)=>({id:g.serial++,x,z,hp:100,maxHp:100,boss,slow:0,burn:0,poison:0,flash:0});
const ball=(g,x,z,vx,vz,kind='seed')=>({id:g.serial++,x,z,vx,vz,kind,damage:10,life:5,last:-1,lock:0,returns:0});
const wall=fresh();wall.enemies=[enemy(wall,0,-8)];wall.balls=[ball(wall,5.7,0,15,-1)];tick(wall,.05);assert(wall.balls[0].vx<0);assert(wall.balls[0].x<=5.75);
const top=fresh();top.enemies=[enemy(top,0,3)];top.balls=[ball(top,0,-10.9,1,-15)];tick(top,.05);assert(top.balls[0].vz>0);
const collide=fresh();const target=enemy(collide,0,0);collide.enemies=[target];collide.balls=[ball(collide,0,1.3,0,-15)];tick(collide,.07);assert(target.hp<100);assert(collide.balls[0].vz>0,'enemy contact reflects projectile');
const catchBall=fresh();catchBall.balls=[ball(catchBall,-.78,7.1,0,15)];tick(catchBall,.02);assert(catchBall.balls[0].vz<0);assert.equal(catchBall.balls[0].returns,1);assert(catchBall.balls[0].damage>10);
const escape=fresh();escape.balls=[ball(escape,4,8.9,0,15)];tick(escape,.1);assert.equal(escape.balls.length,0);
const fire=fresh();fire.auto=true;fire.step(1/120);assert.equal(fire.balls.length,2);assert.deepEqual(new Set(fire.balls.map(b=>b.kind)),new Set(['seed','stone']));assert(fire.balls.every(b=>b.vz<0));fire.fire();assert.equal(fire.balls.length,2);fire.extra=1;fire.fireTime=0;fire.fire();assert.equal(fire.balls.length,6);
const status=fresh();status.enemies=[enemy(status,0,0),enemy(status,1,0),enemy(status,2,0),enemy(status,0,-2)];status.apply(status.enemies[0],ball(status,0,0,0,0,'steam'));assert(status.enemies.every(e=>e.slow>0&&e.burn>0));let hp=status.enemies[0].hp;tick(status,.2);assert(status.enemies[0].hp<hp);
const chain=fresh();chain.enemies=[enemy(chain,0,0),enemy(chain,1,0),enemy(chain,2,0),enemy(chain,0,-2)];chain.apply(chain.enemies[0],ball(chain,0,0,0,0,'tempest'));assert(chain.enemies.every(e=>e.poison>0&&e.hp<100));
for(let i=0;i<RECIPES.length;i++){const g=fresh(),r=RECIPES[i];assert.equal(g.fuse(i),false);g.orbs=[{kind:r.a,rank:2},{kind:r.b,rank:2}];g.paused=true;assert.equal(g.fuse(i),true);assert.deepEqual(g.orbs,[{kind:r.result,rank:1}]);assert.equal(g.fuse(i),false)}
const upgrade=fresh();upgrade.xp=35;upgrade.step(1/120);assert.equal(upgrade.level,2);assert.equal(upgrade.choice.length,3);const time=upgrade.time;tick(upgrade,1);assert.equal(upgrade.time,time);assert.equal(upgrade.choose('invalid'),false);assert(upgrade.choose(upgrade.choice[0].id));assert.equal(upgrade.choice.length,0);
const pause=fresh();pause.paused=true;pause.auto=true;tick(pause,2);assert.equal(pause.time,0);assert.equal(pause.balls.length,0);
const breach=fresh();breach.enemies=[enemy(breach,0,5.1)];breach.step(1/120);assert.equal(breach.hp,88);
const bossBreach=fresh();bossBreach.wave=12;bossBreach.enemies=[enemy(bossBreach,0,5.1,true)];bossBreach.step(1/120);assert(bossBreach.lost);assert(!bossBreach.won,'boss breach is never a victory');
const win=fresh();win.wave=12;const boss=enemy(win,0,0,true);win.enemies=[boss];win.hit(boss,200);win.step(1/120);assert(win.won);const inventory=JSON.stringify(win.orbs);win.descend();assert.equal(win.depth,2);assert.equal(win.wave,1);assert.equal(JSON.stringify(win.orbs),inventory);assert.equal(win.hp,win.maxHp);
const burst=fresh();burst.charge=50;burst.balls=[ball(burst,0,0,0,15)];burst.burst();assert.equal(burst.charge,0);assert(burst.balls[0].vz<0);
const drill=fresh();drill.enemies=[enemy(drill,0,1),enemy(drill,0,-1),enemy(drill,0,-3)];drill.balls=[{...ball(drill,0,3,0,-15,'drill'),pierce:2,hitIds:[]}];tick(drill,.5);assert(drill.enemies.every(e=>e.hp===90),'drill hits each enemy once');assert(drill.balls[0].vz>0,'drill bounces after two penetrations');
const split=fresh();const acorn=ball(split,0,0,0,15,'scatter'),victim=enemy(split,0,0);split.enemies=[victim];split.balls=[acorn];split.apply(victim,acorn);assert.equal(split.balls.length,3);assert(split.balls.slice(1).every(b=>b.fragment&&b.damage===5));split.apply(victim,acorn);assert.equal(split.balls.length,3,'parent splits once');split.apply(victim,split.balls[1]);assert.equal(split.balls.length,3,'fragments cannot recursively split');
const quill=fresh();const q=ball(quill,0,0,0,15,'shrapnel'),v=enemy(quill,0,0);quill.enemies=[v];quill.balls=[q];quill.apply(v,q);assert.equal(quill.balls.length,5);assert(quill.balls.slice(1).every(b=>b.kind==='drill'&&b.pierce===1));
const drain=fresh();drain.hp=60;const life=enemy(drain,0,0);life.hp=5;drain.enemies=[life];drain.apply(life,ball(drain,0,0,0,0,'leech'));assert(Math.abs(drain.hp-60.6)<.001,'healing counts actual damage, not overkill');drain.hp=99.9;const healthy=enemy(drain,0,0);drain.enemies=[healthy];drain.apply(healthy,ball(drain,0,0,0,0,'leech'));assert.equal(drain.hp,100);
const gale=fresh();const light=enemy(gale,0,0),heavy=enemy(gale,0,0,true);gale.enemies=[light,heavy];gale.apply(light,ball(gale,0,0,0,0,'gale'));gale.apply(heavy,ball(gale,0,0,0,0,'gale'));assert.equal(light.z,-.35);assert.equal(heavy.z,-.06);const near=enemy(gale,1,0);gale.enemies.push(near);gale.hp=50;gale.apply(light,ball(gale,0,0,0,0,'moonwhirl'));assert(near.hp<100&&near.z<0);assert(gale.hp>50);
const cap=fresh();cap.balls=Array.from({length:179},()=>ball(cap,0,0,0,0));cap.apply(enemy(cap,0,0),ball(cap,0,0,0,0,'shrapnel'));assert.equal(cap.balls.length,180,'splinters respect rendering and simulation capacity');
const roam=fresh();roam.enemies=[enemy(roam,5,-9)];tick(roam,3,{x:0,z:-1});assert(roam.z<0,'pair can move into the upper battlefield');tick(roam,5,{x:0,z:-1});assert.equal(roam.z,-10.1);tick(roam,5,{x:1,z:1});assert(roam.x<=4.65&&roam.z<=8.2);
const backward=fresh();backward.z=0;backward.aim={x:0,z:7};backward.fire();assert(backward.balls.every(b=>b.vz>0),'aim downfield from upper arena');tick(backward,.16);assert(backward.balls.every(b=>b.vz>0),'new volleys do not immediately rebound from their own shooters');
const suggest=fresh();assert.equal(suggest.upgrades()[0].id,'seed');suggest.orbs=[{kind:'seed',rank:2},{kind:'stone',rank:1}];assert.equal(suggest.upgrades()[0].id,'stone');suggest.orbs[1].rank=2;suggest.choice=suggest.upgrades();assert(suggest.fusionSuggestions()[0].ready);assert(suggest.fuse(0),'fuse during level-up');assert.equal(suggest.choice.length,3,'fusion retains level-up pick');assert(suggest.choice.every(c=>c.id!=='seed'&&c.id!=='stone'||c.name.startsWith('Learn ')),'no stale upgrade cards for consumed ingredients');assert(suggest.choose(suggest.choice[0].id));
const run=fresh(11);run.auto=true;for(let i=0;i<120*160&&!run.lost&&!run.won;i++){if(run.choice.length){const c=run.choice.find(c=>c.id==='extra')||run.choice.find(c=>c.id==='power')||run.choice[0];run.choose(c.id)}const target=run.alive.sort((a,b)=>b.z-a.z)[0];if(target)run.aim={x:target.x,z:target.z};if(run.charge>=50)run.burst();run.step(1/120)}
console.log(`Simulation: wave ${run.wave}, ${run.kills} kills, ${run.hp} courage, ${run.won?'won':run.lost?'lost':'ongoing'}, level ${run.level}.`);assert.equal(run.wave,12);assert(run.won,'normal auto-fire, aim and upgrades can complete a pit');
console.log('Passed ricochets, paw rebounds, elemental effects, fusion, upgrade gating, pause, breach loss, boss victory and a complete run.');

for(let seed=1;seed<=30;seed++){const g=fresh(seed);assert(g.upgrades().some(c=>c.category==='Passive item'),'level-ups offer a passive');}
const items=fresh();const owned=JSON.stringify(items.orbs);for(const id of ['shell','clock','boots','ribbon','clover','hay']){for(let rank=1;rank<=3;rank++){items.choice=[{id:'item:'+id}];assert(items.choose('item:'+id));assert.equal(items.rank(id),rank)}items.choice=[{id:'item:'+id}];assert(!items.choose('item:'+id),'rank cap enforced');items.choice=[]}assert.equal(JSON.stringify(items.orbs),owned);assert(!items.upgrades().some(c=>c.category==='Passive item'));items.won=true;items.descend();assert.equal(items.rank('boots'),3);assert.deepEqual(fresh().passives,{});
const speed=fresh();speed.passives.boots=2;tick(speed,.5,{x:1,z:0});assert(Math.abs(speed.x-5.5*1.24*.5)<.001);
const shield=fresh();shield.passives.shell=3;shield.enemies=[enemy(shield,0,5.1)];shield.step(1/120);assert.equal(shield.hp,93.4);shield.enemies=[enemy(shield,0,5.1,true)];shield.step(1/120);assert(shield.lost);
const timer=fresh();timer.passives.clock=2;timer.fire();assert(timer.balls.every(b=>b.life===8.4));const frag=ball(timer,0,0,0,1,'scatter');timer.apply(enemy(timer,0,0),frag);assert(timer.balls.filter(b=>b.fragment).every(b=>b.life===5));
const lucky=fresh();lucky.passives={clover:2,ribbon:3};lucky.hit(enemy(lucky,0,0),200);assert.equal(lucky.xp,16);assert.equal(lucky.charge,14);
const heal=fresh();heal.passives.hay=3;heal.hp=50;tick(heal,1);assert(Math.abs(heal.hp-51.2)<.001);heal.paused=true;const healed=heal.hp;tick(heal,1);assert.equal(heal.hp,healed);
const thorn=fresh();thorn.enemies=[enemy(thorn,0,0),enemy(thorn,1,0)];thorn.apply(thorn.enemies[0],ball(thorn,0,0,0,0,'thorn'));assert.equal(thorn.enemies[0].bleed,4);const before=thorn.enemies[0].hp;tick(thorn,.2);assert(thorn.enemies[0].hp<before);thorn.apply(thorn.enemies[0],ball(thorn,0,0,0,0,'bramble'));assert(thorn.enemies.every(e=>e.bleed>0&&e.slow>0&&e.hp<100));
const sun=fresh();sun.enemies=[enemy(sun,0,0),enemy(sun,1,0),enemy(sun,2,0),enemy(sun,-2,0)];sun.apply(sun.enemies[0],ball(sun,0,0,0,0,'sunburst'));assert(sun.enemies.every(e=>e.burn>0&&e.hp<100));assert.equal(sun.enemies[1].hp,89.5);assert.equal(sun.enemies[3].hp,93.5);
for(const kind of ['boomerang','windscythe']){const g=fresh();g.enemies=[enemy(g,5,-8)];g.balls=[{...ball(g,0,0,0,-15,kind),age:1.3}];g.step(1/120);assert(g.balls[0].vz>0,'returning weapon steers to pair');tick(g,1);assert.equal(g.balls.length,0,'returning weapon is caught');}
console.log('Passed all eight recipes, passive choice/rank/persistence, six passive effects, bleeding, returning blades and Sunburst splash/arcs.');
