'use client';
import {useEffect,useRef,useState} from 'react';
import {FlappyGame,FLIGHT} from '../../lib/flappy-game';
import {drawFlight} from '../../lib/flappy-scene';
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new FlappyGame(42)),last=useRef(0),[frame,setFrame]=useState(0),[best,setBest]=useState(0),[error,setError]=useState(false),sound=useRef(false),audio=useRef<AudioContext|null>(null),savedBest=useRef(0),[audible,setAudible]=useState(false);const g=game.current;
 function tone(event:string){if(!sound.current)return;try{audio.current??=new AudioContext();const a=audio.current;void a.resume();const o=a.createOscillator(),v=a.createGain();o.type=event==='crash'?'triangle':'sine';const f=event==='perfect'?880:event==='point'?600:event==='crash'?150:event==='win'?1100:360;o.frequency.setValueAtTime(f,a.currentTime);o.frequency.exponentialRampToValueAtTime(event==='crash'?60:f*1.4,a.currentTime+.12);v.gain.setValueAtTime(.035,a.currentTime);v.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(v);v.connect(a.destination);o.start();o.stop(a.currentTime+.17)}catch{}}
 function flap(){if(game.current.canRetry){restart();return}game.current.flap();canvas.current?.focus();setFrame(v=>v+1)}
 function restart(){if(!game.current.canRetry)return;game.current=new FlappyGame();game.current.flap();canvas.current?.focus();setFrame(v=>v+1)}
 function pause(){game.current.pause();canvas.current?.focus();setFrame(v=>v+1)}
 useEffect(()=>{try{const n=Number(localStorage.getItem('border-hop-best'));if(Number.isFinite(n)&&n>=0){savedBest.current=n;setBest(n)}}catch{}const c=canvas.current?.getContext('2d');if(!c){setError(true);return}let raf=0,acc=0,ui=0;const loop=(now:number)=>{acc+=last.current?Math.min(.1,(now-last.current)/1000):0;last.current=now;while(acc>=1/120){game.current.step(1/120);acc-=1/120}for(const event of game.current.events.splice(0))tone(event);drawFlight(c,game.current,now/1000);if(game.current.points>savedBest.current){savedBest.current=game.current.points;setBest(savedBest.current);try{localStorage.setItem('border-hop-best',String(savedBest.current))}catch{}}if(now-ui>70){setFrame(v=>v+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();if(!e.repeat)flap()}if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();if(!e.repeat)pause()}};const blur=()=>{if(game.current.state==='playing')game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('blur',blur);return()=>{cancelAnimationFrame(raf);last.current=0;window.removeEventListener('keydown',down);window.removeEventListener('blur',blur);void audio.current?.close();audio.current=null}},[]);
 void frame;
 return <main className="flight-shell"><header className="flight-header"><a href="/">← MAIN ARCADE <span>BORDER HOP</span></a><button className="flight-sound" aria-pressed={audible} onClick={()=>{sound.current=!sound.current;setAudible(sound.current);tone('point');canvas.current?.focus()}}>Sound {audible?'on':'off'}</button></header><section className="flight-heading"><div><p className="flight-eyebrow">TWO CHINCHILLAS. ONE BIG TRIP.</p><h1>Little wings.<br/><em>Big American dream.</em></h1></div><p>Flap through the desert checkpoints.<br/>Get both friends through 20 gaps to reach<br/>the Welcome to the USA gate.</p></section>
 <section className="flight-board" aria-label="Border Hop game"><div className="flight-hud"><div><small>CHECKPOINTS</small><strong>{g.score}<span> / {FLIGHT.goal}</span></strong></div><div className="flight-route"><span>DESERT</span><div><i style={{width:g.score/FLIGHT.goal*100+'%'}}/></div><span>USA ★</span></div><div><small>BEST POINTS</small><strong>{best}</strong></div><button onClick={pause} disabled={g.state!=='playing'&&g.state!=='paused'} aria-label={g.state==='paused'?'Resume game':'Pause game'}>{g.state==='paused'?'▶':'Ⅱ'}</button></div>
 <div className="flight-canvas-wrap"><canvas ref={canvas} width={900} height={540} tabIndex={0} aria-label="Dora and Enzo fly together. Press Space, Up, or tap to flap. Avoid checkpoint columns and the ground." onPointerDown={e=>{e.preventDefault();flap()}}/>
 {(g.state==='ready'||g.state==='paused'||(g.state==='lost'&&g.endTime>=.4)||g.state==='won'||error)&&<div className={'flight-overlay '+(g.state==='ready'?'flight-ready':'')} onPointerDown={e=>{if((g.state==='lost'||g.state==='won')&&!(e.target as HTMLElement).closest('button'))flap()}}><div><span className="flight-eyebrow">{error?'CANVAS UNAVAILABLE':g.state==='won'?'ARRIVAL STAMP · USA':g.state==='lost'?'A LITTLE TURBULENCE':g.state==='paused'?'TAKE A BREATHER':'PASSPORTS? PAWS-PORTS.'}</span><h2>{error?'Please try another browser.':g.state==='won'?'Welcome, Dora & Enzo!':g.state==='lost'?'One more hop?':g.state==='paused'?'Trip paused.':'Ready for takeoff?'}</h2><p>{g.state==='won'?`All 20 checkpoints cleared! ${g.points} points · ${g.perfect} Perfect Pairs.`:g.state==='lost'?`${g.hitHero<0?'The pair':g.hitHero===0?'Dora':'Enzo'} clipped ${g.hitReason}. ${g.points} points · ${g.perfect} Perfect Pairs.`:g.state==='paused'?'Dora and Enzo are waiting for you.':'One tap lifts both chinchillas. Release to glide down.'}</p>{!error&&<button className="flight-primary" disabled={(g.state==='lost'||g.state==='won')&&!g.canRetry} onClick={g.state==='ready'?flap:g.state==='paused'?pause:restart}>{g.state==='ready'?'Let’s flap →':g.state==='paused'?'Continue the trip →':'Space / tap to fly again →'}</button>}</div></div>}
 </div><div className="flight-rewards"><b>{g.points} POINTS</b><span>✦ {g.perfect} Perfect Pairs</span><small>100 per gap · +50 when both cross near the center</small></div><div className="flight-controls"><span><kbd>SPACE</kbd> / <kbd>↑</kbd> / TAP to flap</span><span><kbd>P</kbd> pause · Both friends must clear each gap</span></div></section>
 <section className="flight-bottom"><div><span className="flight-portrait flight-dora">D</span><p><b>Dora</b><span>White fluff. Front-seat flyer.</span></p><span className="flight-portrait flight-enzo">E</span><p><b>Enzo</b><span>Grey fluff. Never left behind.</span></p></div><p>A desert postcard starring Dora & Enzo.<br/>Paper wings. Shared dreams. One more try.</p></section></main>
}
