export type Input={left:boolean;right:boolean;jump:boolean};
export type Platform={x:number;y:number;w:number;kind?:'lift'|'bridge'};
export type Pet={x:number;y:number;vx:number;vy:number;ground:boolean;face:number;support:string;safeX:number};
export type Mode='solo'|'duo';
export const SIZE=.75,HEIGHT=1.38,GRAVITY=22;
export const rooms=[
 {title:'The counterweight',short:'A helping paw goes a long way.',hint:'Park Grey on the gold floor pad. White rides the lift and presses the upper button.',platforms:[{x:4.9,y:1.2,w:2},{x:10.4,y:4,w:2.4},{x:14,y:3.6,w:2.5},{x:17.4,y:4.7,w:3.2}],snack:{x:19,y:4.94}},
 {title:'The pantry door',short:'A little muscle. A little mischief.',hint:'Use Grey to push the crate onto the brass pad. The pantry gate will stay open.',platforms:[{x:11.4,y:1.2,w:2.1},{x:14.5,y:2.5,w:2.3},{x:18,y:3.8,w:3}],snack:{x:19.6,y:4.04}},
 {title:'A snack-sized bridge',short:'The best way home is together.',hint:'Cross the gap, climb the right-hand shelves, and grab the snack. Bring it back to the gap.',platforms:[{x:5.7,y:1.2,w:2.0},{x:8.4,y:2.4,w:1.6},{x:12.7,y:1.2,w:1.8},{x:15.3,y:2.45,w:2.4},{x:18.6,y:4.1,w:2.6}],snack:{x:20,y:4.34}}
];
export class Game{
 room:number;mode:Mode;active=0;playing=false;paused=false;won=false;clock=0;gate=false;liftY=.25;plate=false;bridge=false;together=false;message='';messageFor=0;events:string[]=[];lastTower=-10;crate={x:4.1,y:0,w:1.5,h:1.1};pets:Pet[];snack:{x:number;y:number;vy:number;length:number;owner:number;vertical:boolean};
 constructor(room=0,mode:Mode='solo'){this.room=room;this.mode=mode;this.pets=[1.2,2.25].map(x=>({x,y:0,vx:0,vy:0,ground:true,face:1,support:'floor',safeX:x}));this.snack={...rooms[room].snack,vy:0,length:3,owner:-1,vertical:false};}
 say(s:string){this.message=s;this.messageFor=4.5}
 platforms():Platform[]{const floor=this.room===2?[{x:0,y:0,w:9.5},{x:11.6,y:0,w:10.4}]:[{x:0,y:0,w:22}];const p:Platform[]=[...floor,...rooms[this.room].platforms];if(this.room===0)p.push({x:7.6,y:this.liftY,w:2.1,kind:'lift'});if(this.room===1)p.push({x:this.crate.x,y:this.crate.h,w:this.crate.w});if(this.bridge)p.push({x:9.4,y:.25,w:2.3,kind:'bridge'});return p;}
 action(action:string,who=this.active){if(!this.playing||this.paused||this.won)return;const p=this.pets[who];
 if(action==='switch'){this.active=1-this.active;this.events.push('switch')}
 if(action==='grab'){if(this.bridge){this.say('Cross with both friends, then press B on the left to pick the bridge back up.');return}if(this.snack.owner===who){this.snack.owner=-1;this.snack.vy=1.2;this.together=false;this.say('Snack set down.')}else if(Math.hypot(p.x+.4-this.snack.x,p.y+.8-this.snack.y)<1.6){this.snack.owner=who;this.events.push('grab');this.say('The snack is yours. Bring it and both friends home.')}else this.say('Get a little closer to the snack and press E.');}
 if(action==='rotate'&&this.snack.owner>=0){this.snack.vertical=!this.snack.vertical;this.events.push('switch');this.say(this.snack.vertical?'Snack upright. Mind the whiskers!':'Snack held sideways.');}
 if(action==='nibble'&&this.snack.owner>=0){const min=this.room===2?2.35:1.1;this.snack.length=Math.max(min,this.snack.length-.22);this.events.push('nibble');this.say(this.snack.length===min?'That is enough nibbling—save the rest for home!':'A little nibble. A little less snack.');}
 if(action==='tower'){const[a,b]=this.pets;if(Math.abs(a.x-b.x)<1.5&&Math.abs(a.y-b.y)<1.7&&b.ground&&this.clock-this.lastTower>1.2){a.x=b.x;a.y=b.y+1.15;a.vy=10.2;a.ground=false;this.active=0;this.lastTower=this.clock;this.events.push('jump');this.say('Up you go! Guide White with the movement keys.')}else this.say('Bring White close to Grey on a steady platform, then press T.');}
 if(action==='team'){if(this.snack.owner>=0&&Math.abs(this.pets[0].x-this.pets[1].x)<2.3&&Math.abs(this.pets[0].y-this.pets[1].y)<1.6){this.together=!this.together;this.say(this.together?'Together. Your buddy follows in solo mode.':'Moving separately.')}else this.say('Hold the snack and bring your friend close, then press F.');}
 if(action==='bridge'){if(this.room!==2){this.say('You will need a snack bridge in the final room.');return}if(this.bridge){if(this.pets.every(a=>a.x+SIZE<9.35)&&p.x>6.5){this.bridge=false;this.snack.owner=who;this.say('Bridge packed. Take the snack and both friends home!');this.events.push('grab')}else this.say('Both friends must cross to the left before packing up the bridge.');}else if(this.snack.owner===who&&p.x>7.0&&p.x<13.9&&p.y<1.0){this.bridge=true;this.snack.owner=-1;this.snack.vertical=false;this.snack.x=10.55;this.snack.y=.13;this.together=false;this.events.push('gate');this.say('Snack bridge ready. Cross with both friends, then press B on the left to retrieve it.');}else this.say('Carry the snack to ground level beside the gap, then press B.');}
 }
 step(dt:number,input:Input[]){if(!this.playing||this.paused||this.won)return;dt=Math.min(dt,1/30);this.clock+=dt;this.messageFor=Math.max(0,this.messageFor-dt);const oldLift=this.liftY;
 if(this.room===0){const grey=this.pets[1];this.plate=grey.x+SIZE>3.5&&grey.x<4.6&&grey.y<.06;const goal=this.plate||this.gate?2.6:.25;this.liftY+=Math.sign(goal-this.liftY)*Math.min(Math.abs(goal-this.liftY),dt*.9);for(const p of this.pets)if(p.support==='lift'&&p.ground)p.y+=this.liftY-oldLift;}
 this.pets.forEach((p,i)=>{let keys=input[i]||{left:false,right:false,jump:false};if(this.mode==='solo'&&i!==this.active){keys={left:false,right:false,jump:false};if(this.together){const lead=this.pets[this.active],dx=lead.x-p.x;keys={left:dx< -1.25,right:dx>1.25,jump:p.ground&&(lead.y>p.y+.5||Math.abs(dx)>2.3)}}}const direction=+keys.right-+keys.left;const carrying=this.snack.owner===i;const speed=carrying?(this.room===2?1.55:3.4):4.35;p.vx=direction*speed;if(direction)p.face=direction;if(keys.jump&&p.ground){p.vy=i===0?9.9:8.5;p.ground=false;p.support='';this.events.push('jump')}
 const oldX=p.x,oldY=p.y;p.x=Math.max(.25,Math.min(21.1,p.x+p.vx*dt));
 if(this.room===1){const c=this.crate;if(p.y<c.h-.06&&p.x+SIZE>c.x&&p.x<c.x+c.w){if(i===1)c.x=Math.max(3.1,Math.min(8.15,c.x+p.vx*dt));p.x=oldX<c.x?c.x-SIZE:c.x+c.w;}
 if(!this.gate&&p.x+SIZE>9.8&&p.x<10.15)p.x=oldX<9.8?9.8-SIZE:10.15;
 if(this.gate&&carrying&&!this.snack.vertical&&this.snack.length>1.94&&((oldX<9.8&&p.x+SIZE>=9.8)||(oldX>10.15&&p.x<=10.15))){p.x=oldX;this.say('The snack is too wide. Press R to turn it upright, or N to nibble it shorter.');}}
 p.vy-=GRAVITY*dt;p.y+=p.vy*dt;p.ground=false;p.support='';let top=-Infinity;let kind='';for(const s of this.platforms()){if(p.vy<=0&&oldY>=s.y-(s.kind==='bridge'?.30:.06)&&p.y<=s.y&&p.x+SIZE>s.x+.03&&p.x<s.x+s.w-.03&&s.y>top){top=s.y;kind=s.kind||(s.y===0?'floor':'shelf');}}if(top!==-Infinity){p.y=top;p.vy=0;p.ground=true;p.support=kind;if(kind==='floor')p.safeX=p.x;}
 if(p.y< -3){p.x=p.safeX;p.y=0;p.vy=0;this.events.push('rescue');this.say('Soft landing. Try again—or make a snack bridge with B.');}
 });
 if(this.room===0&&!this.gate){const p=this.pets[0];if(p.x+SIZE>11.4&&p.x<12.6&&Math.abs(p.y-4)<.08){this.gate=true;this.events.push('gate');this.say('Lift locked at the top. Grey can leave the pad and join you.');}}
 if(this.room===1&&!this.gate&&this.crate.x>7.0&&this.crate.x<8.1){this.gate=true;this.events.push('gate');this.say('Pantry open! Find the snack on the high shelf.');}
 const snack=this.snack;if(this.bridge){snack.x=10.55;snack.y=.13;}else if(snack.owner>=0){const p=this.pets[snack.owner];snack.x=p.x+.4;snack.y=p.y+.72;snack.vy=0;}else{const old=snack.y;snack.vy-=GRAVITY*dt;snack.y+=snack.vy*dt;for(const s of this.platforms()){if(old>=s.y+.13-.015&&snack.y<=s.y+.13&&snack.x>s.x&&snack.x<s.x+s.w){snack.y=s.y+.13;snack.vy=0;}}if(snack.y< -2){Object.assign(snack,{...rooms[this.room].snack,vy:0});this.say('The snack rolled back to its shelf.');}}
 if(this.pets.every(p=>p.x<3.0&&p.y<.2)&&snack.x<3.3&&snack.y<1.5&&!this.bridge){this.won=true;this.events.push('win');}
 }
 objective(){if(this.won)return 'Both friends home. Heist complete.';if(this.messageFor>0)return this.message;if(this.bridge)return 'Cross with both friends. Press B on the left to retrieve your snack bridge.';if(this.snack.owner>=0)return this.room===2?'Bring the snack beside the gap at ground level. B makes a bridge.':'Bring the snack and both chinchillas back to the HOME marker.';if(this.gate)return 'Find the glowing snack on the far shelf. E picks it up.';return rooms[this.room].hint;}
}
