import * as T from 'three';
import {createChinchilla,animateChinchilla} from './chinchilla';
import {Game,rooms} from './game';
export class World {
 scene=new T.Scene();camera:T.OrthographicCamera;renderer:T.WebGLRenderer;environment=new T.Group();puzzle=new T.Group();pets=[createChinchilla(true),createChinchilla(false)];width=24;disposed=false;closeView=false;level=-99;lift=new T.Group();crate=new T.Group();gate=new T.Group();snack=new T.Group();pad:T.Mesh|undefined;button:T.Mesh|undefined;marker=new T.Group();snackLight=new T.PointLight(0xffd285,2.5,4);textures:T.Texture[]=[];
 constructor(public canvas:HTMLCanvasElement){this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.scene.background=new T.Color('#b7b4c1');this.scene.fog=new T.Fog('#b7b4c1',36,70);this.camera=new T.OrthographicCamera(-12,12,6.75,-6.75,.1,100);this.camera.position.set(11,8,24);this.camera.lookAt(11,4,0);this.scene.add(new T.HemisphereLight(0xe1e5ff,0x755848,2.1));const sun=new T.DirectionalLight(0xffe5ba,3.6);sun.position.set(-3,13,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:15,bottom:-15,near:.1,far:50});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;sun.shadow.radius=4;this.scene.add(sun);const rim=new T.DirectionalLight(0xc0c9ff,2.8);rim.position.set(14,9,-7);this.scene.add(rim);this.scene.add(this.environment,this.puzzle);this.pets.forEach(p=>this.scene.add(p.root));this.buildRoom();this.setRoom(-1);this.resize();}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);const aspect=w/h;this.camera.left=-this.width/2;this.camera.right=this.width/2;this.camera.top=this.width/aspect/2;this.camera.bottom=-this.width/aspect/2;this.camera.updateProjectionMatrix()}
 wood(color=0xaa7446){const m=new T.MeshStandardMaterial({color,roughness:.87});m.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vGrain;').replace('#include <begin_vertex>','#include <begin_vertex>\nvGrain=position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vGrain;').replace('#include <color_fragment>','#include <color_fragment>\nfloat grain=sin(vGrain.x*3.0+sin(vGrain.z*16.0)*.9+sin(vGrain.y*6.0))*.04+sin(vGrain.z*83.0+sin(vGrain.x*2.0)*2.0)*.025;diffuseColor.rgb+=grain;');};return m;}
 box(parent:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,mat:T.Material){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 buildRoom(){const room=this.environment;const wood=this.wood(0xa97650);for(let x=-4;x<28;x+=2.4)this.box(room,x,-.20,-3.95,2.38,.4,3.3,this.wood(x%3===0?0x9a6549:0xab7953));this.box(room,11,5.5,-5,34,11,.3,new T.MeshStandardMaterial({color:0xc9bfaf,roughness:1}));this.box(room,11,.5,-4.8,34,1,.2,wood);for(let x=-5;x<30;x+=4.4)this.box(room,x,5.5,-4.72,.08,10,.09,new T.MeshStandardMaterial({color:0xafa08d,roughness:1}));
 // A deep window, moonlit glass and a warm work lamp frame the miniature room.
 const frame=this.wood(0x715346);this.box(room,16,6.3,-4.63,6,5,.3,frame);this.box(room,16,6.3,-4.4,5.65,4.65,.05,new T.MeshStandardMaterial({color:0x7788a4,emissive:0x596f94,emissiveIntensity:.38,roughness:.25}));this.box(room,16,6.3,-4.25,.13,4.7,.17,frame);this.box(room,16,6.3,-4.25,5.7,.12,.17,frame);this.box(room,16,3.87,-4.05,6.4,.19,1.1,wood);const moon=new T.Mesh(new T.SphereGeometry(.37,32,24),new T.MeshBasicMaterial({color:0xfff0cc}));moon.position.set(17.7,7.7,-4.30);room.add(moon);
 const cloth=new T.MeshStandardMaterial({color:0x6e547f,roughness:1});const cushion=new T.Mesh(new T.TorusGeometry(1.10,.26,14,44),cloth);cushion.rotation.x=Math.PI/2;cushion.scale.y=.75;cushion.position.set(20.4,.35,-2.3);room.add(cushion);const pad=new T.Mesh(new T.SphereGeometry(1,32,16),cloth);pad.scale.set(1.0,.17,.79);pad.position.set(20.4,.16,-2.3);room.add(pad);cushion.castShadow=pad.castShadow=true;
 // Open wooden home cubby: its entrance remains visible from the play camera.
 this.box(room,1.55,1.1,-2.2,3.5,2.2,.16,wood);this.box(room,-.12,1.1,-1.05,.2,2.2,2.4,wood);this.box(room,3.22,1.1,-1.05,.2,2.2,2.4,wood);this.box(room,1.55,2.27,-1.05,3.7,.20,2.6,wood);this.box(room,1.55,.09,-1.05,3.3,.13,2.5,cloth);
 for(let i=0;i<4;i++){const b=this.box(room,6.5+i*.65,.9+i*.08,-3.8,.58,1.8+i*.16,1.3,new T.MeshStandardMaterial({color:[0x8a604a,0x71827b,0xb99566,0x575766][i],roughness:.9}));b.rotation.z=(i-1)*.035;}
 this.box(room,10,4.5,-4.5,3.4,.18,1.1,wood);const metal=new T.MeshStandardMaterial({color:0xae946f,metalness:.65,roughness:.3});const shade=new T.Mesh(new T.ConeGeometry(.65,.70,32,1,true),metal);shade.position.set(10,5.4,-3.85);room.add(shade);const lamp=new T.PointLight(0xffd39a,13,7);lamp.position.set(10,5.1,-3.6);room.add(lamp);
 }
 label(text:string,x:number,y:number,z:number,color='#f4dfbd',parent:T.Object3D=this.puzzle){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d')!;ctx.font='600 32px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='rgba(23,30,38,.85)';ctx.beginPath();ctx.roundRect(10,10,492,76,22);ctx.fill();ctx.fillStyle=color;ctx.fillText(text,256,48);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;this.textures.push(tex);const sprite=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sprite.position.set(x,y,z);sprite.scale.set(2.7,.506,1);parent.add(sprite);return sprite;}
 clearPuzzle(){this.puzzle.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line||o instanceof T.LineSegments||o instanceof T.Sprite){if('geometry' in o)o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}});this.puzzle.clear();this.textures.forEach(t=>t.dispose());this.textures=[];}
 setRoom(level:number){if(this.level===level)return;this.level=level;this.clearPuzzle();this.lift=new T.Group();this.crate=new T.Group();this.gate=new T.Group();this.snack=new T.Group();this.marker=new T.Group();this.pad=undefined;this.button=undefined;this.puzzle.add(this.lift,this.crate,this.gate,this.snack,this.marker,this.snackLight);
 const floor=this.wood(0xa77a56);const spans=level===2?[[-4,9.5],[11.6,28]]:[[-4,28]];for(const [a,b] of spans){for(let x=a;x<b;x+=.8){const w=Math.min(.79,b-x);this.box(this.puzzle,x+w/2,-.19,.15,w,.38,4.6,floor)}}
 if(level===2){this.box(this.puzzle,10.55,-1.3,.1,2.15,.2,4.6,new T.MeshStandardMaterial({color:0x343c47,roughness:.9}));this.label('B · SNACK BRIDGE',10.55,-.73,2.25);}
 if(level<0){this.snack.visible=false;this.marker.visible=false;this.snackLight.visible=false;return}
 this.snackLight.visible=true;const wood=this.wood(0xc38f55),edge=this.wood(0x865731),metal=new T.MeshStandardMaterial({color:0xab9575,metalness:.65,roughness:.45});
 for(const p of rooms[level].platforms){this.box(this.puzzle,p.x+p.w/2,p.y-.14,.15,p.w,.28,2.35,wood);this.box(this.puzzle,p.x+p.w/2,p.y-.18,1.34,p.w,.12,.10,edge);for(const x of [p.x+.15,p.x+p.w-.15]){this.box(this.puzzle,x,p.y/2-.2,-.79,.13,p.y-.4,.16,edge);this.box(this.puzzle,x,p.y-.65,.15,.09,.9,.09,metal);}}
 this.label('HOME',1.5,-.50,2.15,'#e4cead');
 if(level===0){this.box(this.lift,8.65,-.14,.15,2.1,.28,2.35,this.wood(0xa78e63));for(const x of [7.8,9.45]){this.box(this.puzzle,x,2.3,-.8,.10,4.5,.13,metal);this.box(this.puzzle,x,4.59,-.8,.35,.1,.3,metal)}this.pad=this.box(this.puzzle,4.02,.045,.2,1.1,.09,1.6,new T.MeshStandardMaterial({color:0xc9a45c,emissive:0x6f4a16,emissiveIntensity:.25,metalness:.4,roughness:.5}));this.label('GREY · HOLD',4.02,.40,1.6);this.button=this.box(this.puzzle,11.9,4.07,.15,.8,.14,1.2,new T.MeshStandardMaterial({color:0xd7b565,emissive:0x88632c,emissiveIntensity:.3,roughness:.4}));this.label('WHITE · PRESS',11.9,4.68,1.0);}
 if(level===1){this.box(this.crate,.75,.55,0,1.5,1.1,1.3,edge);for(const x of [.12,1.38])this.box(this.crate,x,.55,.69,.10,1.0,.08,wood);for(const y of [.13,.97])this.box(this.crate,.75,y,.69,1.3,.10,.08,wood);const diagonal=this.box(this.crate,.75,.55,.70,1.45,.10,.08,wood);diagonal.rotation.z=.55;this.pad=this.box(this.puzzle,7.78,.04,0,1.6,.08,1.7,new T.MeshStandardMaterial({color:0xc9a45c,metalness:.4,roughness:.4}));this.label('CRATE HERE',7.8,.40,1.6);for(const z of [-.6,.6])this.box(this.gate,9.99,3.3,z,.24,6.6,.17,metal);for(let y=.25;y<6.6;y+=.45)this.box(this.gate,9.99,y,0,.18,.1,1.45,metal);this.label('PANTRY',10,7.0,.3);}
 const snackCore=new T.Mesh(new T.CylinderGeometry(.125,.125,3,14),new T.MeshStandardMaterial({color:0x956733,roughness:.95}));snackCore.rotation.z=Math.PI/2;this.snack.add(snackCore);snackCore.castShadow=true;const seeds=new T.InstancedMesh(new T.SphereGeometry(1,5,4),new T.MeshStandardMaterial({color:0xd1af61,roughness:.92}),240);const obj=new T.Object3D(),color=new T.Color();for(let i=0;i<240;i++){const a=i*2.399963;obj.position.set((i/239-.5)*2.98,Math.sin(a)*.121,Math.cos(a)*.121);obj.scale.set(.040,.026,.052);obj.rotation.set(a,a*.3,a*.7);obj.updateMatrix();seeds.setMatrixAt(i,obj.matrix);color.setHSL(.105+(i%5)*.012,.25+(i%4)*.1,.26+(i%7)*.044);seeds.setColorAt(i,color)}this.snack.add(seeds);
 const cone=new T.Mesh(new T.ConeGeometry(.13,.20,3),new T.MeshBasicMaterial({color:0xffd694}));cone.rotation.z=Math.PI;this.marker.add(cone);this.label('E · GRAB',0,.52,0,'#f8d493',this.marker);
 }
 quality(detailed:boolean){this.renderer.setPixelRatio(detailed?Math.min(window.devicePixelRatio,1.7):1);this.renderer.shadowMap.enabled=detailed;this.pets.forEach(p=>p.fur.forEach(f=>f.geometry.setDrawRange(0,detailed?Infinity:Math.floor(f.geometry.getAttribute('position').count/12)*4)));this.resize()}
 render(time:number,game?:Game|null){const desired=game?game.room:-1;this.setRoom(desired);const width=game?(this.closeView?14:24):20;if(width!==this.width){this.width=width;this.resize()}
 if(!game){this.pets.forEach((p,i)=>{p.root.position.set(12.1+i*2.4,.02,i===0?.4:-.2);p.root.scale.setScalar(1.65);animateChinchilla(p,time,0,true,i===0?1:-1)});this.camera.position.set(11,7.4,22);this.camera.lookAt(11,3.2,0)}else{
 const follow=this.closeView?T.MathUtils.clamp(game.pets[game.active].x+1.0,5.6,16.2):11;const up=this.closeView?Math.max(2.1,game.pets[game.active].y+1.3):4.0;this.camera.position.set(follow,up+4.0,24);this.camera.lookAt(follow,up,0);this.pets.forEach((model,i)=>{const p=game.pets[i];model.root.position.set(p.x+.37,p.y+.01,i===0?.20:-.13);model.root.scale.setScalar(1);animateChinchilla(model,game.clock,p.vx,p.ground,p.face,game.won)});
 this.lift.position.y=game.liftY;this.crate.position.x=game.crate.x;this.gate.position.y=game.gate?6.8:0;if(this.pad)(this.pad.material as T.MeshStandardMaterial).color.set(game.plate||game.gate?0x9ab585:0xc9a45c);if(this.button)(this.button.material as T.MeshStandardMaterial).color.set(game.gate?0x9ab585:0xd7b565);
 const s=game.snack;this.snack.visible=true;this.snack.position.set(s.x,s.y,.7);this.snack.rotation.z=s.vertical?Math.PI/2:0;this.snack.scale.set(game.bridge?2.3/3:s.length/3,1,1);this.snackLight.position.set(s.x,s.y+.25,.5);this.snackLight.intensity=s.owner<0&&!game.bridge?2.3:0;this.marker.visible=s.owner<0&&!game.bridge&&!game.won;this.marker.position.set(s.x,s.y+.6+Math.sin(time*2.4)*.08,.5);
 }
 this.renderer.render(this.scene,this.camera)}
 dispose(){this.disposed=true;const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>();this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments||o instanceof T.Line){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m)}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());this.textures.forEach(t=>t.dispose());this.renderer.dispose()}
}
