'use client';
import {useEffect,useRef,useState} from 'react';
import {Patrol,BOXES,HOME} from '../../lib/legacy/midnight-patrol/fps-game';
import type {FPSWorld} from '../../lib/legacy/midnight-patrol/fps-scene';
import {Pause,Play,RotateCcw,Volume2,VolumeX,HelpCircle,ChevronRight,Heart,Maximize,Target,MousePointer2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
const empty={health:100,stamina:100,ammo:12,reload:0,found:0,bots:0,won:false,message:'',hurt:0,hit:0,x:-9,z:9,yaw:0,buddyX:-7.5,buddyZ:10,time:0,accuracy:0,targets:[] as {x:number;z:number;taken:boolean}[],enemies:[] as {x:number;z:number;hp:number}[]};
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),world=useRef<FPSWorld|null>(null),game=useRef<Patrol|null>(null),keys=useRef(new Set<string>()),firing=useRef(false),dragging=useRef(false),soundRef=useRef(false),audio=useRef<AudioContext|null>(null),wasLocked=useRef(false);const[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[locked,setLocked]=useState(false),[help,setHelp]=useState(false),[white,setWhite]=useState(true),[sound,setSound]=useState(false),[detail,setDetail]=useState(true),[hud,setHud]=useState(empty);
 function tone(event:string){if(!soundRef.current)return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();const o=c.createOscillator(),v=c.createGain();o.type=event==='fire'?'triangle':'sine';const f=event==='fire'?430:event==='hurt'?140:event==='snack'?820:event==='disabled'?620:330;o.frequency.setValueAtTime(f,c.currentTime);o.frequency.exponentialRampToValueAtTime(f*(event==='snack'?1.4:.5),c.currentTime+.13);v.gain.setValueAtTime(.04,c.currentTime);v.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.connect(v);v.connect(c.destination);o.start();o.stop(c.currentTime+.2)}catch{}}
 function capture(){const c=canvas.current;if(!c)return;c.focus();try{Promise.resolve(c.requestPointerLock()).catch(()=>setLocked(false))}catch{setLocked(false)}}
 function begin(){const g=new Patrol();g.playing=true;game.current=g;world.current?.setPet(white);world.current?.quality(detail);keys.current.clear();firing.current=false;setHud(empty);setStarted(true);setPaused(false);capture()}
 function pause(){const g=game.current;if(!g||g.won)return;g.paused=true;setPaused(true);keys.current.clear();firing.current=false;dragging.current=false;if(document.pointerLockElement)document.exitPointerLock()}
 function resume(){if(game.current)game.current.paused=false;setPaused(false);capture()}
 function title(){game.current=null;keys.current.clear();firing.current=false;setStarted(false);setPaused(false);setHud(empty);if(document.pointerLockElement)document.exitPointerLock()}
 useEffect(()=>{let stop=false,frame=0,last=0,acc=0,ui=0;const resize=()=>world.current?.resize();import('../../lib/legacy/midnight-patrol/fps-scene').then(({FPSWorld})=>{if(stop||!canvas.current)return;try{world.current=new FPSWorld(canvas.current);setReady(true);const loop=(now:number)=>{const dt=last?Math.min((now-last)/1000,.1):0;last=now;const g=game.current;if(g){acc+=dt;while(acc>=1/120){const k=keys.current;if(!g.paused&&!g.won){if(k.has('arrowleft'))g.player.yaw+=1.7/120;if(k.has('arrowright'))g.player.yaw-=1.7/120;if(k.has('arrowup'))g.player.pitch=Math.min(1.3,g.player.pitch+1.3/120);if(k.has('arrowdown'))g.player.pitch=Math.max(-1.3,g.player.pitch-1.3/120)}g.step(1/120,{forward:+k.has('w')-+k.has('s'),strafe:+k.has('d')-+k.has('a'),jump:k.has(' '),sprint:k.has('shift'),fire:firing.current});acc-=1/120}for(const e of g.events.splice(0)){tone(e);if(e==='win'&&document.pointerLockElement)document.exitPointerLock()}if(now-ui>70){setHud({health:Math.ceil(g.health),stamina:g.stamina,ammo:g.ammo,reload:g.reload,found:g.found,bots:g.disabled,won:g.won,message:g.messageFor?g.message:'',hurt:g.hurt,hit:g.hit,x:g.player.x,z:g.player.z,yaw:g.player.yaw,buddyX:g.buddy.x,buddyZ:g.buddy.z,time:g.time,accuracy:g.fired?Math.round(g.hits/g.fired*100):0,targets:g.snacks.map(s=>({...s})),enemies:g.bots.map(b=>({...b}))});ui=now}}else acc=0;world.current?.render(now/1000,g);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setFailure('The 3D view needs WebGL 2 and hardware acceleration. Try a recent desktop browser.')}}).catch(()=>setFailure('The game could not load. Check your connection and reload.'));const loss=(e:Event)=>{e.preventDefault();pause();setFailure('The 3D view was interrupted. Reload the game to restart.')};canvas.current?.addEventListener('webglcontextlost',loss);return()=>{stop=true;cancelAnimationFrame(frame);window.removeEventListener('resize',resize);canvas.current?.removeEventListener('webglcontextlost',loss);world.current?.dispose();world.current=null;void audio.current?.close();audio.current=null}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('[role="dialog"],input,select'))return;const g=game.current;if(!g)return;const k=e.key.toLowerCase();if([' ','arrowleft','arrowright','arrowup','arrowdown'].includes(k))e.preventDefault();if(e.repeat)return;keys.current.add(k);if(k==='p'||k==='escape'){pause();return}if(k==='r')g.startReload();if(k==='q'&&!g.paused){g.pathTimer=0;g.say('Your buddy is following. Give them a moment to get around the furniture.')}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const move=(e:PointerEvent)=>{if(document.pointerLockElement===canvas.current||dragging.current)game.current?.look(e.movementX,e.movementY)};const release=()=>{firing.current=false;dragging.current=false};const lock=()=>{const yes=document.pointerLockElement===canvas.current;setLocked(yes);if(!yes&&wasLocked.current&&game.current&&!game.current.won)pause();wasLocked.current=yes};const blur=()=>{keys.current.clear();release();pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointermove',move);window.addEventListener('pointerup',release);window.addEventListener('blur',blur);document.addEventListener('pointerlockchange',lock);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',release);window.removeEventListener('blur',blur);document.removeEventListener('pointerlockchange',lock)}},[]);
 const homeDist=Math.hypot(hud.x-HOME.x,hud.z-HOME.z),buddyDist=Math.hypot(hud.x-hud.buddyX,hud.z-hud.buddyZ),point=(n:number)=>(n+13)/26*100;
 return <main className="shell"><header><div className="brand">ChinChin<span>MIDNIGHT PATROL</span></div><div className="header-tools"><span className="edition">FIRST-PERSON ADVENTURE</span><button className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{soundRef.current=!soundRef.current;setSound(soundRef.current);tone('snack')}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><Dialog open={help} onOpenChange={open=>{setHelp(open);if(open)pause()}}><DialogTrigger className="icon-button" aria-label="Controls and settings"><HelpCircle size={18}/></DialogTrigger><DialogContent className="help-dialog"><DialogHeader><DialogTitle>A tiny first-person heist.</DialogTitle><DialogDescription>Find all six snacks and return to the purple HOME rug with your companion.</DialogDescription></DialogHeader><div className="help-copy"><p><b>W A S D</b> moves. <b>Mouse</b> aims. <b>Left click</b> fires seeds. <b>R</b> reloads, with unlimited spare seeds. <b>Space</b> jumps; <b>Shift</b> sprints.</p><p>Three seed hits put a vacuum bot to sleep. Dodge their dust puffs. The home rug restores courage. If courage runs out, you return home and keep your collected snacks.</p><p>Your other chinchilla follows automatically. <b>Q</b> calls your buddy. Snacks collect when you get close; jump onto crates to reach the high ones.</p><p><b>Esc / P</b> pauses. If mouse capture is unavailable, hold the <b>right mouse button</b> and drag to look, or use the <b>arrow keys</b> to aim.</p><div className="setting"><label htmlFor="quality">Detailed fur and shadows<small>Turn off for smoother performance.</small></label><Switch id="quality" checked={detail} onCheckedChange={v=>{setDetail(v);world.current?.quality(v)}}/></div></div></DialogContent></Dialog></div></header>
 <section className={`stage fps-stage ${started?'is-patrol':''}`} aria-label="First-person chinchilla game"><canvas ref={canvas} tabIndex={0} aria-label="WASD to move, mouse to aim, click to fire, R to reload, Space to jump." onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{if(!game.current||game.current.paused||game.current.won)return;e.preventDefault();canvas.current?.focus();if(e.button===0)firing.current=true;if(e.button===2){dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId)}}}/>
 {!started&&!failure&&<div className="title-overlay fps-title"><span className="kicker">TINY PAWS. NIGHT SHIFT.</span><h1>Take back<br/>snack time.</h1><p>The vacuum bots are on patrol.<br/>Grab your seed blaster and bring the snacks home.</p><div className="choose-pet"><span>PLAY AS</span><button className={white?'chosen':''} aria-pressed={white} onClick={()=>setWhite(true)}><i className="coat coat-0"/>Dora</button><button className={!white?'chosen':''} aria-pressed={!white} onClick={()=>setWhite(false)}><i className="coat coat-1"/>Enzo</button></div><button className="primary" disabled={!ready} onClick={begin}>{ready?'Start patrol':'Preparing the patrol…'}<ChevronRight size={20}/></button><span className="small-note">WASD move · mouse aim · click fire</span><div className="edition-tag">6 SNACKS <i/> 5 VACUUM BOTS <i/> 1 FLUFFY COMPANION</div></div>}
 {started&&!failure&&<><div className="mission-panel"><span className="kicker">{hud.found===6?'GET YOUR BUDDY HOME':'RESCUE THE MIDNIGHT SNACKS'}</span><div><b>{String(hud.found).padStart(2,'0')}</b><span>/ 06 snacks</span><i/>{hud.bots} / 5 bots asleep</div></div><div className="fps-tools"><button className="icon-button" aria-label="Pause game" onClick={pause}><Pause size={17}/></button><button className="icon-button" aria-label="Fullscreen" onClick={()=>{const p=canvas.current?.parentElement;if(p)Promise.resolve(p.requestFullscreen()).catch(()=>game.current?.say('Fullscreen is unavailable here. You can keep playing in this window.'))}}><Maximize size={17}/></button></div><div className={`crosshair ${hud.hit?'hit':''}`} aria-hidden="true"><i/><i/><i/><i/></div>{hud.hurt>0&&<div className="hurt-screen"/>}<div className="vitals"><div className="vital-title"><Heart size={15}/><span>COURAGE</span><b>{hud.health}</b></div><Progress value={hud.health} aria-label="Courage" className="courage-bar"/><Progress value={hud.stamina} aria-label="Sprint stamina" className="stamina-bar"/><span className="buddy-label">{white?'Enzo':'Dora'} is {buddyDist<2.5?'right beside you':`${buddyDist.toFixed(1)}m away`}</span></div><div className="ammo"><span>SEED BLASTER</span><div>{hud.ammo.toString().padStart(2,'0')}<small>/ 12</small></div><p>{hud.reload>0?'Reloading…':'R reload · unlimited reserves'}</p></div><div className="map-panel"><svg viewBox="0 0 100 100" role="img" aria-label="Room map: gold dots are snacks, orange dots are vacuum bots, purple square is home"><rect width="100" height="100" rx="5" fill="#14232ce8"/>{BOXES.map((b,i)=><rect key={i} x={point(b.x-b.w/2)} y={point(b.z-b.d/2)} width={b.w/26*100} height={b.d/26*100} fill="#65717c88"/>)}<rect x={point(HOME.x)-5} y={point(HOME.z)-5} width="10" height="10" rx="2" fill="#987bb2"/>{hud.targets.filter(s=>!s.taken).map((s,i)=><circle key={i} cx={point(s.x)} cy={point(s.z)} r="2.1" fill="#f1ce84"/>)}{hud.enemies.filter(b=>b.hp>0).map((b,i)=><circle key={i} cx={point(b.x)} cy={point(b.z)} r="1.6" fill="#e8925c"/>)}<circle cx={point(hud.buddyX)} cy={point(hud.buddyZ)} r="2" fill={white?'#a3a1ae':'#f5ecdb'} stroke="#fff" strokeWidth=".4"/><g transform={`translate(${point(hud.x)} ${point(hud.z)}) rotate(${-hud.yaw*180/Math.PI})`}><path d="M 0 -3.3 L 2.7 2.2 L 0 1.2 L -2.7 2.2 Z" fill="#cce7e9"/></g></svg><span>HOME · {homeDist<2?'safe zone':`${homeDist.toFixed(1)}m`}</span></div>{hud.message&&<div className="game-toast" role="status">{hud.message}</div>}</>}
 {paused&&!hud.won&&!failure&&<div className="scrim"><div className="pause-card"><span className="kicker">THE NIGHT CAN WAIT</span><h2>Patrol paused.</h2><button className="primary" onClick={resume}>Resume patrol<Play size={18}/></button><button className="text-button" onClick={begin}>Restart patrol</button><button className="text-button" onClick={title}>Back to title</button></div></div>}
 {hud.won&&!failure&&<div className="scrim"><div className="win-card"><Heart size={34} className="heart" fill="currentColor"/><span className="kicker">SNACKS SAFE. BUDDY HOME.</span><h2>Night shift complete.</h2><p>All six snacks rescued with your fluffy partner.<br/>{hud.bots} bots asleep · {hud.accuracy}% seed accuracy</p><button className="primary" onClick={begin}>Another patrol <ChevronRight size={18}/></button><button className="text-button" onClick={title}>Back to title</button></div></div>}
 {failure&&<div className="scrim"><div className="pause-card"><h2>The room needs a moment.</h2><p>{failure}</p><button className="primary" onClick={()=>window.location.reload()}>Reload game<RotateCcw size={18}/></button></div></div>}
 </section>
 <section className="fps-control-strip"><div><kbd>W A S D</kbd> Move <kbd>Space</kbd> Jump <kbd>Shift</kbd> Sprint</div><div><MousePointer2 size={15}/>{started?(locked?'Mouse captured · Esc to pause':'Right-drag or arrow keys to aim'):'Mouse aim · Left click to fire'}{started&&!locked&&!paused&&!hud.won&&<button onClick={capture}>Capture mouse</button>}</div><div><kbd>R</kbd> Reload <kbd>Q</kbd> Call buddy</div></section><footer><div className="original-pair"><img src="/art/the-original-duo.jpg" alt="The original white and grey chinchillas together"/><span>Your two fluffy partners, on midnight patrol.</span></div><span className="footer-note">Desktop + mouse recommended <i>·</i> Playful seed blasters</span></footer></main>
}
