import * as T from 'three';
import {createChinchilla,animateChinchilla} from './chinchilla';
import {Adventure,BLOCKS,type Point} from './arpg-game';
export class IsometricWorld{
 scene=new T.Scene();camera=new T.OrthographicCamera(-12,12,6.75,-6.75,.1,100);renderer:T.WebGLRenderer;heroes=[createChinchilla(true),createChinchilla(false)];decoyModel=createChinchilla(true);seals:T.Mesh[]=[];dynamic=new T.Group();enemies:T.Group[]=[];enemyTargets:T.Object3D[]=[];blocks:T.Object3D[]=[];loot:T.Mesh[]=[];shotPool:T.Mesh[]=[];fxPool:T.Mesh[]=[];rings:T.Mesh[]=[];portal=new T.Group();portalLight=new T.PointLight(0xb8a1fa,3,7);destination:T.Mesh;room=-99;layoutKey='';focus=new T.Vector3(0,0,4);raycaster=new T.Raycaster();groundPlane=new T.Plane(new T.Vector3(0,1,0),0);groundMat:T.MeshStandardMaterial;close=false;
 constructor(public canvas:HTMLCanvasElement){this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.scene.background=new T.Color(0x151b24);this.scene.fog=new T.Fog(0x151b24,35,68);this.scene.add(new T.HemisphereLight(0xb9cde3,0x574439,1.8));const key=new T.DirectionalLight(0xe8d3ad,3.0);key.position.set(-7,18,10);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-18,right:18,top:18,bottom:-18,near:1,far:50});key.shadow.normalBias=.04;this.scene.add(key);const rim=new T.DirectionalLight(0x8bacdb,2.4);rim.position.set(-12,8,-8);this.scene.add(rim);this.groundMat=this.material(0x51585b);this.buildRoom();this.scene.add(this.dynamic);this.heroes.forEach((h,i)=>{this.scene.add(h.root);const ring=new T.Mesh(new T.TorusGeometry(.79,.025,7,48),new T.MeshBasicMaterial({color:i===0?0xf2d293:0xafa9e9,transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;this.scene.add(ring);this.rings.push(ring)});this.destination=new T.Mesh(new T.TorusGeometry(.35,.03,6,32),new T.MeshBasicMaterial({color:0xf0d5a4,transparent:true,opacity:.7}));this.scene.add(this.decoyModel.root);this.decoyModel.root.visible=false;this.decoyModel.root.traverse(obj=>{if(obj instanceof T.Mesh||obj instanceof T.LineSegments){obj.castShadow=false;const mats=Array.isArray(obj.material)?obj.material:[obj.material];for(const mat of mats){mat.transparent=true;mat.opacity=.24;mat.depthWrite=false;if(mat instanceof T.MeshStandardMaterial){mat.color.set(0xa2caca);mat.emissive.set(0x497a77);mat.emissiveIntensity=.6}}}});this.decoyModel.fur.forEach(f=>f.geometry.setDrawRange(0,Math.floor(f.geometry.getAttribute('position').count/32)*4));
 this.destination.rotation.x=Math.PI/2;this.scene.add(this.destination);this.resize()}
 material(color:number,roughness=.9,metalness=0){return new T.MeshStandardMaterial({color,roughness,metalness})}
 box(parent:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,mat:T.Material){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
 ball(parent:T.Object3D,x:number,y:number,z:number,r:number,mat:T.Material){const m=new T.Mesh(new T.SphereGeometry(r,20,14),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}
 buildRoom(){const stone=this.material(0x414c53),edge=this.material(0x746553),wood=this.material(0x6a5140);this.box(this.scene,0,-.20,0,26,.4,26,this.groundMat);for(let x=-12;x<13;x+=2)for(let z=-12;z<13;z+=2){const shade=.94+((x*7+z*11+99)%7)*.012;const m=this.material(new T.Color(0x566167).multiplyScalar(shade).getHex());this.box(this.scene,x,.006,z,1.975,.035,1.975,m)}
 // A cutaway den leaves the two camera-facing walls open.
 this.box(this.scene,-13,2.2,0,.55,4.4,26,stone);this.box(this.scene,0,2.2,-13,26,4.4,.55,stone);for(let p=-12;p<13;p+=3){this.box(this.scene,p,2.3,-12.6,.55,4.6,.6,edge);this.box(this.scene,-12.6,2.3,p,.6,4.6,.55,edge)}

 this.box(this.scene,0,.043,5.8,4.6,.05,6.4,this.material(0x635065));for(const z of [3,8.6])this.box(this.scene,0,.075,z,4.3,.008,.10,this.material(0xaf8c63));
 for(const [x,z]of [[-10,10],[10,10],[-10,-10],[10,-10]]){const l=new T.PointLight(0xffb46d,13,7);l.position.set(x,3.55,z);this.scene.add(l);const brazier=new T.Mesh(new T.CylinderGeometry(.33,.23,.22,16),this.material(0x937545,.4,.55));brazier.position.set(x,3.32,z);this.scene.add(brazier);const ember=this.ball(this.scene,x,3.58,z,.16,new T.MeshBasicMaterial({color:0xffcd8c}));ember.scale.y=1.6;}
 const portalStone=this.material(0x737681);for(const x of [-1.4,1.4])this.box(this.portal,x,1.5,0,.38,3.0,.65,portalStone);this.box(this.portal,0,3.13,0,3.3,.35,.7,portalStone);const glow=new T.Mesh(new T.PlaneGeometry(2.5,2.9),new T.MeshBasicMaterial({color:0xa99ed8,transparent:true,opacity:.2,side:T.DoubleSide}));glow.position.set(0,1.45,0);this.portal.add(glow);this.portal.position.set(0,0,-10.3);this.scene.add(this.portal);this.portalLight.position.set(0,1.3,-9.5);this.scene.add(this.portalLight);
 const petals=new T.InstancedMesh(new T.IcosahedronGeometry(.035,0),this.material(0xb39666),75),dummy=new T.Object3D();for(let i=0;i<75;i++){dummy.position.set(Math.sin(i*17.2)*10,.08,Math.cos(i*8.91)*10);dummy.scale.set(1+(i%3),1,1);dummy.updateMatrix();petals.setMatrixAt(i,dummy.matrix)}this.scene.add(petals);
 }
 clear(){this.disposeObject(this.dynamic);this.dynamic.clear();this.enemies=[];this.loot=[];this.shotPool=[];this.fxPool=[];this.enemyTargets=[];this.seals=[];this.blocks=[]}
 setRoom(g:Adventure|null){const level=g?g.room:-1;const layoutKey=level+':'+(g?.seed??0);if(this.layoutKey===layoutKey)return;this.layoutKey=layoutKey;this.room=level;this.clear();
 for(const b of g?g.floor.blocks:BLOCKS){const group=new T.Group();group.userData.block=true;const stone=this.material(g&&g.room%3===1?0x6e5547:g&&g.room%3===2?0x51465f:0x515d64);this.box(group,b.x,b.h/2,b.z,b.w,b.h,b.d,stone);this.box(group,b.x,b.h+.04,b.z,b.w+.08,.08,b.d+.08,this.material(0x9c8569));this.dynamic.add(group);this.blocks.push(group)}
 this.groundMat.color.set([0x51585b,0x625244,0x464054][Math.max(0,level)%3]);const bronze=this.material(0x998365,.35,.65),shell=this.material(0x53616a,.5,.4);if(g)this.enemies=g.enemies.map(e=>{const root=new T.Group();root.userData.enemyId=e.id;root.userData.alive=true;const body=new T.Mesh(new T.CylinderGeometry(.49,.56,.4,24),shell);body.position.y=.35;body.castShadow=true;root.add(body);this.ball(root,0,.62,0,.36,bronze).scale.y=.65;for(const x of [-.51,.51])this.ball(root,x,.24,0,.18,this.material(0x222b31)).scale.x=.5;this.box(root,0,.52,.46,.57,.10,.08,this.material(0xdc9b63,.4));if(e.type!=='mite'){this.box(root,0,.9,0,.07,.65,.07,bronze);this.ball(root,0,1.23,0,.10,new T.MeshBasicMaterial({color:0xe9ab68}))}if(e.type==='boss'){root.scale.setScalar(1.9);const collar=new T.Mesh(new T.TorusGeometry(.39,.06,8,24),bronze);collar.rotation.x=Math.PI/2;collar.position.y=.82;root.add(collar)}this.dynamic.add(root);this.enemyTargets.push(root);return root});
 if(g)for(const e of g.enemies){const seal=new T.Mesh(new T.TorusGeometry(e.radius+.2,.035,6,36),new T.MeshBasicMaterial({color:0xf4d794,transparent:true,opacity:.8,depthWrite:false}));seal.rotation.x=Math.PI/2;this.dynamic.add(seal);this.seals.push(seal)}
 for(let i=0;i<30;i++){const m=new T.Mesh(new T.IcosahedronGeometry(.16,1),new T.MeshStandardMaterial({color:0xe0c083,roughness:.6,emissive:0x80613a,emissiveIntensity:.4}));m.visible=false;this.dynamic.add(m);this.loot.push(m)}for(let i=0;i<130;i++){const m=new T.Mesh(new T.SphereGeometry(.075,6,4),new T.MeshBasicMaterial({color:0xf2d699}));m.visible=false;this.dynamic.add(m);this.shotPool.push(m)}for(let i=0;i<60;i++){const m=new T.Mesh(new T.TorusGeometry(1,.028,6,40),new T.MeshBasicMaterial({color:0xe8c68b,transparent:true,opacity:.8,depthWrite:false}));m.rotation.x=Math.PI/2;m.visible=false;this.dynamic.add(m);this.fxPool.push(m)}
 this.resize();
 }
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);const width=this.room<0?17:this.close?17:23;this.camera.left=-width/2;this.camera.right=width/2;this.camera.top=width/(w/h)/2;this.camera.bottom=-width/(w/h)/2;this.camera.updateProjectionMatrix()}
 quality(high:boolean){this.renderer.setPixelRatio(high?Math.min(devicePixelRatio,1.6):1);this.renderer.shadowMap.enabled=high;this.heroes.forEach(h=>h.fur.forEach(f=>f.geometry.setDrawRange(0,high?Infinity:Math.floor(f.geometry.getAttribute('position').count/16)*4)));this.resize()}
 project(x:number,y:number,z:number){const p=new T.Vector3(x,y,z).project(this.camera);return {x:(p.x*.5+.5)*100,y:(-.5*p.y+.5)*100,visible:Math.abs(p.x)<1.04&&Math.abs(p.y)<1.04}}
 pick(clientX:number,clientY:number){const r=this.canvas.getBoundingClientRect();this.raycaster.setFromCamera(new T.Vector2((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1),this.camera);const hits=this.raycaster.intersectObjects([...this.enemyTargets.filter(e=>e.userData.alive),...this.blocks],true);if(hits[0]){let obj:T.Object3D|null=hits[0].object;while(obj){if(typeof obj.userData.enemyId==='number')return {x:obj.position.x,z:obj.position.z,enemy:obj.userData.enemyId};if(obj.userData.block)break;obj=obj.parent}}
 const hit=this.raycaster.ray.intersectPlane(this.groundPlane,new T.Vector3());return hit?{x:hit.x,z:hit.z,enemy:-1}:null}
 render(t:number,g:Adventure|null){this.setRoom(g);if(g){const a=g.hero,b=g.heroes[1-g.active],desired=new T.Vector3((a.x+b.x)/2,0,(a.z+b.z)/2);this.focus.lerp(desired,.09);this.camera.position.set(this.focus.x+17,22,this.focus.z+17);this.camera.lookAt(this.focus.x,.4,this.focus.z);
 const aspect=this.canvas.clientWidth/this.canvas.clientHeight,span=Math.max(this.close?17:23,Math.hypot(a.x-b.x,a.z-b.z)*Math.max(1,aspect)+7);this.camera.left=-span/2;this.camera.right=span/2;this.camera.top=span/aspect/2;this.camera.bottom=-span/aspect/2;this.camera.updateProjectionMatrix();
 const obscuring=new Set<T.Object3D>();for(const h of g.heroes){const target=new T.Vector3(h.x,.8,h.z),delta=target.clone().sub(this.camera.position);this.raycaster.set(this.camera.position,delta.clone().normalize());this.raycaster.far=delta.length();for(const hit of this.raycaster.intersectObjects(this.blocks,true)){let obj=hit.object;while(obj.parent&&!obj.userData.block)obj=obj.parent;obscuring.add(obj)}}this.raycaster.far=Infinity;for(const block of this.blocks)block.traverse(obj=>{if(obj instanceof T.Mesh){const mat=obj.material as T.MeshStandardMaterial;mat.transparent=true;mat.opacity=obscuring.has(block)?.28:1;mat.depthWrite=!obscuring.has(block)}});
 this.heroes.forEach((m,i)=>{const h=g.heroes[i];m.root.position.set(h.x,.04,h.z);m.root.scale.setScalar(i===1&&g.transform>0?1.42:1.08);if(i===1)m.root.traverse(obj=>{if(obj instanceof T.Mesh&&obj.material instanceof T.MeshStandardMaterial){obj.material.emissive.set(g.transform>0?0x805727:0x000000);obj.material.emissiveIntensity=g.transform>0?.65:0}});animateChinchilla(m,g.time,h.speed,true,1,g.won);m.root.rotation.y=h.face;if(h.cooldown>.28)m.body.rotation.z=Math.sin(h.cooldown*14)*.07;this.rings[i].position.set(h.x,.065,h.z);this.rings[i].scale.setScalar(i===g.active?1.05:.88);(this.rings[i].material as T.MeshBasicMaterial).opacity=i===g.active?.95:.45});
 this.decoyModel.root.visible=!!g.decoy;if(g.decoy){this.decoyModel.root.position.set(g.decoy.x,.06,g.decoy.z);this.decoyModel.root.scale.setScalar(1.08);animateChinchilla(this.decoyModel,g.time,0,true,1);this.decoyModel.root.rotation.y=g.heroes[0].face}
 this.seals.forEach((m,i)=>{const e=g.enemies[i];m.visible=e.hp>0&&e.stun>0;if(m.visible){m.position.set(e.x,.4+Math.sin(t*4)*.15,e.z);m.rotation.z=t*.7}});
 this.enemies.forEach((m,i)=>{const e=g.enemies[i];m.userData.alive=e.hp>0;m.position.set(e.x,.03,e.z);m.rotation.y=e.face;m.rotation.z=e.hp<=0?.2:0;m.scale.y=e.hp<=0?(e.type==='boss'? .8:.4):(e.type==='boss'?1.9:1);m.visible=true;if(e.flash>0)m.position.y=.12});this.loot.forEach((m,i)=>{const l=g.loot[i];m.visible=!!l;if(l){m.position.set(l.x,.30+Math.sin(t*2+i)*.07,l.z);m.rotation.y=t;(m.material as T.MeshStandardMaterial).color.set(l.heal?0xa6c8a1:0xe0c083)}});this.shotPool.forEach((m,i)=>{const s=g.shots[i];m.visible=!!s;if(s){m.position.set(s.x,.66,s.z);m.scale.setScalar(s.enemy?2:1);(m.material as T.MeshBasicMaterial).color.set(s.enemy?0xe3a481:0xffdc91)}});this.fxPool.forEach((m,i)=>{const e=g.effects[i];m.visible=!!e;if(e){const f=e.age/e.ttl;m.position.set(e.x,.1,e.z);m.scale.setScalar(e.radius*(.25+f));const mat=m.material as T.MeshBasicMaterial;mat.opacity=(1-f)*.85;mat.color.set(e.kind==='seal'?0xf4d794:e.kind==='puff'?0xa2caca:e.kind==='burst'?0xd4b5f3:e.kind==='heal'?0xabd4ad:e.kind==='hit'&&!e.value?0xe99782:0xebd098)}});
 this.destination.visible=!!g.target&&!g.cleared;if(g.target){this.destination.position.set(g.target.x,.07,g.target.z);this.destination.scale.setScalar(.9+Math.sin(t*4)*.1)}this.portalLight.intensity=g.cleared?15:1.4;const veil=this.portal.children[3] as T.Mesh;(veil.material as T.MeshBasicMaterial).opacity=g.cleared?.55:.10;
 }else{this.decoyModel.root.visible=false;this.heroes[1].root.traverse(obj=>{if(obj instanceof T.Mesh&&obj.material instanceof T.MeshStandardMaterial)obj.material.emissiveIntensity=0});this.focus.set(0,0,5);this.camera.position.set(14,16,19);this.camera.lookAt(0,.7,5);this.heroes.forEach((m,i)=>{m.root.position.set(1.5+i*2.2,.05,4+i*.4);m.root.scale.setScalar(1.7);animateChinchilla(m,t,0,true,i===0?1:-1);this.rings[i].visible=false});this.destination.visible=false;this.portalLight.intensity=5}
 if(g)this.rings.forEach(r=>r.visible=true);this.renderer.render(this.scene,this.camera)}
 disposeObject(o:T.Object3D){const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>();o.traverse(m=>{if(m instanceof T.Mesh||m instanceof T.Line||m instanceof T.LineSegments){gs.add(m.geometry);for(const mat of Array.isArray(m.material)?m.material:[m.material])ms.add(mat)}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose())}
 dispose(){this.disposeObject(this.scene);this.renderer.dispose()}
}
