import {generateFloor,type Block,type Floor} from './dungeon.js';
import {SKILLS,STANCES,type Stance} from './skills.js';
export type Point={x:number;z:number};
export const BLOCKS=[{x:-5,z:0,w:1.6,d:1.6,h:3.2},{x:5,z:0,w:1.6,d:1.6,h:3.2},{x:0,z:-3,w:3.4,d:1.8,h:1.15},{x:-8,z:-6,w:2,d:2,h:1.3},{x:8,z:5,w:2,d:2,h:1.2}];
export const CHAMBERS=[{name:'The Forgotten Den',subtitle:'Something stirs beneath the floorboards.'},{name:'The Dustworks',subtitle:'The machines are waking.'},{name:'The Vacuum Vault',subtitle:'The Great Sweeper guards the last passage.'}];
export function blocked(x:number,z:number,r=.42,blocks:Block[]=BLOCKS){return Math.abs(x)>11.6||Math.abs(z)>11.6||blocks.some(b=>Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r)}
export function pathfind(from:Point,to:Point,blocks:Block[]=BLOCKS,r=.53):Point[]{const key=(x:number,z:number)=>x+','+z,sx=Math.round(from.x),sz=Math.round(from.z),gx=Math.round(to.x),gz=Math.round(to.z);const open=[{x:sx,z:sz,g:0,f:0}],came=new Map<string,string>(),cost=new Map<string,number>([[key(sx,sz),0]]);let best=key(sx,sz),distance=Infinity;const closed=new Set<string>();for(let loop=0;open.length&&loop<5000;loop++){open.sort((a,b)=>a.f-b.f);const p=open.shift()!,pk=key(p.x,p.z),d=Math.hypot(p.x-gx,p.z-gz);if(closed.has(pk))continue;closed.add(pk);if(d<distance){distance=d;best=pk}if(d<1.1)break;for(const[dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const x=p.x+dx,z=p.z+dz;if(blocked(x,z,r,blocks)||blocked(p.x+dx,p.z,r,blocks)||blocked(p.x,p.z+dz,r,blocks))continue;const k=key(x,z),g=p.g+Math.hypot(dx,dz);if(g>=(cost.get(k)??Infinity))continue;cost.set(k,g);came.set(k,pk);open.push({x,z,g,f:g+Math.hypot(x-gx,z-gz)})}}const out:Point[]=[];for(let k=best;k!==key(sx,sz)&&came.has(k);k=came.get(k)!){const[x,z]=k.split(',').map(Number);out.unshift({x,z})}return out}
export type Hero=Point&{face:number;speed:number;cooldown:number;special:number;dodge:number;path:Point[];pathTime:number};
export type Enemy=Point&{id:number;type:'mite'|'sweeper'|'boss';hp:number;maxHp:number;radius:number;cooldown:number;stun:number;flash:number;face:number;path:Point[];pathTime:number};
export type Shot=Point&{vx:number;vz:number;life:number;damage:number;enemy:boolean;stun?:number};
export type Effect=Point&{id:number;kind:'hit'|'burst'|'slash'|'dodge'|'heal'|'seal'|'puff';age:number;ttl:number;radius:number;value?:number};
export type Input={forward:number;strafe:number};
export class Adventure{
 heroes:Hero[]=[];enemies:Enemy[]=[];shots:Shot[]=[];effects:Effect[]=[];loot:(Point&{id:number;heal:boolean;value:number})[]=[];active=0;room=0;playing=false;paused=false;won=false;cleared=false;reward=false;hp=150;maxHp=150;bond=45;stamina=100;treats=0;roomTreats=0;time=0;hurt=0;target:Point|null=null;enemyTarget=-1;message='';messageFor=0;events:string[]=[];serial=0;ranged=1;melee=1;boosts:string[]=[];revivals=0;
 stance:Stance='smash';decoy:(Point&{life:number;hp:number;maxHp:number})|null=null;decoyCooldown=0;transform=0;transformCooldown=0;floorDepth=-1;seed:number;floor!:Floor;level=1;xp=0;skillPoints=1;skills:Record<string,number>={};xpClaimed=new Set<number>();
 constructor(seed=Math.floor(Math.random()*4294967296)){this.seed=seed>>>0;this.setup(0)}
 get xpNext(){return 70+(this.level-1)*35}
 rank(id:string){return this.skills[id]||0}
 get burstCost(){return 50}
 get meleeRange(){return 1.55+(this.stance==='thrust'?.6*this.rank('thrust'):0)}
 get meleePower(){return (this.stance==='smash'?1+.2*this.rank('smash'):1)*(this.transform>0?1.25:1)}
 equipStance(id:Stance){if(!this.playing||!STANCES.some(s=>s.id===id)||!this.rank(id))return false;this.stance=id;return true}
 immobilize(e:Enemy,seconds:number){e.stun=Math.max(e.stun,seconds*(e.type==='boss'?.5:1));this.effect('seal',e,.8)}
 breakDecoy(){const d=this.decoy;if(!d)return;this.decoy=null;this.effect('puff',d,3);if(this.rank('echo'))for(const e of this.living)if(Math.hypot(e.x-d.x,e.z-d.z)<3+e.radius&&this.visible(d,e))this.damage(e,25*this.rank('echo')*this.power)}
 get power(){return 1+(this.level-1)*.07}
 skillReason(id:string){const s=SKILLS.find(s=>s.id===id);if(!s)return 'Unknown skill';if(this.rank(id)>=s.max)return 'Mastered';if(this.level<s.level)return 'Requires level '+s.level;if(s.parent&&!this.rank(s.parent))return 'Requires '+SKILLS.find(n=>n.id===s.parent)!.name;if(this.skillPoints<1)return 'Earn a skill point by leveling up';return ''}
 learn(id:string){if(!this.playing||this.skillReason(id))return false;this.skills[id]=this.rank(id)+1;this.skillPoints--;this.events.push('boon');return true}
 gainXp(amount:number){this.xp+=amount;while(this.xp>=this.xpNext){this.xp-=this.xpNext;this.level++;this.skillPoints++;this.maxHp+=12;this.hp=this.maxHp;this.bond=Math.min(100,this.bond+20);this.effect('burst',this.hero,3);this.say('Level '+this.level+'! +1 skill point. Press K to shape your build.');this.events.push('level')}}
 takeDamage(amount:number){this.hp-=amount*(1-(this.active===1?(this.stance==='pillar'?.1*this.rank('pillar'):0)+(this.transform>0?.2+.05*this.rank('ironhide'):0):0))}

 get hero(){return this.heroes[this.active]} get living(){return this.enemies.filter(e=>e.hp>0)}
 setup(room:number){this.decoy=null;this.decoyCooldown=0;this.transform=0;this.transformCooldown=0;this.room=room;this.heroes=[-1,1].map(x=>({x,z:8,face:Math.PI/2,speed:0,cooldown:0,special:0,dodge:0,path:[],pathTime:0}));this.enemies=[];if(!this.floor||this.room!==this.floorDepth){this.xpClaimed.clear()}this.floorDepth=room;this.floor=generateFloor(this.seed,room);const spawns=this.floor.spawns.map(e=>[e.x,e.z,e.type]);spawns.forEach(([x,z,type],i)=>{const kind=type===2?'boss':type===1?'sweeper':'mite',hp=type===2?350+room*65:type===1?65+room*16:38+room*11;this.enemies.push({id:i,x,z,type:kind,hp,maxHp:hp,radius:type===2?1.05:.53,cooldown:1+i*.3,stun:0,flash:0,face:0,path:[],pathTime:0})});this.target=null;this.enemyTarget=-1;this.shots=[];this.effects=[];this.loot=[];this.cleared=false;this.reward=false;this.roomTreats=this.treats;this.hp=Math.min(this.maxHp,this.hp+40);this.stamina=100;this.say('Floor '+(room+1)+' · '+this.floor.name+((room+1)%3===0?' · A guardian awaits.':''))}
 say(s:string){this.message=s;this.messageFor=4}
 effect(kind:Effect['kind'],p:Point,radius:number,value?:number){this.effects.push({...p,id:this.serial++,kind,age:0,ttl:kind==='burst'? .7:kind==='hit'? .85:.38,radius,value})}
 visible(a:Point,b:Point){const d=Math.hypot(a.x-b.x,a.z-b.z);for(let s=.15;s<d;s+=.25){const f=s/d,x=a.x+(b.x-a.x)*f,z=a.z+(b.z-a.z)*f;if(this.floor.blocks.some(o=>Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2))return false}return true}
 move(body:Point,dx:number,dz:number,r=.42){if(!blocked(body.x+dx,body.z,r,this.floor.blocks))body.x+=dx;if(!blocked(body.x,body.z+dz,r,this.floor.blocks))body.z+=dz}
 steer(h:Hero,goal:Point,dt:number,speed:number){if(h.pathTime<=0){h.path=pathfind(h,goal,this.floor.blocks);h.pathTime=.55}let p=h.path[0];if(p&&Math.hypot(p.x-h.x,p.z-h.z)<.25){h.path.shift();p=h.path[0]}if(!p&&this.visible(h,goal)&&!blocked(goal.x,goal.z,.42,this.floor.blocks))p=goal;if(p){const dx=p.x-h.x,dz=p.z-h.z,d=Math.hypot(dx,dz);if(d>.1){this.move(h,dx/d*Math.min(d,speed*dt),dz/d*Math.min(d,speed*dt));h.face=Math.atan2(-dz,dx);h.speed=speed}}}
 command(point:Point,enemy=-1){if(!this.playing||this.paused||this.won||this.reward)return;this.target={x:Math.max(-11,Math.min(11,point.x)),z:Math.max(-11,Math.min(11,point.z))};this.enemyTarget=enemy;this.hero.pathTime=0;this.hero.path=[];}
 swap(index=1-this.active){if(!this.playing||this.paused||this.won||this.reward)return;this.active=index;this.target=null;this.enemyTarget=-1;this.heroes.forEach(h=>{h.path=[];h.pathTime=0});this.events.push('switch')}
 damage(e:Enemy,amount:number){if(e.hp<=0)return;const dmg=Math.round(amount*(e.stun>0?1+.2*this.rank('brittle'):1));e.hp=Math.max(0,e.hp-dmg);e.flash=.13;this.bond=Math.min(100,this.bond+5);this.effect('hit',e,.35,dmg);this.events.push('hit');if(e.hp===0){if(!this.xpClaimed.has(e.id)){this.xpClaimed.add(e.id);this.gainXp(e.type==='boss'?120:e.type==='sweeper'?28:18)}this.loot.push({x:e.x,z:e.z,id:this.serial++,heal:e.id%3===0,value:e.type==='boss'?20:3+this.room});this.events.push('loot')}}
 attack(index:number,e:Enemy,power=1){const h=this.heroes[index];if(h.cooldown>0)return;h.face=Math.atan2(-(e.z-h.z),e.x-h.x);const support=index===this.active?1:.7;if(index===0){const dx=e.x-h.x,dz=e.z-h.z,d=Math.hypot(dx,dz)||1;this.shots.push({x:h.x,z:h.z,vx:dx/d*19,vz:dz/d*19,life:1.3,damage:15*this.ranged*this.power*power*support,enemy:false});h.cooldown=.39;this.events.push('seed')}else{const damage=27*this.melee*this.power*this.meleePower*power*support;this.damage(e,damage);if(this.stance==='pillar'&&this.rank('pillar'))for(const other of this.living)if(other!==e&&Math.hypot(other.x-h.x,other.z-h.z)<2.3&&this.visible(h,other))this.damage(other,damage*.25*this.rank('pillar'));this.effect('slash',h,1.65);h.cooldown=this.stance==='smash'&&this.rank('smash')?.75:.59;this.events.push('slash')}}
 special(point?:Point){if(!this.playing||this.paused||this.won||this.reward)return;const h=this.hero;if(h.special>0){this.say('That ability is recharging.');return}h.special=3.6;if(this.active===0){const nearest=this.living.slice().sort((a,b)=>Math.hypot(a.x-h.x,a.z-h.z)-Math.hypot(b.x-h.x,b.z-h.z))[0];const target=point||nearest||{x:h.x+Math.cos(h.face)*5,z:h.z-Math.sin(h.face)*5};const angle=Math.atan2(target.z-h.z,target.x-h.x);h.face=-angle;for(const offset of [-.22,-.11,0,.11,.22])this.shots.push({x:h.x,z:h.z,vx:Math.cos(angle+offset)*20,vz:Math.sin(angle+offset)*20,life:.8,damage:20*this.ranged*this.power,enemy:false,stun:.7*this.rank('hush')});if(this.rank('sanctuary'))for(const e of this.living)if(Math.hypot(e.x-h.x,e.z-h.z)<4+e.radius&&this.visible(h,e))this.immobilize(e,this.rank('sanctuary'));
 if(this.rank('decoy')&&this.decoyCooldown<=0){const p={x:h.x,z:h.z};for(const angle of [h.face+Math.PI/2,h.face-Math.PI/2,h.face+Math.PI]){const candidate={x:h.x+Math.cos(angle)*1.3,z:h.z-Math.sin(angle)*1.3};if(!blocked(candidate.x,candidate.z,.5,this.floor.blocks)&&this.visible(h,candidate)){Object.assign(p,candidate);break}}const hp=35+15*this.rank('lingering');this.decoy={...p,hp,maxHp:hp,life:4+2*this.rank('lingering')};this.decoyCooldown=10;this.effect('puff',p,1.4);this.say('Dust Double draws their attention.')}
 this.events.push('seed')}else{if(this.rank('stonefur')&&this.transformCooldown<=0){this.transform=2+2*this.rank('stonefur');this.transformCooldown=12;this.effect('burst',h,2);this.say('Stonefur Spirit awakens!')}for(const e of this.living)if(Math.hypot(e.x-h.x,e.z-h.z)<3.1+e.radius){this.damage(e,43*this.melee*this.power*this.meleePower);e.stun=.7}this.effect('slash',h,3.1);this.events.push('slash')}}
 burst(){if(!this.playing||this.paused||this.won||this.reward)return;if(this.bond<this.burstCost){this.say('Build '+this.burstCost+' bond by landing attacks.');return}this.bond-=this.burstCost;for(const h of this.heroes)this.effect('burst',h,4.2);for(const e of this.living)if(this.heroes.some(h=>Math.hypot(h.x-e.x,h.z-e.z)<4.2+e.radius)){this.damage(e,62*this.power);e.stun=1.5}this.events.push('burst');this.say('Better together!')}
 dodge(){if(!this.playing||this.paused||this.won||this.reward)return;const h=this.hero;if(h.dodge>0||this.stamina<30)return;this.stamina-=30;h.dodge=1.4;this.hurt=.4;for(let i=0;i<16;i++)this.move(h,Math.cos(h.face)*.18,-Math.sin(h.face)*.18);this.target=null;this.effect('dodge',h,1.1);this.events.push('dodge')}
 keyboardAttack(){const h=this.hero,e=this.living.slice().sort((a,b)=>Math.hypot(a.x-h.x,a.z-h.z)-Math.hypot(b.x-h.x,b.z-h.z))[0];if(e)this.command(e,e.id)}
 choose(boon:'ranged'|'melee'|'heart'){if(!this.reward)return;if(boon==='ranged'){this.ranged*=1.25;this.boosts.push('Sharper seeds')}if(boon==='melee'){this.melee*=1.25;this.boosts.push('Stronger paws')}if(boon==='heart'){this.maxHp+=35;this.boosts.push('Braver hearts')}this.hp=this.maxHp;this.reward=false;this.say('The passage is open. Lead both friends to the glowing arch and press E.');this.events.push('boon')}
 enter(){if(!this.playing||this.paused||!this.cleared||this.reward||this.won)return;if(Math.hypot(this.hero.x,this.hero.z+9.8)>2.6){this.command({x:0,z:-9.8});this.say('Walk to the glowing arch, then press E.');return}this.treats+=this.loot.reduce((a,l)=>a+l.value,0);this.setup(this.room+1);this.events.push('enter')}
 step(dt:number,input:Input={forward:0,strafe:0}){if(!this.playing||this.paused||this.won||this.reward)return;dt=Math.min(dt,1/30);this.time+=dt;this.hurt=Math.max(0,this.hurt-dt);this.messageFor=Math.max(0,this.messageFor-dt);this.stamina=Math.min(100,this.stamina+21*dt);this.effects.forEach(e=>e.age+=dt);this.effects=this.effects.filter(e=>e.age<e.ttl);const leader=this.hero;
 this.decoyCooldown=Math.max(0,this.decoyCooldown-dt);this.transformCooldown=Math.max(0,this.transformCooldown-dt);if(this.transform>0){this.transform=Math.max(0,this.transform-dt);if(this.transform===0&&this.rank('return')){this.hp=Math.min(this.maxHp,this.hp+15*this.rank('return'));this.effect('heal',this.heroes[1],1.5)}}if(this.decoy){this.decoy.life-=dt;if(this.decoy.life<=0||this.decoy.hp<=0)this.breakDecoy()}

 for(let i=0;i<2;i++){const h=this.heroes[i];h.cooldown=Math.max(0,h.cooldown-dt);h.special=Math.max(0,h.special-dt);h.dodge=Math.max(0,h.dodge-dt);h.pathTime-=dt;h.speed=0;const controlled=i===this.active,moving=controlled&&(input.forward||input.strafe);if(moving){this.target=null;this.enemyTarget=-1;const n=Math.max(1,Math.hypot(input.forward,input.strafe)),dx=(input.strafe-input.forward)*.7071/n,dz=(-input.strafe-input.forward)*.7071/n;this.move(h,dx*4.5*dt,dz*4.5*dt);h.face=Math.atan2(-dz,dx);h.speed=4.5;continue}
 let enemy=controlled?this.enemies.find(e=>e.id===this.enemyTarget&&e.hp>0):this.living.filter(e=>Math.hypot(e.x-leader.x,e.z-leader.z)<6).sort((a,b)=>Math.hypot(a.x-h.x,a.z-h.z)-Math.hypot(b.x-h.x,b.z-h.z))[0];if(!controlled&&Math.hypot(h.x-leader.x,h.z-leader.z)>5.5)enemy=undefined;
 if(enemy){const range=i===0?6.9:this.meleeRange+enemy.radius,d=Math.hypot(h.x-enemy.x,h.z-enemy.z);if(d<=range&&this.visible(h,enemy))this.attack(i,enemy);else this.steer(h,enemy,dt,controlled?4.5:5.5)}else if(controlled&&this.target){if(Math.hypot(h.x-this.target.x,h.z-this.target.z)<.25){this.target=null;this.enemyTarget=-1}else this.steer(h,this.target,dt,4.5)}else if(!controlled&&Math.hypot(h.x-leader.x,h.z-leader.z)>1.8)this.steer(h,leader,dt,5.5);
 }
 for(const e of this.living){e.flash=Math.max(0,e.flash-dt);e.stun=Math.max(0,e.stun-dt);e.cooldown-=dt;e.pathTime-=dt;if(e.stun>0)continue;const lure=this.decoy&&Math.hypot(this.decoy.x-e.x,this.decoy.z-e.z)<7&&this.visible(e,this.decoy)?this.decoy:null;const h=lure||this.heroes.slice().sort((a,b)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(b.x-e.x,b.z-e.z))[0],d=Math.hypot(h.x-e.x,h.z-e.z);e.face=Math.atan2(h.x-e.x,h.z-e.z);if(d>10.5)continue;const ranged=e.type==='sweeper'||e.type==='boss',attackRange=ranged?6:1.4+e.radius;if(d>attackRange||!this.visible(e,h)){if(e.pathTime<=0){e.path=pathfind(e,h,this.floor.blocks,Math.max(.53,e.radius*.8));e.pathTime=.9}const n=e.path[0];if(n){const dx=n.x-e.x,dz=n.z-e.z,dist=Math.hypot(dx,dz);if(dist<.25)e.path.shift();else this.move(e,dx/dist*dt*(e.type==='mite'?1.95:1.2),dz/dist*dt*(e.type==='mite'?1.95:1.2),e.radius*.8)}}else if(e.cooldown<=0){e.cooldown=e.type==='boss'?1.65:ranged?2.2:1.15;if(ranged){const a=Math.atan2(h.z-e.z,h.x-e.x),spread=e.type==='boss'?[-.28,-.14,0,.14,.28]:[0];for(const da of spread)this.shots.push({x:e.x,z:e.z,vx:Math.cos(a+da)*5.6,vz:Math.sin(a+da)*5.6,life:2.5,damage:e.type==='boss'?15:10,enemy:true});this.events.push('bot')}else if(lure){lure.hp-=8+this.room*2;if(lure.hp<=0)this.breakDecoy()}else if(this.hurt===0){this.takeDamage(8+this.room*2);this.hurt=.35;this.effect('hit',h,.5);this.events.push('hurt')}}}
 for(const s of this.shots){s.life-=dt;const steps=Math.max(1,Math.ceil(Math.hypot(s.vx,s.vz)*dt/.14));for(let i=0;i<steps&&s.life>0;i++){s.x+=s.vx*dt/steps;s.z+=s.vz*dt/steps;if(blocked(s.x,s.z,.04,this.floor.blocks)){s.life=0;break}if(s.enemy){if(this.decoy&&Math.hypot(s.x-this.decoy.x,s.z-this.decoy.z)<.65){this.decoy.hp-=s.damage;s.life=0;if(this.decoy.hp<=0)this.breakDecoy();break}for(const h of this.heroes)if(Math.hypot(s.x-h.x,s.z-h.z)<.58){s.life=0;if(this.hurt===0){this.takeDamage(s.damage);this.hurt=.3;this.effect('hit',h,.5);this.events.push('hurt')}break}}else for(const e of this.living)if(Math.hypot(s.x-e.x,s.z-e.z)<e.radius+.16){this.damage(e,s.damage);if(s.stun)this.immobilize(e,s.stun);s.life=0;break}}}this.shots=this.shots.filter(s=>s.life>0);
 this.loot=this.loot.filter(l=>{if(this.heroes.some(h=>Math.hypot(h.x-l.x,h.z-l.z)<1.2)){this.treats+=l.value;if(l.heal){this.hp=Math.min(this.maxHp,this.hp+20);this.effect('heal',leader,1.0)}this.events.push('pickup');return false}return true});
 if(this.hp<=0){this.revivals++;this.treats=this.roomTreats;this.hp=this.maxHp;this.setup(this.room);this.say('Back on your paws. The room has reset—your earlier upgrades are safe.');this.events.push('rescue')}
 if(!this.cleared&&this.living.length===0){this.cleared=true;this.reward=true;this.events.push('clear')}
 }
}
