import * as T from 'three';
import {createChinchilla,poseChinchillaPaws} from './chinchilla';
import {EscapeGame,BLOCKS,HIDES,PLATFORMS,ROUTES,VISION_RANGE,VISION_HALF_ANGLE,DECOY_DURATION} from './escape-game';
export class EscapeScene{
 scene=new T.Scene();camera=new T.PerspectiveCamera(48,1,.1,150);renderer:T.WebGLRenderer;cage=new T.Group();room=new T.Group();heroes=[createChinchilla(false),createChinchilla(true)];guards:T.Group[]=[];cones:T.Mesh[]=[];marker:T.Mesh;dust:T.Mesh;door=new T.Group();phase='';yaw=.63;distance=17;elevation=.56;focus=new T.Vector3(0,1.3,0);walls:{mesh:T.Mesh;side:string}[]=[];woodMap:T.CanvasTexture;floorShadows:T.Mesh[]=[];clipModel=new T.Group();disguise=new T.Group();guardSignals:T.Mesh[]=[];stunCloud:T.Mesh;tunnelParts:T.Mesh[]=[];looseStick=new T.Group();shelfHints:T.Mesh[]=[];leaderRing:T.Mesh;fluff:T.Mesh;occluders:T.Mesh[]=[];ray=new T.Raycaster();
 constructor(public canvas:HTMLCanvasElement){this.renderer=new T.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
 const grain=document.createElement('canvas');grain.width=256;grain.height=512;const brush=grain.getContext('2d')!;brush.fillStyle='#d7be95';brush.fillRect(0,0,256,512);for(let i=0;i<170;i++){brush.strokeStyle=i%3?'#90745425':'#fff1c827';brush.lineWidth=i%5===0?2:1;brush.beginPath();for(let y=0;y<=512;y+=12){const x=i*1.53+Math.sin(y*.015+i)*2.8; if(y===0)brush.moveTo(x,y);else brush.lineTo(x,y)}brush.stroke()}this.woodMap=new T.CanvasTexture(grain);this.woodMap.colorSpace=T.SRGBColorSpace;this.woodMap.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());this.woodMap.wrapS=this.woodMap.wrapT=T.RepeatWrapping;this.scene.background=new T.Color('#17212b');this.scene.add(new T.HemisphereLight(0xa5bbd1,0x514136,2.2));const light=new T.DirectionalLight(0xffd5a0,2.7);light.position.set(-4,15,7);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:.5,far:50});light.shadow.bias=-.0005;light.shadow.normalBias=.025;this.scene.add(light);this.scene.add(this.cage,this.room);
 const wood=0xb09670,metal=0x9eabb2;this.box(this.cage,0,-.18,0,10,.35,8,wood);
 this.walls.push({mesh:this.box(this.cage,0,2,-4,10,4.4,.16,wood),side:'back'});for(const x of [-5,5])this.walls.push({mesh:this.box(this.cage,x,2,0,.16,4.4,8,wood),side:x<0?'left':'right'});
 const rounded=(w:number,d:number,depth:number)=>{const r=.18,a=-w/2,b=-d/2,shape=new T.Shape();shape.moveTo(a+r,b);shape.lineTo(a+w-r,b);shape.quadraticCurveTo(a+w,b,a+w,b+r);shape.lineTo(a+w,b+d-r);shape.quadraticCurveTo(a+w,b+d,a+w-r,b+d);shape.lineTo(a+r,b+d);shape.quadraticCurveTo(a,b+d,a,b+d-r);shape.lineTo(a,b+r);shape.quadraticCurveTo(a,b,a+r,b);return new T.ExtrudeGeometry(shape,{depth,bevelEnabled:false,curveSegments:6})};
 for(const p of PLATFORMS){const rim=new T.Mesh(rounded(p.w,p.d,.10),new T.MeshStandardMaterial({color:0xaeb5b9,metalness:.7,roughness:.28}));rim.rotation.x=-Math.PI/2;rim.position.set(p.x,p.y-.13,p.z);rim.userData.fadeGroup=p.id;rim.castShadow=true;rim.receiveShadow=true;this.cage.add(rim);const top=new T.Mesh(rounded(p.w-.06,p.d-.06,.025),new T.MeshStandardMaterial({color:0xd1bc96,map:this.woodMap,roughness:.8}));top.rotation.x=-Math.PI/2;top.position.set(p.x,p.y-.025,p.z);top.userData.fadeGroup=p.id;top.receiveShadow=true;this.cage.add(top);for(const dx of [-p.w*.32,p.w*.32]){const screw=new T.Mesh(new T.CylinderGeometry(.045,.045,.025,8),new T.MeshStandardMaterial({color:0x40464b,metalness:.6}));screw.userData.fadeGroup=p.id;screw.position.set(p.x+dx,p.y+.014,p.z-p.d*.33);this.cage.add(screw)}}
 // Front frame and mesh echo the photographed silver wire door.
 for(const x of [-5,5])this.box(this.cage,x,2,4,.16,4.4,.16,metal);for(const y of [0,4.2])this.box(this.cage,0,y,4,10,.14,.16,metal);
 const wire=new T.LineBasicMaterial({color:0xbbc9d2,transparent:true,opacity:.23});const pts:T.Vector3[]=[];for(let x=-4.8;x<5;x+=.55)pts.push(new T.Vector3(x,0,4),new T.Vector3(x,4.2,4));for(let y=.3;y<4.2;y+=.45)pts.push(new T.Vector3(-5,y,4),new T.Vector3(5,y,4));this.door.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(pts),wire));this.door.children.forEach(o=>o.position.x+=5);this.door.position.x=-5;this.cage.add(this.door);this.box(this.cage,0,.8,3.9,.35,.55,.22,0xd1b979);
 const tunnel=new T.Mesh(new T.CylinderGeometry(.75,.75,2.5,24,1,true),new T.MeshStandardMaterial({color:0x137bbc,metalness:.65,roughness:.3,side:T.DoubleSide}));tunnel.rotation.z=Math.PI/2;tunnel.position.set(-3,1.4,2.7);this.cage.add(tunnel);this.tunnelParts.push(tunnel);for(const x of [-4.25,-1.75]){const ring=new T.Mesh(new T.TorusGeometry(.75,.06,6,24),new T.MeshStandardMaterial({color:0x82b3ce,metalness:.6}));ring.rotation.y=Math.PI/2;ring.position.set(x,1.4,2.7);this.cage.add(ring);this.tunnelParts.push(ring)}
 this.box(this.looseStick,0,0,0,.65,.07,.09,0x967144,.35);this.looseStick.position.set(-3,.72,1);this.cage.add(this.looseStick);
 // The new interior photo shows a pink hay feeder, with an open top and metal retaining bars.
 for(const x of [2.25,3.75])this.box(this.cage,x,1.95,2.15,.1,1.25,1,0xd491aa);this.box(this.cage,3,1.4,2.15,1.6,.1,1,0xc689a0);this.box(this.cage,3,1.95,2.65,1.6,1.25,.1,0xe0a4b9);for(const x of [2.45,2.8,3.2,3.55])this.box(this.cage,x,1.9,1.7,.025,1,.025,metal);for(let i=0;i<24;i++)this.box(this.cage,2.4+i%6*.22,1.55+Math.floor(i/6)*.05,1.9+(i%4)*.1,.3,.025,.035,0x9f9868,i*.7);
 const clipRing=new T.Mesh(new T.TorusGeometry(.13,.028,6,16,Math.PI*1.7),new T.MeshStandardMaterial({color:0xd9e1e4,metalness:.8,roughness:.22}));clipRing.rotation.x=Math.PI/2;this.clipModel.add(clipRing);this.clipModel.position.set(-.6,2.81,-3);this.cage.add(this.clipModel);for(const x of [-.96,-.24])this.box(this.cage,x,2.99,-3.15,.08,.48,.45,wood);this.box(this.cage,-.6,3.23,-3.15,.8,.07,.45,wood);
 const bottle=new T.Mesh(new T.CylinderGeometry(.35,.35,2,18),new T.MeshStandardMaterial({color:0xc6d4d5,transparent:true,opacity:.48,roughness:.2}));bottle.position.set(4.3,1.9,3.5);this.cage.add(bottle);this.box(this.cage,4.3,3,3.5,.8,.28,.8,0x269dc9);this.box(this.cage,4.3,.75,3.3,.13,.6,.13,metal);
 for(const x of [-1.6,1.1]){this.box(this.cage,x,3.1,3.5,1.8,.85,.5,0xb7bbb9);for(const dx of [-.55,.55])this.box(this.cage,x+dx,2.8,3.82,.18,.18,.14,metal)}
 this.box(this.cage,1.7,.08,-.1,2.4,.18,1.6,0xb4b8a8);for(const x of [.5,2.9])this.box(this.cage,x,.27,-.1,.08,.5,1.6,0xd6d9c7);for(const z of [-.9,.7])this.box(this.cage,1.7,.27,z,2.4,.5,.08,0xd6d9c7);for(let i=0;i<40;i++)this.box(this.cage,.7+(i%8)*.28,.21,-.65+Math.floor(i/8)*.25,.3,.02,.035,0xb6aa76,i*.6);
 for(let i=0;i<12;i++){const a=i/11*Math.PI,log=new T.Mesh(new T.CylinderGeometry(.1,.1,1.4,8),new T.MeshStandardMaterial({color:i%2?0x977c54:0x776247,map:this.woodMap}));log.rotation.x=Math.PI/2;log.position.set(-.7+Math.cos(a)*.65,Math.sin(a)*.7+.1,.3);log.castShadow=true;this.cage.add(log)}
 for(const radius of [.2,.34,.48]){const fan=new T.Mesh(new T.TorusGeometry(radius,.022,5,24),new T.MeshStandardMaterial({color:metal,metalness:.7,roughness:.3}));fan.rotation.y=Math.PI/2;fan.position.set(4.85,1,-1.8);this.cage.add(fan)}
 // Adjacent wooden cabinet and translucent playpen panels from the side views.
 this.box(this.cage,-6.2,.75,0,2,1.5,4,0xb09670);this.box(this.cage,-6.2,2,-1,2,1,2,0xb09670);const glass=this.box(this.cage,-6.2,2,.03,1.8,.85,.05,0xaebac1);(glass.material as T.MeshStandardMaterial).transparent=true;(glass.material as T.MeshStandardMaterial).opacity=.22;
 const pen=this.box(this.cage,5.8,1.2,1.5,.045,2.4,5.5,0xc9d2cc);(pen.material as T.MeshStandardMaterial).transparent=true;(pen.material as T.MeshStandardMaterial).opacity=.18;
 // Wooden room, shelving, covered hiding places, and a green exit.
 this.box(this.room,0,-.2,0,25,.3,19,0x795337);for(let x=-12;x<12;x+=1.5)for(let z=-9;z<9;z+=1.5)this.box(this.room,x+.7,-.03,z+.7,1.46,.04,1.46,(Math.round((x+z)*2)%3)?0x8b603f:0x9b6f47);
 this.box(this.room,0,1.6,-9,25,3.5,.2,0x766b61);this.box(this.room,-12,1.6,0,.2,3.5,18,0x766b61);
 for(const b of BLOCKS){this.box(this.room,b.x,1,b.z,b.w,2,b.d,0x62594e);for(const y of [.3,1.2])this.box(this.room,b.x,y,b.z+b.d/2+.02,b.w-.2,.08,.04,0xa9987a)}
 for(const h of HIDES){const top=this.box(this.room,h.x,1.6,h.z,h.w,.12,h.d,0x73828b);(top.material as T.MeshStandardMaterial).transparent=true;(top.material as T.MeshStandardMaterial).opacity=.4;for(const dx of [-h.w/2+.12,h.w/2-.12])for(const dz of [-h.d/2+.12,h.d/2-.12])this.box(this.room,h.x+dx,.8,h.z+dz,.12,1.6,.12,0x59646a);this.box(this.room,h.x,.005,h.z,h.w,.015,h.d,0x314d5c)}
 this.box(this.room,-1,.6,-6,2,.2,1.2,0x96856e);this.box(this.room,-1,.75,-6,.45,.05,.3,0xc9e3c1);this.box(this.room,10.8,1.5,-8.8,2.4,3,.15,0x355c50);
 this.box(this.room,8,1.76,-6,.9,.32,.12,0x244b45);this.box(this.room,8,1.78,-5.92,.73,.21,.025,0x8be3af);this.box(this.room,8,1.64,-5.65,.8,.045,.4,0x3e5753);
 const exitLight=new T.PointLight(0x8be3af,12,6);exitLight.position.set(10,2,-7);this.room.add(exitLight);
 const textureCanvas=document.createElement('canvas');textureCanvas.width=128;textureCanvas.height=64;const c=textureCanvas.getContext('2d')!;c.fillStyle='#203440';c.fillRect(0,0,128,64);c.fillStyle='#eef1e7';c.font='bold 40px Arial';c.textAlign='center';c.fillText('ICE',64,47);const tag=new T.CanvasTexture(textureCanvas);
 for(let i=0;i<ROUTES.length;i++){const guard=new T.Group();for(const x of [-.2,.2])this.box(guard,x,.6,0,.25,1.2,.3,0x1f2e3d);this.box(guard,0,1.5,0,.85,.9,.42,0x2e4356);const head=new T.Mesh(new T.SphereGeometry(.26,12,8),new T.MeshStandardMaterial({color:0xa18b77}));head.position.y=2.2;guard.add(head);this.box(guard,0,2.4,.06,.65,.12,.55,0x233443);const label=new T.Mesh(new T.PlaneGeometry(.65,.33),new T.MeshBasicMaterial({map:tag}));label.position.set(0,1.65,.22);guard.add(label);this.box(guard,.55,1.3,.25,.15,.15,.4,0xcaccc0);this.guards.push(guard);this.room.add(guard);const signal=new T.Mesh(new T.OctahedronGeometry(.16),new T.MeshBasicMaterial({color:0xedc477}));this.room.add(signal);this.guardSignals.push(signal);
 const shape=new T.Shape();shape.moveTo(0,0);for(let j=0;j<=24;j++){const a=-VISION_HALF_ANGLE+j/24*VISION_HALF_ANGLE*2;shape.lineTo(Math.sin(a)*VISION_RANGE,Math.cos(a)*VISION_RANGE)}shape.closePath();const cone=new T.Mesh(new T.ShapeGeometry(shape),new T.MeshBasicMaterial({color:0xf3d990,transparent:true,opacity:.13,side:T.DoubleSide,depthWrite:false}));cone.rotation.x=Math.PI/2;this.room.add(cone);this.cones.push(cone)}
 this.heroes.forEach(h=>{h.root.scale.setScalar(.55);h.fur.forEach(f=>f.geometry.setDrawRange(0,Math.floor(f.geometry.getAttribute('position').count/24)*4));this.scene.add(h.root);const shadow=new T.Mesh(new T.CircleGeometry(.46,24),new T.MeshBasicMaterial({color:0x10191b,transparent:true,opacity:.25,depthWrite:false}));shadow.rotation.x=-Math.PI/2;this.scene.add(shadow);this.floorShadows.push(shadow)});
 this.marker=new T.Mesh(new T.TorusGeometry(.6,.055,6,32),new T.MeshBasicMaterial({color:0xe8c782,transparent:true,opacity:.9}));this.marker.rotation.x=Math.PI/2;this.scene.add(this.marker);this.dust=new T.Mesh(new T.SphereGeometry(.7,12,8),new T.MeshBasicMaterial({color:0xc7bbd5,transparent:true,opacity:.35,depthWrite:false}));this.scene.add(this.dust);for(const root of [this.cage,this.room])root.traverse(o=>{if(o instanceof T.Mesh){o.userData.baseOpacity=(o.material as T.Material).opacity;o.userData.baseCastShadow=o.castShadow;this.occluders.push(o)}});for(const p of PLATFORMS){const hint=new T.Mesh(new T.RingGeometry(.27,.32,24),new T.MeshBasicMaterial({color:0x95d9be,transparent:true,opacity:.65,depthWrite:false}));hint.rotation.x=-Math.PI/2;hint.position.set(p.x,p.y+.025,p.z);this.cage.add(hint);this.shelfHints.push(hint)}
 this.leaderRing=new T.Mesh(new T.RingGeometry(.36,.4,24),new T.MeshBasicMaterial({color:0xf0d398,transparent:true,opacity:.8,depthWrite:false}));this.leaderRing.rotation.x=-Math.PI/2;this.scene.add(this.leaderRing);
 for(const x of [-.95,.95])this.box(this.disguise,x,.55,0,.06,1.1,1.35,0xa37e4c);for(const z of [-.65,.65])this.box(this.disguise,0,.55,z,1.9,1.1,.06,0xa37e4c);this.box(this.disguise,0,1.12,0,1.96,.06,1.4,0xbf9b65);this.box(this.disguise,0,1.157,0,.2,.01,1.4,0xdbc59a);this.scene.add(this.disguise);this.stunCloud=new T.Mesh(new T.IcosahedronGeometry(.7,1),new T.MeshBasicMaterial({color:0xd9cbe3,transparent:true,opacity:.4,depthWrite:false,wireframe:true}));this.scene.add(this.stunCloud);
 this.fluff=new T.Mesh(new T.IcosahedronGeometry(.55,1),new T.MeshBasicMaterial({color:0xd7c6af,transparent:true,opacity:.22,depthWrite:false,wireframe:true}));this.scene.add(this.fluff);this.resize('cage')}
 box(parent:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,color:number,angle=0){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,map:[0xb09670,0x9f7b51,0xbd9c6b,0x795337,0x8b603f,0x9b6f47].includes(color)?this.woodMap:null,roughness:.8}));m.castShadow=h>.08;m.receiveShadow=true;m.position.set(x,y,z);m.rotation.y=angle;parent.add(m);return m}
 rotate(delta:number){this.yaw+=delta}
 zoom(delta:number){this.distance=Math.max(this.phase==='cage'?14:20,Math.min(this.phase==='cage'?25:42,this.distance+delta))}
 resetCamera(){this.yaw=.63;this.distance=this.phase==='room'?29:17;this.elevation=.56}
 movement(x:number,z:number){return {x:x*Math.cos(this.yaw)+z*Math.sin(this.yaw),z:-x*Math.sin(this.yaw)+z*Math.cos(this.yaw)}}
 resize(phase=this.phase||'cage'){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}

 render(g:EscapeGame,t:number){if(this.phase!==g.phase){this.phase=g.phase;this.resize();this.room.visible=g.phase==='room';this.cage.scale.setScalar(g.phase==='cage'?1:.4);this.cage.position.set(g.phase==='cage'?0:-9,0,g.phase==='cage'?0:-7);this.resetCamera();this.focus.set(0,g.phase==='cage'?1.4:0,0)}
 const target=g.phase==='cage'?new T.Vector3(g.x*.18,1.2+g.y*.3,g.z*.18):new T.Vector3(g.x*.5,.5,g.z*.5);this.focus.lerp(target,.08);const distance=this.distance*Math.max(1,1/this.camera.aspect);this.camera.position.set(this.focus.x+Math.sin(this.yaw)*Math.cos(this.elevation)*distance,this.focus.y+Math.sin(this.elevation)*distance,this.focus.z+Math.cos(this.yaw)*Math.cos(this.elevation)*distance);this.camera.lookAt(this.focus);
 for(const w of this.walls){const front=w.side==='right'?Math.sin(this.yaw)>.15:w.side==='left'?Math.sin(this.yaw)<-.15:Math.cos(this.yaw)<-.15;const mat=w.mesh.material as T.MeshStandardMaterial;mat.transparent=front;mat.opacity=front?.12:1;mat.depthWrite=!front;w.mesh.castShadow=!front}

 const lead=g.leader==='Enzo'?0:1;
 this.heroes.forEach((h,i)=>{const active=i===lead,offset=i?.48:-.48;h.root.position.set(g.x+offset,g.y,g.z+(active?-.15:.15)+(g.hayHidden?.65:0));h.root.rotation.y=Math.atan2(-g.face.z,g.face.x);h.root.rotation.z=g.actionKind==='bath'?Math.sin((1.1-g.actionTime)*Math.PI*3)*.8:0;const squeeze=active&&g.actionKind==='squeeze';h.root.scale.set(.55,squeeze?.31:g.hayHidden?.3:g.sneaking?.4:.55,squeeze?.4:.55);h.body.position.y=g.state==='won'?Math.abs(Math.sin(t*4+i))*.12:g.moving?Math.abs(Math.sin(t*13))*.018:Math.sin(t*2+i)*.009+.01;h.body.rotation.z=g.actionKind==='roll'&&active?-.14:0;h.head.rotation.z=Math.sin(t*1.7+i)*.025;h.tail.rotation.z=Math.sin(t*3+i)*.08;h.ears.forEach((e,j)=>e.rotation.x=Math.sin(t*2+j)*.06+(Math.sin(t*4+i+j)>.98?.15:0));h.feet.forEach((f,j)=>f.position.y=.071+(g.moving&&g.grounded?Math.max(0,Math.sin(t*14+j*Math.PI))*.1:0));poseChinchillaPaws(h)});
 this.floorShadows.forEach((m,i)=>{const h=this.heroes[i].root,below=g.surfaceBelow(h.position.x,h.position.z);m.position.set(h.position.x,below+.022,h.position.z);m.scale.setScalar(1+Math.max(0,g.y-below)*.12);(m.material as T.MeshBasicMaterial).opacity=.3/(1+Math.max(0,g.y-below)*.3)});
 this.leaderRing.position.copy(this.heroes[lead].root.position);this.leaderRing.position.y=g.surfaceBelow(this.leaderRing.position.x,this.leaderRing.position.z)+.028;this.leaderRing.visible=!g.hayHidden;
 this.shelfHints.forEach((m,i)=>{m.visible=g.phase==='cage'&&g.active&&g.canReach(PLATFORMS[i])&&Math.abs(g.y-PLATFORMS[i].y)>.1});
 const roll=g.tunnelRolled?1-(g.actionKind==='roll'?g.actionTime/.9:0):0;this.tunnelParts.forEach(m=>m.position.z=2.7+roll*.25);this.tunnelParts[0].rotation.x=roll*.33;this.looseStick.visible=g.tunnelRolled&&!g.stick;this.looseStick.position.y=.72+(g.actionKind==='roll'?Math.sin(roll*Math.PI)*.35:0);
 this.fluff.visible=g.actionKind==='bath'||g.hayHidden;this.fluff.position.set(g.x,g.y+.25,g.z+(g.hayHidden?.65:0));this.fluff.rotation.y=t*2;this.fluff.scale.setScalar(g.hayHidden?1.3:1+(1.1-g.actionTime)*.7);
 this.guards.forEach((m,i)=>{const guard=g.guards[i];m.position.set(guard.x,0,guard.z);m.rotation.y=guard.angle;m.rotation.z=(guard.stunned??0)>0?Math.sin(t*14)*.07:0;const signal=this.guardSignals[i];signal.position.set(guard.x,2.95,guard.z);signal.visible=(guard.stunned??0)>0||(guard.investigate??0)>0;signal.rotation.y=t*3;(signal.material as T.MeshBasicMaterial).color.set((guard.stunned??0)>0?0xbba3e6:g.sees(guard)?0xff7766:0xf0d18e);const cone=this.cones[i];cone.visible=(guard.stunned??0)===0;cone.position.set(guard.x,.06,guard.z);cone.rotation.set(Math.PI/2,0,-guard.angle);const mat=cone.material as T.MeshBasicMaterial;mat.color.set(g.noticed?0xeb8d70:0xf3d990)});
 this.disguise.visible=g.boxed&&g.phase==='room';this.disguise.position.set(g.x,g.y,g.z);this.stunCloud.visible=g.stunFlash>0&&!!g.stunPoint;if(g.stunPoint){this.stunCloud.position.set(g.stunPoint.x,1.5,g.stunPoint.z);this.stunCloud.scale.setScalar(1+(.6-g.stunFlash)*2)}
 this.clipModel.visible=!g.clip;this.door.rotation.y=g.phase==='room'?-1.05:0;this.marker.position.set(g.target.x,g.target.y+.08,g.target.z);this.marker.scale.setScalar(.95+Math.sin(t*3)*.08);this.marker.visible=g.state!=='won';this.dust.visible=!!g.decoy;if(g.decoy){this.dust.position.set(g.decoy.x,.5,g.decoy.z);this.dust.scale.setScalar(1+(DECOY_DURATION-g.decoyTime)*.6)}this.scene.updateMatrixWorld(true);
 const obscuring=new Set<T.Mesh>();
 for(const h of this.heroes){for(const height of [.2,.7]){const aim=h.root.position.clone().add(new T.Vector3(0,height,0)),direction=aim.clone().sub(this.camera.position);this.ray.set(this.camera.position,direction.clone().normalize());this.ray.far=direction.length()-.35;for(const hit of this.ray.intersectObjects(this.occluders,false)){const mesh=hit.object as T.Mesh;if((g.phase==='room'||!this.room.children.includes(mesh))&&mesh.getWorldPosition(new T.Vector3()).y>g.y+.05)obscuring.add(mesh)}}}
 const obscuredShelves=new Set([...obscuring].map(mesh=>mesh.userData.fadeGroup).filter(Boolean));
 for(const mesh of this.occluders){const mat=mesh.material as T.Material;const wall=this.walls.find(w=>w.mesh===mesh);const front=wall&&(wall.side==='right'?Math.sin(this.yaw)>.15:wall.side==='left'?Math.sin(this.yaw)<-.15:Math.cos(this.yaw)<-.15);const fade=obscuring.has(mesh)||obscuredShelves.has(mesh.userData.fadeGroup)||!!front;mat.opacity=fade?.08:mesh.userData.baseOpacity;mat.transparent=mat.opacity<1;mat.depthWrite=!fade&&mat.opacity>=.5;mesh.castShadow=!fade&&mesh.userData.baseCastShadow}
 (this.door.children[0] as T.LineSegments).material instanceof T.LineBasicMaterial&&((this.door.children[0] as T.LineSegments<T.BufferGeometry,T.LineBasicMaterial>).material.opacity=Math.cos(this.yaw)>0?.07:.23);
 this.renderer.render(this.scene,this.camera)}
 dispose(){const geo=new Set<T.BufferGeometry>(),mat=new Set<T.Material>(),textures=new Set<T.Texture>();this.scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments){geo.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){mat.add(m);if('map'in m&&m.map instanceof T.Texture)textures.add(m.map)}}});textures.add(this.woodMap);textures.forEach(t=>t.dispose());geo.forEach(g=>g.dispose());mat.forEach(m=>m.dispose());this.renderer.dispose()}
}
