export type FighterId='dora'|'enzo'|'fox'|'owl'|'snake'|'agent'|'trump';
export const ROSTER: {id:FighterId;name:string;tag:string;special:string;color:string;speed:number;power:number}[]=[
{id:'dora',name:'DORA',tag:'The white whirlwind',special:'Dust Blossom',color:'#e6c7df',speed:4.6,power:1},
{id:'enzo',name:'ENZO',tag:'The grey bruiser',special:'Thunder Chew',color:'#78bbd0',speed:4,power:1.14},
{id:'fox',name:'ANDEAN FOX',tag:'The canyon hunter',special:'Ember Pounce',color:'#ec9d57',speed:4.7,power:.96},
{id:'owl',name:'NIGHT OWL',tag:'Silent wings, loud hits',special:'Feather Cyclone',color:'#c1aedf',speed:4.2,power:1.04},
{id:'snake',name:'VIPER',tag:'The coiled challenger',special:'Venom Wave',color:'#aed278',speed:3.8,power:1.13},
{id:'agent',name:'ICE AGENT',tag:'The checkpoint brawler',special:'Red Tape',color:'#78b1b5',speed:3.7,power:1.15},
{id:'trump',name:'DONALD TRUMP',tag:'The podium powerhouse',special:'Golden Tweet',color:'#f2c960',speed:3.5,power:1.2},
];
export const SPECIALS:Record<FighterId,{speed:number;damage:number;radius:number;description:string}>={
 dora:{speed:6,damage:17,radius:.55,description:'A broad, slow dust fireball.'},enzo:{speed:8,damage:20,radius:.34,description:'A fast, heavy electric chew bolt.'},fox:{speed:10,damage:14,radius:.3,description:'A quick ember fireball.'},owl:{speed:7,damage:7,radius:.23,description:'Three feathers fan out at different heights.'},snake:{speed:6.8,damage:17,radius:.3,description:'A low venom wave that can be jumped.'},agent:{speed:7.5,damage:12,radius:.4,description:'A red-tape blast that briefly slows its target.'},trump:{speed:4.8,damage:24,radius:.6,description:'A large, slow golden energy wave.'}};
export const RISERS:Record<FighterId,{name:string;damage:number;lift:number;description:string}>={
 dora:{name:'Dust Spiral',damage:15,lift:9.4,description:'A spinning rising paw that swats jumpers.'},enzo:{name:'Static Uppaw',damage:18,lift:8.8,description:'A crackling uppercut with heavy launch.'},fox:{name:'Canyon Leap',damage:16,lift:9.8,description:'A soaring claw pounce that climbs high.'},owl:{name:'Updraft',damage:14,lift:10.2,description:'A wing beat that lifts the owl above fireballs.'},snake:{name:'Coil Strike',damage:17,lift:8.4,description:'A short coil launch with a biting apex.'},agent:{name:'Baton Rise',damage:16,lift:8.6,description:'A rising baton swing that stops air rushes.'},trump:{name:'Podium Slam',damage:19,lift:8.2,description:'A slow but brutal rising haymaker.'}};
export const SUPERS:Record<FighterId,{name:string;damage:number;hits:number;speed:number;radius:number;description:string}>={
 dora:{name:'Andean Bloom',damage:11,hits:4,speed:7.5,radius:.5,description:'Four dust blossoms bloom across the arena.'},enzo:{name:'Thunder Chorus',damage:13,hits:4,speed:9,radius:.36,description:'A rolling barrage of thunder bolts.'},fox:{name:'Ember Hunt',damage:10,hits:5,speed:11,radius:.3,description:'Five ember darts in a blistering rush.'},owl:{name:'Moonlit Gale',damage:9,hits:6,speed:8,radius:.26,description:'A storm of feathers at every height.'},snake:{name:'Venom Flood',damage:12,hits:4,speed:7.4,radius:.34,description:'Overlapping low venom waves.'},agent:{name:'Full Audit',damage:11,hits:4,speed:8,radius:.42,description:'Stacked red tape that keeps the target slowed.'},trump:{name:'Gold Rush',damage:15,hits:3,speed:5.4,radius:.62,description:'Three huge golden waves that crowd the screen.'}};
export type StoryBeat={chapter:number;place:string;title:string;text:string};
export const STORY:Record<FighterId,{place:string;before:string;after:string}>={
 dora:{place:'THE BURROW, CHILE',before:'Dora has read the citizenship handbook twice and thinks the whole plan is nonsense. Convince her the hard way.',after:'Dora stuffs the handbook into your bag. "Fine. But I am coming with you."'},
 enzo:{place:'ANTOFAGASTA DOCKS',before:'Enzo runs the cargo crates north. Passage costs one honest bout.',after:'Enzo waves you aboard a crate marked ALPACA WOOL. Next stop: north.'},
 fox:{place:'ATACAMA CROSSING',before:'An Andean fox has claimed the only path out of the desert, and he charges a toll in fur.',after:'The fox lets you pass and points at the highway lights. Paperwork is still ahead.'},
 snake:{place:'DARIEN GAP',before:'A viper owns the jungle route where the road ends. She does not accept documents.',after:'The viper slides aside. The jungle opens onto a long road north.'},
 owl:{place:'RIO GRANDE, MIDNIGHT',before:'A night owl watches the river and decides who crosses quietly and who does not.',after:'The owl drops a feather in the water. Cross now, little one, while it is dark.'},
 agent:{place:'THE ICE CHECKPOINT',before:'An ICE agent wants papers a chinchilla has never been allowed to hold. This one will not be talked down.',after:'The detention file blows off the desk. Someone stamps your form by accident. You keep walking.'},
 trump:{place:'THE NATURALIZATION PODIUM',before:'The final hearing. The man behind the gold microphone says your kind does not belong here. The oath is on the table behind him.',after:'The podium cracks. You take the oath yourself, in a small squeaky voice, and nobody stops you.'}};
export const STORY_ORDER:FighterId[]=['dora','enzo','fox','snake','owl','agent','trump'];
export const STORY_INTRO='A chinchilla leaves the Andes with a folded application, a dream of citizenship, and absolutely no lawyer. Seven fights stand between the burrow and the oath.';
export const STORY_END='The certificate is stamped, the fur is filthy, and the trophy says CITIZEN. Somewhere south, an old burrow gets a very long letter.';
export type Input={move:number;down?:boolean;jump?:boolean;block?:boolean;jab?:boolean;kick?:boolean;special?:boolean;rising?:boolean;super?:boolean};
export type Attack='jab'|'kick'|'special'|'rising'|'super';
export type Body={id:FighterId;x:number;y:number;vy:number;hp:number;meter:number;facing:number;block:boolean;stun:number;cooldown:number;attack:Attack|null;attackTime:number;hit:boolean;flash:number;combo:number;comboTime:number;slow:number;rising:number};
export type Shot={x:number;y:number;dir:number;owner:0|1;life:number;kind:FighterId;speed:number;damage:number;radius:number;vy:number;delay:number};
const empty:Input={move:0};
const body=(id:FighterId,x:number,facing:number):Body=>({id,x,y:0,vy:0,hp:100,meter:50,facing,block:false,stun:0,cooldown:0,attack:null,attackTime:0,hit:false,flash:0,combo:0,comboTime:0,slow:0,rising:0});
export const SPECIAL_COST=35,RISING_COST=20,SUPER_COST=100;
export class FighterGame{
 motionStage=0;motionTime=0;riseStage=0;riseTime=0;notice='';noticeTime=0;mode:'arcade'|'story'|'training'='arcade';beat:StoryBeat|null=null;dummy:'stand'|'block'|'jump'|'fight'='stand';training={damage:0,best:0,hits:0,bestCombo:0};
 state:'select'|'story'|'fight'|'paused'|'round'|'match'|'champion'='select';selected:FighterId='dora';opponent=0;round=1;wins=[0,0];time=60;fighters:[Body,Body]=[body('dora',-3,1),body('fox',3,-1)];shots:Shot[]=[];message='CHOOSE YOUR FIGHTER';ai=true;aiClock=0;seed=17;intro=1.2;result:0|1|2=2;impact=0;
 get rivals(){return (this.mode==='story'?STORY_ORDER:ROSTER.map(r=>r.id)).filter(id=>id!==this.selected)}
 get active(){return this.state==='fight'}
 pick(id:FighterId){this.state='select';this.selected=id;this.opponent=0;this.round=1;this.wins=[0,0];this.time=60;this.shots=[];this.motionStage=0;this.motionTime=0;this.riseStage=0;this.riseTime=0;this.notice='';this.noticeTime=0;this.beat=null;this.fighters=[body(id,-3,1),body(this.rivals[0],3,-1)]}
 start(mode:'arcade'|'story'|'training'='arcade'){this.mode=mode;this.opponent=0;this.round=1;this.wins=[0,0];this.training={damage:0,best:0,hits:0,bestCombo:0};if(mode==='story'){this.showBeat('before')}else{this.beat=null;this.resetRound()}}
 startStory(){this.start('story')}
 startTraining(rival?:FighterId){this.mode='training';this.opponent=rival?this.rivals.indexOf(rival):0;this.start('training')}
 setDummy(d:'stand'|'block'|'jump'|'fight'){this.dummy=d}
 resetTraining(){this.training={damage:0,best:0,hits:0,bestCombo:0};this.resetRound()}
 showBeat(phase:'before'|'after'){const rival=this.rivals[Math.min(this.opponent,this.rivals.length-1)],chapter=STORY[rival],me=ROSTER.find(r=>r.id===this.selected)!;
  const last=this.opponent>=this.rivals.length-1;this.beat={chapter:this.opponent+1,place:chapter.place,title:phase==='before'?`CHAPTER ${this.opponent+1} OF ${this.rivals.length}`:last?'OATH TAKEN':'CHAPTER CLEARED',text:phase==='before'?(this.opponent===0?`${STORY_INTRO} ${chapter.before}`:chapter.before):last?`${chapter.after} ${STORY_END}`:`${chapter.after} ${me.name} presses on.`};this.state='story';this.shots=[]}
 advance(){if(this.state!=='story')return;if(this.beat?.title==='CHAPTER CLEARED'||this.beat?.title==='OATH TAKEN'){if(this.opponent>=this.rivals.length-1){this.state='champion';this.beat=null;return}this.opponent++;this.round=1;this.wins=[0,0];this.showBeat('before');return}this.resetRound()}
 resetRound(){this.fighters=[body(this.selected,-3,1),body(this.rivals[this.opponent],3,-1)];this.shots=[];this.motionStage=0;this.motionTime=0;this.riseStage=0;this.riseTime=0;this.notice='';this.noticeTime=0;this.time=60;this.intro=this.mode==='training'?.4:1.2;this.aiClock=.6;this.state='fight';this.message=this.mode==='training'?'TRAINING':`ROUND ${this.round}`;this.impact=0;if(this.mode==='training'){this.fighters[0].meter=100;this.fighters[1].meter=100}}
 next(){if(this.state==='round'){this.round++;this.resetRound()}else if(this.state==='match'){if(this.wins[0]===2){if(this.mode==='story'){this.showBeat('after');return}if(this.opponent===this.rivals.length-1){this.state='champion';return}this.opponent++;this.round=1;this.wins=[0,0];this.resetRound()}else{this.round=1;this.wins=[0,0];this.resetRound()}}}
 pause(){if(this.state==='fight')this.state='paused';else if(this.state==='paused')this.state='fight'}
 random(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296}
 cost(a:Attack){return a==='special'?SPECIAL_COST:a==='rising'?RISING_COST:a==='super'?SUPER_COST:0}
 attack(i:0|1,a:Attack){const f=this.fighters[i];if(!this.active||this.intro>0||f.stun>0||f.cooldown>0||f.block||f.meter<this.cost(a))return false;if((a==='rising'||a==='super')&&f.y>0)return false;f.attack=a;f.attackTime=0;f.hit=false;f.cooldown=a==='jab'?.33:a==='kick'?.55:a==='rising'?.7:a==='super'?1.4:.8;f.meter-=this.cost(a);
  if(a==='rising'){f.vy=RISERS[f.id].lift;f.rising=.45}
  if(i===0&&a!=='jab'&&a!=='kick'){const p=ROSTER.find(r=>r.id===f.id)!;this.notice=(a==='special'?p.special:a==='rising'?RISERS[f.id].name:SUPERS[f.id].name).toUpperCase();this.noticeTime=a==='super'?1.3:.85;this.motionStage=0;this.riseStage=0}
  return true}
 damage(owner:0|1,amount:number){const a=this.fighters[owner],b=this.fighters[owner===0?1:0],blocked=b.block&&b.y===0&&b.facing===-Math.sign(b.x-a.x);const dealt=blocked?Math.max(1,amount*.15):amount;b.hp=Math.max(0,b.hp-dealt);if(this.mode==='training'&&owner===0){this.training.hits++;this.training.damage=a.comboTime>0?this.training.damage+dealt:dealt;this.training.best=Math.max(this.training.best,this.training.damage);this.training.bestCombo=Math.max(this.training.bestCombo,a.comboTime>0?a.combo+1:1)}b.flash=.14;b.stun=blocked?.08:.2;if(!blocked){b.x=Math.max(-6.8,Math.min(6.8,b.x+a.facing*.2));a.combo=a.comboTime>0?a.combo+1:1;a.comboTime=.9;a.meter=Math.min(100,a.meter+8);this.impact=.1}else b.meter=Math.min(100,b.meter+4)}
 finish(){this.result=this.fighters[0].hp===this.fighters[1].hp?2:this.fighters[0].hp>this.fighters[1].hp?0:1;if(this.result!==2)this.wins[this.result]++;this.state=this.wins.some(w=>w>=2)?'match':'round';this.message=this.result===2?'DRAW — REMATCH':this.result===0?'YOU WIN':'RIVAL WINS';this.shots=[]}
 step(dt:number,input:Input=empty,rivalInput?:Input){if(!this.active)return;dt=Math.min(dt,1/60);this.impact=Math.max(0,this.impact-dt);if(this.intro>0){this.intro=Math.max(0,this.intro-dt);this.message=this.intro>.5?`ROUND ${this.round}`:'FIGHT!';return}if(this.mode!=='training')this.time=Math.max(0,this.time-dt);this.message='';this.noticeTime=Math.max(0,this.noticeTime-dt);this.motionTime=Math.max(0,this.motionTime-dt);if(this.motionTime===0)this.motionStage=0;const forward=input.move*this.fighters[0].facing>0; if(input.down&&!forward&&this.motionStage===0){this.motionStage=1;this.motionTime=.55}else if(input.down&&forward&&this.motionStage===1){this.motionStage=2;this.motionTime=.55}else if(!input.down&&forward&&this.motionStage===2){this.motionStage=3;this.motionTime=.35}this.riseTime=Math.max(0,this.riseTime-dt);if(this.riseTime===0)this.riseStage=0;if(forward&&!input.down&&this.riseStage===0){this.riseStage=1;this.riseTime=.4}else if(input.down&&!forward&&this.riseStage===1){this.riseStage=2;this.riseTime=.4}else if(input.down&&forward&&this.riseStage===2){this.riseStage=3;this.riseTime=.35}if(this.riseStage===3&&input.jab)input={...input,jab:false,rising:true};else if(this.motionStage===3&&input.jab)input={...input,jab:false,special:true};if(input.super&&this.fighters[0].meter<SUPER_COST){this.notice='NEED 100 POWER';this.noticeTime=.4}else if(input.special&&this.fighters[0].meter<SPECIAL_COST){this.notice='NEED 35 POWER';this.noticeTime=.4}else if(input.rising&&this.fighters[0].meter<RISING_COST){this.notice='NEED 20 POWER';this.noticeTime=.4}
 const [p,r]=this.fighters;let ai:Input=rivalInput??empty;if(this.ai&&!rivalInput){this.aiClock-=dt;const distance=Math.abs(p.x-r.x),dir=Math.sign(p.x-r.x);ai={move:distance>1.7?dir:distance<1?-dir:0,block:p.attack!==null&&distance<2.6&&this.random()<.62};if(this.aiClock<=0){const n=this.random();ai={...ai,jab:distance<2&&n<.55,kick:distance<2.4&&n>=.55,special:distance>2.4&&r.meter>=SPECIAL_COST&&n>.35,rising:distance<2.2&&r.meter>=RISING_COST&&(p.y>.6||n>.86),super:r.meter>=SUPER_COST&&distance>2&&n>.4,jump:p.attack==='special'||n<.12};this.aiClock=.25+this.random()*.4}}
 if(this.mode==='training'&&!rivalInput){ai=this.dummy==='stand'?{move:0}:this.dummy==='block'?{move:0,block:true}:this.dummy==='jump'?{move:0,jump:r.y===0}:ai}
 for(const [i,f]of this.fighters.entries()){const n=i as 0|1,other=this.fighters[i===0?1:0],control=i===0?input:ai,profile=ROSTER.find(r=>r.id===f.id)!;f.facing=other.x>=f.x?1:-1;f.slow=Math.max(0,f.slow-dt);f.stun=Math.max(0,f.stun-dt);f.cooldown=Math.max(0,f.cooldown-dt);f.flash=Math.max(0,f.flash-dt);f.comboTime=Math.max(0,f.comboTime-dt);if(f.comboTime===0)f.combo=0;f.meter=Math.min(100,f.meter+7*dt);f.block=!!control.block&&f.y===0&&!f.attack&&f.stun===0;
 f.rising=Math.max(0,f.rising-dt);
 if(f.stun===0){if(control.jump&&f.y===0&&!f.block&&!f.attack){f.vy=7.2}if(control.super)this.attack(n,'super');else if(control.rising)this.attack(n,'rising');else if(control.special)this.attack(n,'special');else if(control.jab)this.attack(n,'jab');else if(control.kick)this.attack(n,'kick');if(!f.block&&!f.attack){const nx=Math.max(-6.8,Math.min(6.8,f.x+Math.max(-1,Math.min(1,control.move))*profile.speed*(f.slow>0?.55:1)*dt));if(Math.abs(nx-other.x)>1.05||Math.abs(f.y-other.y)>.9||Math.abs(nx-other.x)>Math.abs(f.x-other.x))f.x=nx}}
 f.vy-=19*dt;f.y=Math.max(0,f.y+f.vy*dt);if(f.y===0)f.vy=0;
 if(f.attack){f.attackTime+=dt;if(!f.hit&&f.attackTime>=.12){f.hit=true;if(f.attack==='special'){const spec=SPECIALS[f.id];for(const spread of f.id==='owl'?[-.65,0,.65]:[0])this.shots.push({x:f.x+f.facing*.8,y:f.y+(f.id==='snake'?.28:.9),dir:f.facing,owner:n,life:3.2,kind:f.id,speed:spec.speed,damage:spec.damage,radius:spec.radius,vy:spread,delay:0})}else if(f.attack==='super'){const sup=SUPERS[f.id];for(let k=0;k<sup.hits;k++)this.shots.push({x:f.x+f.facing*.8,y:f.y+(f.id==='snake'?.28:.9)+(f.id==='owl'?(k%3-1)*.5:0),dir:f.facing,owner:n,life:3.6,kind:f.id,speed:sup.speed,damage:sup.damage*profile.power,radius:sup.radius,vy:0,delay:k*.14})}else if(f.attack==='rising'){if(Math.abs(f.x-other.x)<2.1&&other.y-f.y<2.4&&other.y-f.y>-2.2)this.damage(n,RISERS[f.id].damage*profile.power)}else if(Math.abs(f.x-other.x)<(f.attack==='jab'?1.85:2.35)&&Math.abs(f.y-other.y)<.95)this.damage(n,(f.attack==='jab'?7:11)*profile.power)}if(f.attackTime> (f.attack==='jab'?.25:f.attack==='rising'?.45:f.attack==='super'?.9:.4))f.attack=null}
 }
 for(const shot of this.shots){if(shot.delay>0){shot.delay=Math.max(0,shot.delay-dt);continue}shot.x+=shot.dir*shot.speed*dt;shot.y+=shot.vy*dt;shot.life-=dt;const target=this.fighters[shot.owner===0?1:0];if(shot.life>0&&Math.abs(shot.x-target.x)<.4+shot.radius&&shot.y+shot.radius>target.y+.1&&shot.y-shot.radius<target.y+1.65){const guarded=target.block;this.damage(shot.owner,shot.damage);if(shot.kind==='agent'&&!guarded)target.slow=1.3;shot.life=0}}this.shots=this.shots.filter(s=>s.life>0&&Math.abs(s.x)<8);if(this.mode==='training'){p.meter=100;if(r.hp<40){r.hp=100;r.stun=0;r.attack=null}if(p.hp<40)p.hp=100;if(p.comboTime===0&&this.training.damage>0)this.training.damage=0;return}if(p.hp<=0||r.hp<=0||this.time<=0)this.finish();
 }
}
