export type Footballer={id:number;name:string;team:0|1;x:number;y:number;keeper:boolean;stamina:number};
export type SoccerInput={x:number;y:number;sprint:boolean};
export const MATCH_SECONDS=90;
export class SoccerGame{
 state:'ready'|'playing'|'paused'|'goal'|'finished'='ready';time=0;score=[0,0];active=0;owner:number|null=0;ball={x:27,y:30,vx:0,vy:0};aim={x:100,y:30};players:Footballer[]=[];lock=0;aiTime=0;goalTime=0;kickoff:0|1=0;message='';messageTime=0;events:string[]=[];
 constructor(){this.reset(0)}
 reset(team:0|1){this.players=['Dora','Pip','Pebble','Cloud','Enzo','Ash','Coco','Slate'].map((name,id)=>{const side=(id<4?0:1) as 0|1,index=id%4;return {id,name,team:side,keeper:index===3,x:side?([73,67,67,95][index]):[27,33,33,5][index],y:[30,16,44,30][index],stamina:1}});this.owner=team===0?0:4;this.active=0;this.ball={x:team===0?28.5:71.5,y:30,vx:0,vy:0};this.lock=.8;this.aiTime=0;this.aim={x:100,y:30}}
 start(){if(this.state==='ready')this.state='playing'}
 pause(){if(this.state==='playing')this.state='paused';else if(this.state==='paused')this.state='playing'}
 say(s:string){this.message=s;this.messageTime=1.8}
 switchPlayer(){if(this.state!=='playing')return;const candidates=this.players.filter(p=>p.team===0&&!p.keeper&&p.id!==this.active).sort((a,b)=>Math.hypot(a.x-this.ball.x,a.y-this.ball.y)-Math.hypot(b.x-this.ball.x,b.y-this.ball.y));this.active=candidates[0].id;this.say(this.players[this.active].name+' selected')}
 kick(target:{x:number;y:number},speed:number){if(this.owner===null)return false;const p=this.players[this.owner],dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy)||1;this.ball.x=p.x+dx/d*1.8;this.ball.y=p.y+dy/d*1.8;this.ball.vx=dx/d*speed;this.ball.vy=dy/d*speed;this.owner=null;this.lock=.18;this.aiTime=0;return true}
 shoot(){if(this.state!=='playing'||this.owner!==this.active)return false;this.events.push('shot');this.say('Shot!');return this.kick(this.aim,52)}
 pass(){if(this.state!=='playing'||this.owner!==this.active)return false;const p=this.players[this.active],mate=this.players.filter(q=>q.team===0&&!q.keeper&&q.id!==p.id).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];this.say('Pass to '+mate.name);return this.kick(mate,30)}
 goal(team:0|1){this.score[team]++;this.state='goal';this.goalTime=2;this.kickoff=team===0?1:0;this.owner=null;this.ball.vx=0;this.ball.vy=0;this.events.push('goal');this.say(team===0?'GOAL! Dora’s team!':'GOAL! Enzo’s team!')}
 step(dt:number,input:SoccerInput={x:0,y:0,sprint:false}){dt=Math.min(dt,1/60);if(this.state==='goal'){this.goalTime-=dt;if(this.goalTime<=0){if(this.time>=MATCH_SECONDS)this.state='finished';else{this.reset(this.kickoff);this.state='playing'}}return}if(this.state!=='playing')return;this.time+=dt;this.lock=Math.max(0,this.lock-dt);this.aiTime+=dt;this.messageTime=Math.max(0,this.messageTime-dt);
 const human=this.players[this.active],n=Math.max(1,Math.hypot(input.x,input.y)),running=input.sprint&&human.stamina>.05&&(input.x!==0||input.y!==0);human.x+=input.x/n*(running?15:10)*dt;human.y+=input.y/n*(running?15:10)*dt;human.stamina=Math.max(0,Math.min(1,human.stamina+(running?-.24:.14)*dt));
 const move=(p:Footballer,x:number,y:number,speed:number)=>{const dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy);if(d>.15){const step=Math.min(d,speed*dt);p.x+=dx/d*step;p.y+=dy/d*step}};
 for(const team of [0,1]){const outfield=this.players.filter(p=>p.team===team&&!p.keeper&&p.id!==this.active);const chaser=outfield.slice().sort((a,b)=>Math.hypot(a.x-this.ball.x,a.y-this.ball.y)-Math.hypot(b.x-this.ball.x,b.y-this.ball.y))[0];for(const p of this.players.filter(p=>p.team===team&&p.id!==this.active)){p.stamina=Math.min(1,p.stamina+dt*.14);if(p.keeper){move(p,team===0?5:95,Math.max(24,Math.min(36,this.ball.y)),5);continue}if(this.owner===p.id){move(p,team===0?94:6,30+Math.sin(this.time*.8)*7,8.5);if(this.aiTime>1.1&&team===0){this.kick(human,29)}else if(team===1&&((p.x<35&&this.aiTime>.55)||this.aiTime>3)){this.kick({x:0,y:26+Math.sin(this.time*1.7)*4},48)}continue}const friendly=this.owner!==null&&this.players[this.owner].team===team;if(!friendly&&p===chaser)move(p,this.ball.x,this.ball.y,9.3);else{const targetX=friendly?this.ball.x+(team===0?11:-11):team===0?28:72;move(p,Math.max(12,Math.min(88,targetX)),p.id%4===1?17:p.id%4===2?43:30,6.5)}}}
 for(const p of this.players){p.x=Math.max(2,Math.min(98,p.x));p.y=Math.max(3,Math.min(57,p.y))}
 if(this.owner!==null){const p=this.players[this.owner];this.ball.x=p.x+(p.team===0?1.5:-1.5);this.ball.y=p.y;this.ball.vx=0;this.ball.vy=0;if(p.keeper&&this.aiTime>.7){const mate=this.players.find(q=>q.team===p.team&&!q.keeper)!;this.kick(mate,32)}if(this.lock===0){const tackler=this.players.find(q=>q.team!==p.team&&Math.hypot(q.x-p.x,q.y-p.y)<1.6);if(tackler){this.owner=tackler.id;this.lock=.75;this.aiTime=0;if(tackler.team===0&&!tackler.keeper)this.active=tackler.id;this.say(tackler.name+' wins the ball')}}}else{this.ball.x+=this.ball.vx*dt;this.ball.y+=this.ball.vy*dt;const damping=Math.exp(-.36*dt);this.ball.vx*=damping;this.ball.vy*=damping;
 if(this.ball.x<0||this.ball.x>100){if(this.ball.y>23&&this.ball.y<37){this.goal(this.ball.x>100?0:1);return}this.ball.x=Math.max(0,Math.min(100,this.ball.x));this.ball.vx*=-.7}if(this.ball.y<1||this.ball.y>59){this.ball.y=Math.max(1,Math.min(59,this.ball.y));this.ball.vy*=-.7}
 if(this.lock===0){const receiver=this.players.slice().sort((a,b)=>Math.hypot(a.x-this.ball.x,a.y-this.ball.y)-Math.hypot(b.x-this.ball.x,b.y-this.ball.y)).find(p=>Math.hypot(p.x-this.ball.x,p.y-this.ball.y)<(p.keeper?1.8:1.2));if(receiver){this.owner=receiver.id;this.lock=.55;this.aiTime=0;if(receiver.team===0&&!receiver.keeper)this.active=receiver.id}}}
 if(this.time>=MATCH_SECONDS){this.time=MATCH_SECONDS;this.state='finished';this.events.push('whistle')}
 }
}
