'use client';
import './classic.css';
import {useEffect,useRef,useState} from 'react';
import {PitGame,ORBS,RECIPES,type OrbKind} from '../../lib/classic-pit-game';
import {PASSIVES,type PassiveKind} from '../../lib/classic-pit-passives';
import type {PitScene} from '../../lib/classic-pit-scene';
import {Play,Pause,Sparkles,Heart,ArrowDown,Volume2,VolumeX,HelpCircle,Combine,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
const KITS:{name:string;balls:OrbKind[];description:string}[]=[{name:'Classic pair',balls:['seed','stone'],description:'Reliable ricochets & heavy hits'},{name:'Burrow breakers',balls:['drill','scatter'],description:'Piercing shots & splitting acorns'},{name:'Moon gardeners',balls:['leech','gale'],description:'Healing spores & crowd control'}];
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef<PitGame|null>(null),scene=useRef<PitScene|null>(null),keys=useRef(new Set<string>()),soundRef=useRef(false),audio=useRef<AudioContext|null>(null),before=useRef(false);const[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[tick,setTick]=useState(0),[kit,setKit]=useState(0),[modal,setModal]=useState<'help'|'fusion'|'arsenal'|null>(null),[sound,setSound]=useState(false);const g=game.current;
 function tone(event:string){if(!soundRef.current||event==='wave')return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();const o=c.createOscillator(),v=c.createGain();o.type='sine';o.frequency.value=event==='fire'?340:event==='pop'?720:event==='hurt'?110:520;v.gain.setValueAtTime(.025,c.currentTime);v.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.connect(v);v.connect(c.destination);o.start();o.stop(c.currentTime+.14)}catch{}}
 function start(){const n=new PitGame();n.orbs=KITS[kit].balls.map(kind=>({kind,rank:1}));n.playing=true;game.current=n;keys.current.clear();setModal(null);canvas.current?.focus();setTick(t=>t+1)}
 function pause(){const n=game.current;if(n?.playing){n.paused=!n.paused;keys.current.clear();n.fireHeld=false;setTick(t=>t+1)}}
 function open(which:'help'|'fusion'|'arsenal'|null){const n=game.current;if(n){if(which){before.current=n.paused;n.paused=true}else n.paused=before.current;n.fireHeld=false}keys.current.clear();setModal(which)}
 useEffect(()=>{let dead=false,raf=0,last=0,acc=0,ui=0;game.current=new PitGame(28);const resize=()=>scene.current?.resize();import('../../lib/classic-pit-scene').then(({PitScene})=>{if(dead||!canvas.current)return;try{scene.current=new PitScene(canvas.current);setReady(true);const loop=(now:number)=>{const n=game.current!;acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){n.step(1/120,{x:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),z:+(keys.current.has('s')||keys.current.has('arrowdown'))-+(keys.current.has('w')||keys.current.has('arrowup'))});acc-=1/120}for(const e of n.events.splice(0))tone(e);scene.current!.render(n,now/1000);if(now-ui>60){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setFailure('This pit needs WebGL 2. Enable hardware acceleration and reload.')}}).catch(()=>setFailure('The pit could not load. Please reload.'));return()=>{dead=true;cancelAnimationFrame(raf);window.removeEventListener('resize',resize);scene.current?.dispose();void audio.current?.close()}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('[role=dialog],input'))return;const k=e.key.toLowerCase(),n=game.current;if(!n?.playing)return;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k==='escape'||k==='p')pause();if(k==='q'||k===' ')n.burst();if(k==='f')open('fusion')};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const release=()=>{if(game.current)game.current.fireHeld=false};const blur=()=>{release();keys.current.clear();if(game.current?.playing)game.current.paused=true};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',release);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',release);window.removeEventListener('blur',blur)}},[]);
 void tick;
 return <main className="classic-pit-shell"><header className="classic-pit-header"><a className="classic-pit-brand" href="/">← MAIN ARCADE <span>Chin x Pit · Classic</span></a><div><button aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{soundRef.current=!soundRef.current;setSound(soundRef.current)}}>{sound?<Volume2/>:<VolumeX/>}</button><button aria-label="How to play" onClick={()=>open('help')}><HelpCircle/></button></div></header>
 <div className="classic-pit-layout"><aside className="classic-pit-sidebar"><span className="classic-pit-eyebrow">TWO FLUFFS. ONE PIT.</span><h1>Make every<br/><em>bounce count.</em></h1><p>Break the swarm. Fuse your balls.<br/>Keep the burrow safe.</p><div className="classic-pit-party"><div><span className="coat coat-0"/><b>Dora</b><small>Seedshot specialist</small></div><div><span className="coat coat-1"/><b>Enzo</b><small>Ricochet partner</small></div></div><div className="classic-pit-stat"><span><Heart size={15}/> COURAGE</span><b>{Math.ceil(g?.hp??100)} / {g?.maxHp??100}</b></div><Progress className="classic-pit-health" value={(g?.hp??100)/(g?.maxHp??100)*100}/><div className="classic-pit-stat"><span>LEVEL {g?.level??1}</span><b>{g?.xp??0} / {g?.xpNext??35} XP</b></div><Progress className="classic-pit-xp" value={(g?.xp??0)/(g?.xpNext??35)*100}/><div className="classic-pit-score"><span>{Math.round(g?.score??0).toLocaleString()}<small>SCORE</small></span><span>{g?.bestCombo??0}<small>BEST CHAIN</small></span></div><div className="classic-pit-control"><b>WASD</b><span>Move both friends</span><b>MOUSE</b><span>Aim your ricochets</span><b>Q / SPACE</b><span>Double Trouble</span><b>F</b><span>Open fusion lab</span></div><img className="classic-pit-photo" src="/art/the-original-duo.jpg" alt="The real Dora and Enzo chinchillas cuddling"/></aside>
 <section className="classic-pit-stage" aria-label="Chinchilla bouncing-ball arena"><canvas ref={canvas} tabIndex={0} aria-label="Aim with mouse, move with WASD, Q to burst" onPointerMove={e=>{const p=scene.current?.pick(e.clientX,e.clientY);if(p&&game.current)game.current.aim=p}} onPointerDown={e=>{const n=game.current;if(!n?.active)return;canvas.current?.focus();n.fireHeld=true;const p=scene.current?.pick(e.clientX,e.clientY);if(p)n.aim=p;e.currentTarget.setPointerCapture(e.pointerId)}} onContextMenu={e=>e.preventDefault()}/><div className="classic-pit-topline"><span>DEPTH {g?.depth??1}</span><b>WAVE {g?.wave??1} / 12</b><button aria-label="Pause" onClick={pause}><Pause size={16}/></button></div>

 {g?.playing&&g.combo>2&&<div className="classic-pit-chain">{g.combo}<span>HIT CHAIN</span></div>}{g?.messageTime&&g.playing&&!g.choice.length?<div className="classic-pit-message">{g.message}</div>:null}{g?.hurt? <div className="hurt-screen"/>:null}
 {!g?.playing&&!failure&&<div className="classic-pit-overlay classic-pit-intro"><span className="classic-pit-eyebrow">A BALL-BOUNCING CHINCHILLA ROGUELITE</span><h2>Little paws.<br/>Big ricochets.</h2><p>Two friends against a rising swarm.<br/>Aim, bounce, fuse, repeat.</p><button className="classic-pit-primary" disabled={!ready} onClick={start}>{ready?'Into the burrow':'Opening the burrow…'}<ArrowDown size={18}/></button><div className="classic-pit-kits" aria-label="Starting weapon pair">{KITS.map((k,i)=><button key={k.name} aria-pressed={kit===i} onClick={()=>{setKit(i);if(g&&!g.playing)g.orbs=KITS[i].balls.map(kind=>({kind,rank:1}))}}><b>{k.name}</b><small>{k.description}</small></button>)}</div><small>Auto-fire is on. Just aim and move.</small></div>}
 {g?.playing&&g.paused&&!modal&&!g.lost&&!g.won&&<div className="classic-pit-overlay"><h2>A little breather.</h2><button className="classic-pit-primary" onClick={pause}>Keep bouncing <Play size={18}/></button><button className="classic-pit-text" onClick={start}>Start a fresh run</button></div>}
 {!!g?.choice.length&&!modal&&!g.paused&&<div className="classic-pit-overlay classic-pit-upgrade"><span className="classic-pit-eyebrow">LEVEL {g.level} · PICK ONE</span><h2>A little more chaos.</h2>{g.choice.map(c=><button className="classic-pit-choice" key={c.id} onClick={()=>g.choose(c.id)}><i style={{background:c.color}}/><span>{c.category&&<em className="classic-pit-choice-tag">{c.category}</em>}<b>{c.name}</b><small>{c.description}</small></span><ChevronRight size={17}/></button>)}{!!g.fusionSuggestions().length&&<div className="classic-pit-level-fusions"><span className="classic-pit-eyebrow">FUSION OPPORTUNITIES</span>{g.fusionSuggestions().slice(0,2).map(r=><div key={r.result}><b style={{color:ORBS[r.result].color}}>{ORBS[r.result].name}</b><small>{ORBS[r.a].name} II + {ORBS[r.b].name} II</small>{r.ready?<button onClick={()=>{g.fuse(r.index);setTick(t=>t+1)}}>Fuse now · keep your level-up pick</button>:<p>{r.detail}{!r.next?' · Free a slot by fusing first.':''}</p>}</div>)}</div>}</div>}
 {(g?.lost||g?.won)&&<div className="classic-pit-overlay"><Sparkles color="#e2c789"/><span className="classic-pit-eyebrow">{g.won?'PIT CLEARED':'THE SWARM GOT THROUGH'}</span><h2>{g.won?'One more descent?':'Back on your paws.'}</h2><p>{g.kills} enemies broken · {Math.round(g.score).toLocaleString()} points<br/>Best chain: {g.bestCombo}</p><button className="classic-pit-primary" onClick={()=>g.won?g.descend():start()}>{g.won?'Descend with this build':'Try a new run'}<ArrowDown size={18}/></button></div>}
 {failure&&<div className="classic-pit-overlay"><h2>The pit needs a moment.</h2><p>{failure}</p><button className="classic-pit-primary" onClick={()=>location.reload()}>Reload</button></div>}
 </section>
 <aside className="classic-pit-inventory"><span className="classic-pit-eyebrow">YOUR BALL COLLECTION</span><h2>Small but mighty.</h2><button className="classic-pit-arsenal-link" onClick={()=>open('arsenal')}>Browse all {Object.keys(ORBS).length} weapons →</button><p>Both friends cycle through your equipped balls.</p><div className="classic-pit-orbs">{g?.orbs.map(o=><div key={o.kind} className="classic-pit-orb-card"><i style={{background:ORBS[o.kind].color,boxShadow:`0 0 20px ${ORBS[o.kind].color}33`}}/><span><b>{ORBS[o.kind].name}</b><small>LEVEL {o.rank} / 5</small><p>{ORBS[o.kind].description}</p></span></div>)}</div><button className="classic-pit-fusion" disabled={!g?.playing||g.lost||g.won||!!g.choice.length} onClick={()=>open('fusion')}><Combine size={18}/> Fusion lab <kbd>F</kbd></button><p className="classic-pit-note">Two compatible balls at level 2 become one evolved ball.</p><section className="classic-pit-passive-pouch"><span className="classic-pit-eyebrow">PASSIVE ITEMS</span>{g&&Object.keys(g.passives).length?Object.entries(g.passives).map(([id,rank])=><div key={id} title={PASSIVES[id as PassiveKind].description}><b style={{color:PASSIVES[id as PassiveKind].color}}>{PASSIVES[id as PassiveKind].name}</b><small>RANK {rank} / 3</small><p>{PASSIVES[id as PassiveKind].description}</p></div>):<p>Choose passive items when you level up. They do not use weapon slots.</p>}</section><div className="classic-pit-bond"><Sparkles/><h3>Double Trouble</h3><p>Damage the whole swarm and send every ball back up the pit.</p><Progress value={g?.charge??0}/><button disabled={!g?.active||(g?.charge??0)<50} onClick={()=>g?.burst()}>Q · {Math.floor(g?.charge??0)} / 50 BOND</button></div><div className="classic-pit-auto"><label htmlFor="autofire">Auto-fire</label><Switch id="autofire" checked={g?.auto??true} onCheckedChange={v=>{if(g)g.auto=v}}/></div><small className="classic-pit-note">When off, hold left click to fire.</small></aside></div>
 <footer className="classic-pit-footer">Aim for the side walls. Returning balls bounce off your chinchillas for extra damage.<span>Made for Dora & Enzo.</span></footer>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)open(null)}}><DialogContent className="classic-pit-dialog"><DialogHeader><DialogTitle>{modal==='fusion'?'The fusion burrow':modal==='arsenal'?'The burrow arsenal':'A crash course in chaos'}</DialogTitle><DialogDescription>{modal==='arsenal'?'Twelve base weapons. Eight evolved forms. Find new weapons in level-up choices; compatible level 2 pairs fuse into evolved weapons. Combat is paused.':modal==='fusion'?'Raise both ingredients to level 2. Fusion consumes them, creates a level 1 evolved ball, and frees a slot. Combat is paused.':'Move anywhere across the battlefield with WASD or arrows and aim in any direction with your mouse. Both chinchillas fire together. Balls bounce off enemies and walls; catching returning balls with either chinchilla sends them back stronger.'}</DialogDescription></DialogHeader>{modal==='arsenal'?<div className="classic-pit-catalog">{(Object.entries(ORBS) as [OrbKind,typeof ORBS[OrbKind]][]).map(([kind,orb])=>{const recipe=RECIPES.find(r=>r.result===kind),owned=g?.orbs.find(o=>o.kind===kind);return <article key={kind}><h3 style={{color:orb.color}}>{orb.name}<small>{owned?'Equipped · Lv '+owned.rank:recipe?'Fusion':'Base weapon'}</small></h3><p>{orb.description}</p>{recipe&&<span>{ORBS[recipe.a].name} II + {ORBS[recipe.b].name} II</span>}</article>})}</div>:modal==='fusion'?RECIPES.map((r,i)=><div className="classic-pit-recipe" key={r.result}><span>{ORBS[r.a].name} II + {ORBS[r.b].name} II</span><h3 style={{color:ORBS[r.result].color}}>{ORBS[r.result].name}</h3><p>{ORBS[r.result].description}</p><button disabled={!!g?.fusionReason(i)} onClick={()=>{g?.fuse(i);setTick(t=>t+1)}}>{g?.fusionReason(i)||'Fuse these balls'}</button></div>):<div className="classic-pit-help"><p>Enemies advance toward the red line. Each breach costs courage. Defeat 12 waves and the Dustbreaker to descend with your current build. A boss breach ends the run.</p><p>Enemy defeats earn XP. Each level offers three upgrades, including a step toward a compatible fusion when possible. Ready fusions can be made directly here without spending your upgrade pick. Equip up to four ball types; upgrade compatible ingredients to level 2, then press <b>F</b> to fuse them.</p><p><b>Q / Space</b> spends 50 bond on Double Trouble. <b>Esc / P</b> pauses. Progress lasts for the current run. Passive items appear at level-up, take no weapon slots, and stack to rank 3 for the current run.</p></div>}</DialogContent></Dialog>
 </main>
}
