'use client';
import {useEffect,useRef,useState} from 'react';
import {Adventure,BLOCKS} from '../../lib/arpg-game';
import {SKILLS,STANCES} from '../../lib/skills';
import type {IsometricWorld} from '../../lib/arpg-scene';
import {Pause,Play,RotateCcw,Volume2,VolumeX,HelpCircle,ChevronRight,Heart,Maximize,Minimize,Sparkles,Swords,Wind,MousePointer2,Leaf} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
const blank={stance:'smash',transform:0,transformCooldown:0,decoyLife:0,decoyCooldown:0,level:1,xp:0,xpNext:70,skillPoints:1,skills:{} as Record<string,number>,floorName:'The Warrens',seed:0,blocks:BLOCKS,burstCost:50,active:0,room:0,hp:150,maxHp:150,bond:45,stamina:100,special:0,dodge:0,treats:0,living:6,total:6,cleared:false,reward:false,won:false,message:'',hurt:0,time:0,heroes:[{x:-1,z:8},{x:1,z:8}],enemies:[] as {id:number;x:number;z:number;hp:number;maxHp:number;type:string;sx:number;sy:number;visible:boolean}[],floats:[] as {id:number;value:number;x:number;y:number}[],boons:[] as string[]};
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),world=useRef<IsometricWorld|null>(null),game=useRef<Adventure|null>(null),keys=useRef(new Set<string>()),held=useRef(false),lastCommand=useRef(0),aim=useRef<{x:number;z:number}|undefined>(undefined),soundRef=useRef(false),audio=useRef<AudioContext|null>(null);const[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[skillsOpen,setSkillsOpen]=useState(false),[help,setHelp]=useState(false),[sound,setSound]=useState(false),[detail,setDetail]=useState(true),[close,setClose]=useState(false),[hud,setHud]=useState(blank);
 function tone(e:string){if(!soundRef.current)return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();const o=c.createOscillator(),gain=c.createGain();o.type=e==='slash'?'triangle':'sine';const f=e==='seed'?480:e==='hurt'?130:e==='burst'?260:e==='pickup'?870:e==='clear'||e==='win'||e==='level'?680:390;o.frequency.setValueAtTime(f,c.currentTime);o.frequency.exponentialRampToValueAtTime(f*(e==='win'||e==='pickup'?1.5:.6),c.currentTime+.16);gain.gain.setValueAtTime(.045,c.currentTime);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(gain);gain.connect(c.destination);o.start();o.stop(c.currentTime+.23)}catch{}}
 const beforeTree=useRef(false);
 function tree(open:boolean){const g=game.current;if(!g)return;if(open){beforeTree.current=g.paused;g.paused=true;keys.current.clear();held.current=false}else{g.paused=beforeTree.current;canvas.current?.focus()}setSkillsOpen(open)}
 function start(){setSkillsOpen(false);game.current=new Adventure();game.current.playing=true;keys.current.clear();held.current=false;setStarted(true);setPaused(false);setHud(blank);canvas.current?.focus()}
 function pause(){if(game.current&&!game.current.won){game.current.paused=true;setPaused(true);keys.current.clear();held.current=false}}
 function resume(){if(game.current)game.current.paused=false;setPaused(false);canvas.current?.focus()}
 function title(){game.current=null;keys.current.clear();held.current=false;setStarted(false);setPaused(false);setHud(blank)}
 function action(a:string){const g=game.current;if(!g)return;if(a==='special')g.special(aim.current);if(a==='burst')g.burst();if(a==='dodge')g.dodge();if(a==='attack')g.keyboardAttack();if(a==='enter')g.enter()}
 useEffect(()=>{let stopped=false,id=0,last=0,acc=0,ui=0;const resize=()=>world.current?.resize();import('../../lib/arpg-scene').then(({IsometricWorld})=>{if(stopped||!canvas.current)return;try{world.current=new IsometricWorld(canvas.current);setReady(true);const loop=(now:number)=>{const dt=last?Math.min((now-last)/1000,.1):0;last=now;const g=game.current;if(g){acc+=dt;while(acc>=1/120){g.step(1/120,{forward:+(keys.current.has('w')||keys.current.has('arrowup'))-+(keys.current.has('s')||keys.current.has('arrowdown')),strafe:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft'))});acc-=1/120}for(const e of g.events.splice(0))tone(e)}else acc=0;world.current?.render(now/1000,g);if(g&&now-ui>70){setHud({stance:g.stance,transform:g.transform,transformCooldown:g.transformCooldown,decoyLife:g.decoy?.life??0,decoyCooldown:g.decoyCooldown,level:g.level,xp:g.xp,xpNext:g.xpNext,skillPoints:g.skillPoints,skills:{...g.skills},floorName:g.floor.name,seed:g.seed,blocks:g.floor.blocks,burstCost:g.burstCost,active:g.active,room:g.room,hp:Math.max(0,Math.ceil(g.hp)),maxHp:g.maxHp,bond:g.bond,stamina:g.stamina,special:g.hero.special,dodge:g.hero.dodge,treats:g.treats,living:g.living.length,total:g.enemies.length,cleared:g.cleared,reward:g.reward,won:g.won,message:g.messageFor?g.message:'',hurt:g.hurt,time:g.time,heroes:g.heroes.map(h=>({x:h.x,z:h.z})),enemies:g.enemies.map(e=>{const p=world.current!.project(e.x,e.type==='boss'?2.8:1.5,e.z);return {id:e.id,x:e.x,z:e.z,hp:e.hp,maxHp:e.maxHp,type:e.type,sx:p.x,sy:p.y,visible:p.visible}}),floats:g.effects.filter(e=>e.value).map(e=>{const p=world.current!.project(e.x,1.9+e.age,e.z);return {id:e.id,value:e.value!,x:p.x,y:p.y}}),boons:[...g.boosts]});ui=now}id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setFailure('The 3D den needs WebGL 2 and hardware acceleration. Try a recent desktop browser.')}}).catch(()=>setFailure('The adventure could not load. Check your connection and reload.'));const lost=(e:Event)=>{e.preventDefault();pause();setFailure('The 3D view was interrupted. Reload to start a fresh adventure.')};canvas.current?.addEventListener('webglcontextlost',lost);return()=>{stopped=true;cancelAnimationFrame(id);window.removeEventListener('resize',resize);canvas.current?.removeEventListener('webglcontextlost',lost);world.current?.dispose();world.current=null;void audio.current?.close();audio.current=null}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('[role="dialog"],input,select'))return;const g=game.current;if(!g)return;const k=e.key.toLowerCase();if([' ','tab','arrowleft','arrowright','arrowup','arrowdown'].includes(k))e.preventDefault();if(e.repeat)return;keys.current.add(k);if(k==='k'){tree(true);return}if(k==='escape'||k==='p'){pause();return}if(k==='tab')g.swap();if(k==='1')g.swap(0);if(k==='2')g.swap(1);if(k==='q')g.burst();if(k===' ')g.dodge();if(k==='r')g.keyboardAttack();if(k==='f')g.special(aim.current);if(k==='e')g.enter()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const release=()=>held.current=false;const blur=()=>{keys.current.clear();release();pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',release);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',release);window.removeEventListener('blur',blur)}},[]);
 const point=(n:number)=>(n+12)/24*100;
 return <main className="shell arpg-shell"><header><div className="brand">ChinChin<span>DUSTBOUND</span></div><div className="header-tools"><a href="/" style={{color:"#d2ae7d",fontSize:13}}>← MAIN ARCADE</a><span className="edition">{started?`FLOOR ${hud.room+1} · LEVEL ${hud.level}`:'TWO HEROES. ONE BOND.'}</span><button className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{soundRef.current=!soundRef.current;setSound(soundRef.current);tone('pickup')}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><Dialog open={help} onOpenChange={open=>{setHelp(open);if(open)pause()}}><DialogTrigger className="icon-button" aria-label="How to play and settings"><HelpCircle size={18}/></DialogTrigger><DialogContent className="help-dialog"><DialogHeader><DialogTitle>Two paws are better than one.</DialogTitle><DialogDescription>Explore an endless procedural dungeon with Dora and Enzo. Earn XP from enemies, level up, and spend skill points in two branching trees. A guardian appears every third floor.</DialogDescription></DialogHeader><div className="help-copy"><p><b>Left click</b> the floor to move, or an enemy to pursue and attack. Hold the mouse button to steer. <b>WASD / arrows</b> also move.</p><p><b>Tab</b> switches heroes. <b>1</b> chooses Dora; <b>2</b> chooses Enzo. Your companion follows and fights automatically.</p><p><b>Right click / F:</b> Dora fires a fan of seeds; Enzo spins to hit nearby enemies. <b>Space:</b> dodge. <b>Q:</b> a shared burst costing 50 bond before upgrades. Attacks build bond.</p><p><b>R</b> targets the nearest enemy. Treats collect when either hero approaches. Green drops also heal your shared courage. Clear a room, choose a boon, then approach the glowing arch and press <b>E</b>.</p><p><b>K</b> opens skill trees and pauses combat. Each level grants a skill point, more courage, and stronger attacks. Unlock a parent skill before its child. Dora’s learned seals and dust decoy trigger with her volley. Enzo’s Stonefur triggers with whirling paws; equip his learned stance in the tree. Decoy and transformation have their own recharge timers. <b>Esc / P</b> pauses. Running out of courage restarts the current chamber; earlier upgrades are kept.</p><div className="setting"><label htmlFor="detail">Detailed fur and shadows<small>Turn off for smoother performance.</small></label><Switch id="detail" checked={detail} onCheckedChange={v=>{setDetail(v);world.current?.quality(v)}}/></div></div></DialogContent></Dialog></div></header>
 <section className={`stage arpg-stage ${started?'adventuring':''}`} aria-label="Isometric chinchilla adventure"><canvas ref={canvas} tabIndex={0} aria-label="Click floor to move, click enemies to attack, Tab to switch chinchillas." onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{const g=game.current;if(!g||g.paused||g.won||g.reward)return;const p=world.current?.pick(e.clientX,e.clientY);if(!p)return;e.preventDefault();canvas.current?.focus();aim.current=p;if(e.button===0){held.current=true;g.command(p,p.enemy);e.currentTarget.setPointerCapture(e.pointerId)}if(e.button===2)g.special(p)}} onPointerMove={e=>{const p=world.current?.pick(e.clientX,e.clientY);if(p)aim.current=p;if(held.current&&p&&performance.now()-lastCommand.current>180){game.current?.command(p,p.enemy);lastCommand.current=performance.now()}}}/>
 {!started&&!failure&&<div className="title-overlay arpg-title"><span className="kicker">BENEATH THE FLOORBOARDS</span><h1>Small heroes.<br/>Ancient dust.</h1><p>Two fluffy adventurers. An ever-changing dungeon.<br/>Face the darkness—together.</p><button className="primary" disabled={!ready} onClick={start}>{ready?'Enter the den':'Opening the den…'}<ChevronRight size={19}/></button><span className="small-note">Click to move or attack · Tab to switch heroes</span><div className="hero-intro"><span><i className="coat coat-0"/>DORA <small>Ranged • Seed volley</small></span><span><i className="coat coat-1"/>ENZO <small>Melee • Whirling paws</small></span></div><div className="edition-tag">PROCEDURAL FLOORS <i/> LEVEL UP <i/> BUILD YOUR SKILL TREES</div></div>}
 {started&&!failure&&<><div className="chamber-plaque"><span className="kicker">FLOOR {hud.room+1}{(hud.room+1)%3===0?' · GUARDIAN':''}</span><h2>{hud.floorName}</h2><p>{hud.cleared?'The passage is open':`${hud.living} dust machines remain`}</p></div><div className="arpg-tools"><button className="icon-button" aria-label={close?'Show more of the room':'Look closer at both heroes'} onClick={()=>{const v=!close;setClose(v);if(world.current){world.current.close=v;world.current.resize()}}}>{close?<Minimize size={17}/>:<Maximize size={17}/>}</button><button className="icon-button" aria-label="Pause adventure" onClick={pause}><Pause size={17}/></button></div><div className="arpg-map"><svg viewBox="0 0 100 100" role="img" aria-label="Chamber map: gold and violet heroes, red enemies, glowing exit"><rect width="100" height="100" rx="4" fill="#151d28e8"/>{hud.blocks.map((b,i)=><rect key={i} x={point(b.x-b.w/2)} y={point(b.z-b.d/2)} width={b.w/24*100} height={b.d/24*100} fill="#73727890"/>)}<rect x="44" y="6" width="12" height="5" fill={hud.cleared?'#d7c7ff':'#665e76'}/>{hud.enemies.filter(e=>e.hp>0).map(e=><circle key={e.id} cx={point(e.x)} cy={point(e.z)} r={e.type==='boss'?3.2:1.7} fill="#d38c78"/>)}{hud.heroes.map((h,i)=><circle key={i} cx={point(h.x)} cy={point(h.z)} r={i===hud.active?2.8:2} fill={i===0?'#f1d79d':'#b5a0e3'} stroke="#fff" strokeWidth={i===hud.active?.6:0}/>)}</svg><span>FLOOR {hud.room+1}</span></div>
 {hud.enemies.filter(e=>e.hp>0&&e.visible&&(e.hp<e.maxHp||e.type==='boss')).map(e=><div className={`enemy-health ${e.type==='boss'?'boss-health':''}`} style={{left:`${e.sx}%`,top:`${e.sy}%`}} key={e.id}>{e.type==='boss'&&<span>THE GREAT SWEEPER</span>}<Progress value={e.hp/e.maxHp*100} aria-label={`${e.type} health`}/></div>)}
 {hud.floats.map(f=><span className="damage-float" key={f.id} style={{left:`${f.x}%`,top:`${f.y}%`}}>{f.value}</span>)}{hud.hurt>0&&<div className="hurt-screen"/>}
 <div className="hero-hud"><button className={hud.active===0?'hero-card chosen':'hero-card'} aria-pressed={hud.active===0} onClick={()=>game.current?.swap(0)}><i className="coat coat-0"/><span>Dora<small>RANGED</small></span><kbd>1</kbd></button><button className={hud.active===1?'hero-card chosen':'hero-card'} aria-pressed={hud.active===1} onClick={()=>game.current?.swap(1)}><i className="coat coat-1"/><span>Enzo<small>MELEE</small></span><kbd>2</kbd></button><span className="swap-note">Tab switches • Your buddy fights alongside you</span></div>
 <div className="mystic-status">{hud.skills.decoy>0&&<span>Dust Double <b>{hud.decoyLife>0?`${hud.decoyLife.toFixed(1)}s active`:hud.decoyCooldown>0?`${Math.ceil(hud.decoyCooldown)}s recharge`:'Ready · Dora F'}</b></span>}{hud.skills.stonefur>0&&<span>Stonefur <b>{hud.transform>0?`${hud.transform.toFixed(1)}s active`:hud.transformCooldown>0?`${Math.ceil(hud.transformCooldown)}s recharge`:'Ready · Enzo F'}</b></span>}{hud.skills[hud.stance]>0&&<span>Enzo’s stance <b>{STANCES.find(s=>s.id===hud.stance)?.name}</b></span>}</div>
 <div className="treasure"><Leaf size={16}/><b>{hud.treats}</b><span>treats</span></div>
 <div className="level-hud"><div><b>LEVEL {hud.level}</b><span>{hud.xp} / {hud.xpNext} XP</span></div><Progress value={hud.xp/hud.xpNext*100} aria-label="Experience toward next level"/><button className={hud.skillPoints?'points-ready':''} onClick={()=>tree(true)}>Skill trees <kbd>K</kbd>{hud.skillPoints>0&&<strong>+{hud.skillPoints}</strong>}</button></div>
 {hud.message&&!hud.reward&&!hud.won&&<div className="arpg-toast" role="status">{hud.message}</div>}{hud.cleared&&!hud.reward&&!hud.won&&<button className="portal-button" onClick={()=>action('enter')}>Enter passage <kbd>E</kbd></button>}</>}
 {paused&&!hud.won&&!failure&&<div className="scrim"><div className="pause-card"><span className="kicker">A MOMENT BETWEEN ADVENTURES</span><h2>Rest your little paws.</h2><button className="primary" onClick={resume}>Continue <Play size={18}/></button><button className="text-button" onClick={start}>Start a new adventure</button><button className="text-button" onClick={title}>Back to title</button></div></div>}
 {hud.reward&&!paused&&!failure&&<div className="scrim reward-screen"><div className="reward-card"><span className="kicker">FLOOR {hud.room+1} CLEARED</span><h2>Your bond grows stronger.</h2><p>Choose a boon for the rest of this adventure.</p><div className="boon-grid"><button onClick={()=>game.current?.choose('ranged')}><Leaf/><b>Sharper seeds</b><span>Dora deals 25% more damage.</span></button><button onClick={()=>game.current?.choose('melee')}><Swords/><b>Stronger paws</b><span>Enzo deals 25% more damage.</span></button><button onClick={()=>game.current?.choose('heart')}><Heart/><b>Braver hearts</b><span>Gain 35 maximum courage.</span></button></div><small>Every boon restores courage. Your level and skills carry to the next floor.</small></div></div>}
 {hud.won&&!failure&&<div className="scrim"><div className="win-card"><Sparkles className="heart" size={37}/><span className="kicker">THE GREAT SWEEPER IS SILENT</span><h2>Small heroes. Great legends.</h2><p>Three chambers reclaimed. {hud.treats} treats recovered.<br/>And not a friend left behind.</p><button className="primary" onClick={start}>Adventure again <ChevronRight size={18}/></button><button className="text-button" onClick={title}>Back to title</button></div></div>}
 {failure&&<div className="scrim"><div className="pause-card"><h2>The den needs a moment.</h2><p>{failure}</p><button className="primary" onClick={()=>window.location.reload()}>Reload <RotateCcw size={18}/></button></div></div>}
 </section>
 {started?<section className="battle-bar"><div className="party-life"><div><Heart size={16}/><span>COURAGE</span><b>{hud.hp}<small> / {hud.maxHp}</small></b></div><Progress value={hud.hp/hud.maxHp*100} aria-label="Shared party courage"/><Progress className="dodge-energy" value={hud.stamina} aria-label="Dodge stamina"/></div><div className="skill-bar"><button onClick={()=>action('attack')}><MousePointer2/><span>Attack<kbd>LMB / R</kbd></span></button><button disabled={hud.special>0} onClick={()=>action('special')}><Swords/><span>{hud.active===0?'Seed volley':'Whirling paws'}<kbd>{hud.special>0?`${hud.special.toFixed(1)}s`:'RMB / F'}</kbd></span></button><button disabled={hud.dodge>0||hud.stamina<30} onClick={()=>action('dodge')}><Wind/><span>Dodge<kbd>{hud.dodge>0?`${hud.dodge.toFixed(1)}s`:'SPACE'}</kbd></span></button><button className="bond-skill" disabled={hud.bond<hud.burstCost} onClick={()=>action('burst')}><Sparkles/><span>Together!<kbd>Q · {hud.burstCost} BOND</kbd></span></button></div><div className="bond-meter"><div><span>BOND</span><b>{Math.floor(hud.bond)}<small> / 100</small></b></div><Progress value={hud.bond} aria-label="Shared bond energy"/><small>Attacks build your bond</small></div></section>:<section className="room-list">{[{name:"Explore",subtitle:"New rooms and routes each adventure."},{name:"Grow",subtitle:"Earn XP. Choose branching skills."},{name:"Descend",subtitle:"A guardian every third floor."}].map((c,i)=><div key={c.name}><span>{['I','II','III'][i]}</span><p>{c.name}<small>{c.subtitle}</small></p></div>)}</section>}
 <Dialog open={skillsOpen} onOpenChange={tree}><DialogContent className="skill-tree-dialog"><DialogHeader><span className="kicker">THE BOOK OF TWO</span><DialogTitle>Shape your legend.</DialogTitle><DialogDescription>Level {hud.level} · {hud.skillPoints} skill {hud.skillPoints===1?'point':'points'} available. Learn a parent skill to unlock the next tier. Spells attach to your existing right-click / F ability. Equip one learned stance for Enzo below. Combat is paused.</DialogDescription></DialogHeader><div className="trees">{[0,1].map(hero=><section className={'hero-tree tree-'+hero} key={hero}><h2><i className={'coat coat-'+hero}/>{hero===0?'Dora · Whisker Sage':'Enzo · Stonefur Adept'}</h2><div className="tree-branches">{[...new Set(SKILLS.filter(n=>n.hero===hero).map(n=>n.branch))].map(branch=><div className="skill-branch" key={branch}><h3>{branch}</h3>{SKILLS.filter(n=>n.hero===hero&&n.branch===branch).map(n=>{const rank=hud.skills[n.id]||0,reason=game.current?.skillReason(n.id)||'';return <button key={n.id} className={'skill-node '+(rank?'learned ':'')+(!reason?'available':'')} disabled={!!reason} onClick={()=>{game.current?.learn(n.id);tone('pickup')}} aria-label={n.name+', rank '+rank+' of '+n.max+'. '+n.description+' '+(reason||'Spend one point')}><span className="node-heading"><b>{n.name}</b><em>{rank}/{n.max}</em></span><span>{n.description}</span><small>{reason||'＋ Spend 1 point'}</small></button>})}</div>)}</div>{hero===1&&<div className="stance-loadout"><h3>Equipped paw stance</h3><div>{STANCES.map(s=><button key={s.id} disabled={!hud.skills[s.id]} aria-pressed={hud.stance===s.id&&!!hud.skills[s.id]} title={s.description} onClick={()=>game.current?.equipStance(s.id)}>{s.name}<small>{!hud.skills[s.id]?'Learn to equip':hud.stance===s.id?'Equipped':'Equip'}</small></button>)}</div></div>}</section>)}</div><button className="primary" onClick={()=>tree(false)}>Return to the dungeon <ChevronRight size={18}/></button></DialogContent></Dialog>
 <footer><div className="original-pair"><img src="/art/the-original-duo.jpg" alt="The two real chinchillas cuddling in their wooden cubby"/><span>Two little partners. A legend in the making.</span></div><span className="footer-note">Click to move • WASD also works <i>·</i> No mouse capture</span></footer></main>
}
