'use client';
import {useEffect,useRef,useState} from 'react';
import {Game,rooms,type Mode,type Input} from '../../lib/legacy/after-hours/game';
import type {World} from '../../lib/legacy/after-hours/scene';
import {Pause,Play,RotateCcw,Volume2,VolumeX,ArrowUp,ArrowLeft,ArrowRight,Repeat2,Hand,RotateCw,Users,HelpCircle,ChevronRight,Heart,Maximize,Minimize} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
const still:Input={left:false,right:false,jump:false};
type Status={active:number;snack:number;held:boolean;won:boolean;message:string;together:boolean;bridge:boolean};
const initial:Status={active:0,snack:100,held:false,won:false,message:'',together:false,bridge:false};
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),world=useRef<World|null>(null),game=useRef<Game|null>(null),keys=useRef(new Set<string>()),touch=useRef({...still}),audio=useRef<AudioContext|null>(null),soundRef=useRef(false),closeRef=useRef(false);const[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[mode,setMode]=useState<Mode>('solo'),[room,setRoom]=useState(0),[hud,setHud]=useState(initial),[sound,setSound]=useState(false),[detailed,setDetailed]=useState(true),[close,setClose]=useState(false),[help,setHelp]=useState(false);
 function ping(event:string){if(!soundRef.current)return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();const o=c.createOscillator(),gain=c.createGain();o.type=event==='nibble'?'triangle':'sine';const frequency=event==='win'?650:event==='gate'?530:event==='jump'?270:event==='rescue'?170:440;o.frequency.setValueAtTime(frequency,c.currentTime);o.frequency.exponentialRampToValueAtTime(event==='win'?980:frequency*.65,c.currentTime+.17);gain.gain.setValueAtTime(.045,c.currentTime);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+.24);o.connect(gain);gain.connect(c.destination);o.start();o.stop(c.currentTime+.25)}catch{}}
 function start(m:Mode,r=0){const g=new Game(r,m);g.playing=true;game.current=g;keys.current.clear();touch.current={...still};setMode(m);setRoom(r);setStarted(true);setPaused(false);setHud(initial);canvas.current?.focus();}
 function pause(){const g=game.current;if(g&&!g.won){g.paused=!g.paused;setPaused(g.paused);keys.current.clear();touch.current={...still};}}
 function title(){game.current=null;setStarted(false);setPaused(false);setHud(initial);keys.current.clear();touch.current={...still};}
 function action(a:string){game.current?.action(a)}
 function zoom(){closeRef.current=!closeRef.current;setClose(closeRef.current);if(world.current)world.current.closeView=closeRef.current;}
 useEffect(()=>{let cancelled=false,id=0,last=0,acc=0,update=0;const resize=()=>world.current?.resize();const lost=(e:Event)=>{e.preventDefault();const g=game.current;if(g){g.paused=true;setPaused(true)}setFailure('The 3D view was interrupted. Reload to restart the game.');};canvas.current?.addEventListener('webglcontextlost',lost);import('../../lib/legacy/after-hours/scene').then(({World})=>{if(cancelled||!canvas.current)return;try{world.current=new World(canvas.current);setReady(true);const loop=(time:number)=>{if(cancelled)return;const dt=last?Math.min((time-last)/1000,.10):0;last=time;const g=game.current;if(g){acc+=dt;while(acc>=1/120){const input=[{...still},{...still}],k=keys.current;if(g.mode==='solo'){input[g.active]={left:k.has('a')||k.has('arrowleft')||touch.current.left,right:k.has('d')||k.has('arrowright')||touch.current.right,jump:k.has('w')||k.has('arrowup')||k.has(' ')||touch.current.jump}}else{input[0]={left:k.has('a'),right:k.has('d'),jump:k.has('w')};input[1]={left:k.has('arrowleft'),right:k.has('arrowright'),jump:k.has('arrowup')};for(const name of ['left','right','jump'] as const)input[g.active][name] ||=touch.current[name];}g.step(1/120,input);acc-=1/120}for(const e of g.events.splice(0))ping(e);if(time-update>90){setHud({active:g.active,snack:Math.round(g.snack.length/3*100),held:g.snack.owner>=0,won:g.won,message:g.objective(),together:g.together,bridge:g.bridge});update=time}}else acc=0;world.current?.render(time/1000,g);id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setFailure('This game needs a browser with WebGL 2 and hardware acceleration. Try a recent Chrome, Edge, Safari, or Firefox on desktop.');}}).catch(()=>setFailure('The 3D game could not load. Check your connection and reload.'));return()=>{cancelled=true;cancelAnimationFrame(id);window.removeEventListener('resize',resize);canvas.current?.removeEventListener('webglcontextlost',lost);world.current?.dispose();world.current=null;void audio.current?.close();audio.current=null}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.closest('[role="dialog"],input,select'))return;const k=e.key.toLowerCase(),g=game.current;if(!g)return;if(['arrowleft','arrowright','arrowup','arrowdown',' ','tab'].includes(k))e.preventDefault();if(e.repeat)return;keys.current.add(k);if(k==='p'||k==='escape'){pause();return}if(k==='v'){zoom();return}const map:Record<string,string>={tab:'switch',e:'grab',t:'tower',r:'rotate',n:'nibble',f:'team',b:'bridge'};if(map[k])g.action(map[k],k==='e'&&g.mode==='duo'?0:g.active);if(k==='enter'&&g.mode==='duo')g.action('grab',1);};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();touch.current={...still};const g=game.current;if(g&&!g.won){g.paused=true;setPaused(true)}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 const touchKey=(key:keyof Input,label:string,icon:React.ReactNode)=><button className="move-button" aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current[key]=true}} onPointerUp={()=>touch.current[key]=false} onPointerCancel={()=>touch.current[key]=false} onLostPointerCapture={()=>touch.current[key]=false}>{icon}</button>;
 return <main className="shell"><header><a className="brand" href="/" onClick={e=>{e.preventDefault();if(!started)title();else{const g=game.current;if(g){g.paused=true;setPaused(true)}}}}>ChinChin<span>AFTER HOURS</span></a><div className="header-tools"><span className="edition">{started?`ROOM ${String(room+1).padStart(2,'0')} / 03`:'A NEW ADVENTURE IN 3D'}</span><button className="icon-button" aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{soundRef.current=!soundRef.current;setSound(soundRef.current);ping('switch')}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><Dialog open={help} onOpenChange={open=>{setHelp(open);if(open&&game.current&&!game.current.won){game.current.paused=true;setPaused(true);keys.current.clear();touch.current={...still}}}}><DialogTrigger className="icon-button" aria-label="Controls and settings"><HelpCircle size={18}/></DialogTrigger><DialogContent className="help-dialog"><DialogHeader><DialogTitle>Small paws. Big teamwork.</DialogTitle><DialogDescription>Bring the snack and both chinchillas home. There are no lives or time limits.</DialogDescription></DialogHeader><div className="help-copy"><p><b>Solo:</b> A / D or ← / → moves. W, ↑ or Space jumps. Tab switches friends.</p><p><b>Two players:</b> Dora uses A / D / W and E to grab. Enzo uses ← / → / ↑ and Enter to grab.</p><p><b>E</b> grab / drop · <b>R</b> turn snack · <b>N</b> nibble · <b>T</b> boost Dora from Enzo · <b>F</b> team up near your buddy · <b>B</b> place or pack the snack bridge in room 3.</p><p>Dora jumps higher. Enzo pushes the crate and weighs down the lift pad. Team mode makes your friend follow in solo play. <b>V</b> changes the camera. <b>P</b> pauses.</p><div className="setting"><label htmlFor="fur-detail">Detailed fur and shadows<small>Turn off for a lighter 3D view.</small></label><Switch id="fur-detail" checked={detailed} onCheckedChange={checked=>{setDetailed(checked);world.current?.quality(checked)}}/></div></div></DialogContent></Dialog></div></header>
 <section className={`stage ${started?'in-game':''}`} aria-label="3D chinchilla playroom"><canvas ref={canvas} tabIndex={0} aria-label="3D side-view game. Use keyboard or the controls beneath the game to play."/>
 {!started&&!failure&&<div className="title-overlay"><span className="kicker">THE HOUSE IS QUIET. THE HEIST IS ON.</span><h1>Small paws.<br/>Bigger plans.</h1><p>Two fluffy accomplices.<br/>Three new rooms. One midnight snack.</p><div className="start-actions"><button className="primary" disabled={!ready} onClick={()=>start('solo')}>{ready?'Play solo':'Waking up the room…'}<ChevronRight size={20}/></button><button className="secondary" disabled={!ready} onClick={()=>start('duo')}><Users size={17}/> Two players</button></div><span className="small-note">Made for desktop · keyboard or on-screen controls</span><div className="edition-tag">3D CHARACTERS <i/> NEW PUZZLES <i/> SAME LITTLE PARTNERS</div></div>}
 {started&&!failure&&<><div className="room-plaque"><span className="kicker">CHAPTER {String(room+1).padStart(2,'0')}</span><h2>{rooms[room].title}</h2></div><div className="scene-tools"><button className={`icon-button ${close?'selected':''}`} aria-label={close?'Show full room':'Follow chinchilla closely'} onClick={zoom}>{close?<Minimize size={18}/>:<Maximize size={18}/>}</button><button className="icon-button" aria-label={paused?'Resume':'Pause'} onClick={pause}>{paused?<Play size={18}/>:<Pause size={18}/>}</button><button className="icon-button" aria-label="Restart room" onClick={()=>start(mode,room)}><RotateCcw size={18}/></button></div></>}
 {paused&&!hud.won&&!failure&&<div className="scrim"><div className="pause-card"><span className="kicker">A MOMENT TO CATCH YOUR WHISKERS</span><h2>A little fluff break.</h2><button className="primary" onClick={pause}>Keep going <Play size={18}/></button><button className="text-button" onClick={title}>Back to the title</button></div></div>}
 {hud.won&&!failure&&<div className="scrim"><div className="win-card"><Heart size={34} className="heart" fill="currentColor"/><span className="kicker">{room===2?'THREE ROOMS. TWO HAPPY CHINCHILLAS.':'HOME, SWEET HIDEOUT'}</span><h2>{room===2?'The perfect accomplices.':'A delicious little victory.'}</h2><p>Both friends safe. {hud.snack}% of the snack saved.<br/>{room===2?'A midnight adventure worth sharing.':rooms[room+1].short}</p><button className="primary" onClick={()=>start(mode,room===2?0:room+1)}>{room===2?'One more heist':'Next room'}<ChevronRight size={18}/></button><button className="text-button" onClick={title}>Back to the title</button></div></div>}
 {failure&&<div className="scrim"><div className="pause-card"><h2>The room needs a moment.</h2><p>{failure}</p><button className="primary" onClick={()=>window.location.reload()}>Reload game <RotateCcw size={18}/></button></div></div>}
 </section>
 {started?<><section className="status"><div className="characters" aria-label="Choose a chinchilla">{['Dora','Enzo'].map((name,i)=><button key={name} className={`character ${hud.active===i?'active':''}`} aria-pressed={hud.active===i} onClick={()=>{if(game.current)game.current.active=i}}><span className={`coat coat-${i}`}/><span>{name}<small>{i===0?'THE HIGH HOPPER':'THE LITTLE LIFTER'}</small></span>{hud.active===i&&<span className="selected-dot"/>}</button>)}</div><div className="objective"><span className="kicker">THE PLAN</span><p aria-live="polite">{hud.message||rooms[room].hint}</p></div><div className="snack-status"><span>{hud.snack}<small>%</small></span><p>snack saved</p></div></section><section className="controls" aria-label="Movement and action controls"><div className="movement">{touchKey('left','Move left',<ArrowLeft size={19}/>)}{touchKey('right','Move right',<ArrowRight size={19}/>)}{touchKey('jump','Jump',<ArrowUp size={19}/>)}<span>{mode==='solo'?<>A / D or arrows<br/>Space to jump</>:<>Dora: A D W<br/>Enzo: arrow keys</>}</span></div><div className="action-buttons"><button onClick={()=>action('switch')}><kbd>Tab</kbd><Repeat2 size={15}/>Switch</button><button onClick={()=>action('grab')}><kbd>E</kbd><Hand size={15}/>{hud.held?'Drop':'Grab'}</button><button onClick={()=>action('tower')}><kbd>T</kbd><ArrowUp size={15}/>Boost</button><button onClick={()=>action('rotate')}><kbd>R</kbd><RotateCw size={15}/>Turn</button><button onClick={()=>action('nibble')}><kbd>N</kbd>Nibble</button><button className={hud.together?'on':''} onClick={()=>action('team')}><kbd>F</kbd><Users size={15}/>Team</button>{room===2&&<button className={hud.bridge?'on':''} onClick={()=>action('bridge')}><kbd>B</kbd>{hud.bridge?'Pack bridge':'Bridge'}</button>}</div></section></>:<section className="room-list">{rooms.map((r,i)=><div key={r.title}><span>0{i+1}</span><p>{r.title}<small>{r.short}</small></p></div>)}</section>}
 <footer><div className="original-pair"><img src="/art/the-original-duo.jpg" alt="The real white and grey chinchillas cuddled together in their wooden cubby"/><span>Inspired by the original partners in crime.</span></div><span className="footer-note">Best played on desktop <i>·</i> No rush. No one left behind.</span></footer></main>
}
