'use client';
import {useEffect,useRef,useState} from 'react';
import {SoccerGame,MATCH_SECONDS} from '../../lib/soccer-game';
import {drawSoccer} from '../../lib/soccer-scene';
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef(new SoccerGame()),keys=useRef(new Set<string>()),[tick,setTick]=useState(0),[error,setError]=useState(false);const g=game.current;
 function start(){game.current=new SoccerGame();game.current.start();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function pause(){game.current.pause();keys.current.clear();canvas.current?.focus();setTick(t=>t+1)}
 function action(which:'pass'|'shoot'|'switch'){if(which==='pass')game.current.pass();else if(which==='shoot')game.current.shoot();else game.current.switchPlayer();canvas.current?.focus();setTick(t=>t+1)}
 useEffect(()=>{const c=canvas.current?.getContext('2d');if(!c){setError(true);return}let raf=0,last=0,acc=0,ui=0;const loop=(now:number)=>{acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){game.current.step(1/120,{x:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),y:+(keys.current.has('s')||keys.current.has('arrowdown'))-+(keys.current.has('w')||keys.current.has('arrowup')),sprint:keys.current.has('shift')});acc-=1/120}game.current.events.splice(0);drawSoccer(c,game.current,now/1000);if(now-ui>60){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input'))return;const k=e.key.toLowerCase();if([' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k==='j')action('pass');if(k==='k'||k===' ')action('shoot');if(k==='tab')action('switch');if(k==='p'||k==='escape')pause()};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>{keys.current.clear();if(game.current.state==='playing')game.current.pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[]);
 const hold=(key:string,label:string)=><button onPointerDown={e=>{e.preventDefault();keys.current.add(key);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)} onLostPointerCapture={()=>keys.current.delete(key)}>{label}</button>;
 void tick;return <main className="soccer-shell"><header className="soccer-header"><a href="/">← MAIN ARCADE <span>FLUFFBALL CUP</span></a><button disabled={!['playing','paused'].includes(g.state)} onClick={pause}>{g.state==='paused'?'Resume':'Pause'} · P</button></header><div className="soccer-title"><div><span className="soccer-eyebrow">FRIENDLY RIVALS · FOUR-A-SIDE</span><h1>Small paws. Big match.</h1></div><p>Dora’s Sky Squad vs Enzo’s Ember FC.<br/>Ninety seconds. Bragging rights forever.</p></div><section className="soccer-board" aria-label="Fluffball soccer match"><div className="soccer-score"><div className="soccer-team blue"><span>D</span><b>DORA<small>SKY SQUAD · YOU →</small></b></div><strong>{g.score[0]} <i>–</i> {g.score[1]}</strong><div className="soccer-team orange"><b>ENZO<small>← EMBER FC · CPU</small></b><span>E</span></div><time>{Math.floor(g.time/60)}:{String(Math.floor(g.time%60)).padStart(2,'0')} <small>/ 1:30</small></time></div>
 <div className="soccer-pitch"><canvas ref={canvas} width={1060} height={660} tabIndex={0} aria-label="Soccer field. WASD to move, mouse to aim, J pass, K shoot, Tab switch, Shift sprint." onPointerDown={()=>canvas.current?.focus()} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();g.aim={x:Math.max(0,Math.min(100,((e.clientX-r.left)/r.width*1060-30)/10)),y:Math.max(1,Math.min(59,((e.clientY-r.top)/r.height*660-30)/10))}}}/>
 {g.state==='goal'&&<div className="soccer-goal"><span>GOOOAL!</span><b>{g.message}</b></div>}
 {(g.state==='ready'||g.state==='paused'||g.state==='finished'||error)&&<div className="soccer-overlay"><div><span className="soccer-eyebrow">{error?'CANVAS UNAVAILABLE':g.state==='finished'?'FULL TIME':g.state==='paused'?'TIME OUT':'THE FLUFFBALL CUP'}</span><h2>{error?'Try another browser.':g.state==='finished'?(g.score[0]>g.score[1]?'Dora takes the cup!':g.score[0]<g.score[1]?'Enzo takes the cup!':'Honors even.'):g.state==='paused'?'A quick breather.':'Best friends.\nOpposite sides.'}</h2><p>{g.state==='finished'?`${g.score[0]} – ${g.score[1]} · ${g.score[0]===g.score[1]?'A friendly draw. Rematch?':'Time for a victory dust bath.'}`:g.state==='paused'?'The match clock is stopped.': 'Control Dora’s blue team. Build your attack, aim for the corners, and beat Enzo’s orange team.'}</p>{!error&&<button className="soccer-primary" onClick={g.state==='paused'?pause:start}>{g.state==='paused'?'Back to the match →':g.state==='finished'?'Play a rematch →':'Kick off →'}</button>}<small>WASD move · J pass · K shoot · Mouse aim</small></div></div>}
 </div><div className="soccer-status"><span>SELECTED <b>{g.players[g.active].name}</b></span><div className="soccer-stamina"><span>STAMINA</span><i><em style={{width:g.players[g.active].stamina*100+'%'}}/></i></div><span>{g.owner===null?'LOOSE BALL':g.players[g.owner].team===0?'SKY SQUAD POSSESSION':'EMBER FC POSSESSION'}</span><b>{g.messageTime>0&&g.state==='playing'?g.message:''}</b></div></section>
 <div className="soccer-actions"><div>{hold('a','←')}{hold('w','↑')}{hold('s','↓')}{hold('d','→')}{hold('shift','SPRINT')}</div><div><button onClick={()=>action('pass')}>J · PASS</button><button onClick={()=>action('shoot')}>K · SHOOT</button><button onClick={()=>action('switch')}>TAB · SWITCH</button></div></div><div className="soccer-help"><p><b>Build the play.</b> Move with WASD or arrows. Hold Shift to sprint. Tap J to pass; control follows a teammate receiving the ball.</p><p><b>Find the corner.</b> Point your mouse to aim, then press K or Space to shoot. Tab switches teammates. Run into the opposing ball carrier to tackle.</p><p><b>Keep it flowing.</b> Goalkeepers defend automatically. Sidelines rebound the ball for continuous arcade play. Attack the goal on the right.</p></div></main>
}
