'use client';
import {useEffect,useRef,useState} from 'react';
import {PitGame,ORBS,RECIPES,type OrbKind} from '../../lib/pit-game';
import {PASSIVES,type PassiveKind} from '../../lib/pit-passives';
import type {PitScene} from '../../lib/pit-scene';
import {Play,Pause,Sparkles,Heart,ArrowDown,Volume2,VolumeX,HelpCircle,Combine,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';

const KITS:{name:string;balls:OrbKind[];description:string}[]=[{name:'Classic pair',balls:['seed','stone'],description:'Hayseed volleys & pumice shots'},{name:'Burrow breakers',balls:['drill','scatter'],description:'Burrowing claws & acorn scatter'},{name:'Moon gardeners',balls:['leech','gale'],description:'Foraging spores & a dust aura'}];
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef<PitGame|null>(null),scene=useRef<PitScene|null>(null),keys=useRef(new Set<string>()),soundRef=useRef(false),audio=useRef<AudioContext|null>(null),before=useRef(false);const[ready,setReady]=useState(false),[failure,setFailure]=useState(''),[tick,setTick]=useState(0),[kit,setKit]=useState(0),[modal,setModal]=useState<'help'|'fusion'|'arsenal'|null>(null),[sound,setSound]=useState(false);const g=game.current;
 function tone(event:string){if(!soundRef.current||event==='wave')return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();const o=c.createOscillator(),v=c.createGain();o.type='sine';o.frequency.value=event==='fire'?340:event==='pop'?720:event==='hurt'?110:520;v.gain.setValueAtTime(.025,c.currentTime);v.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.connect(v);v.connect(c.destination);o.start();o.stop(c.currentTime+.14)}catch{}}
 function start(){const n=new PitGame();n.orbs=KITS[kit].balls.map(kind=>({kind,rank:1}));n.playing=true;game.current=n;keys.current.clear();setModal(null);canvas.current?.focus();setTick(t=>t+1)}
 function pause(){const n=game.current;if(n?.playing){n.paused=!n.paused;keys.current.clear();n.fireHeld=false;setTick(t=>t+1)}}
 function open(which:'help'|'fusion'|'arsenal'|null){const n=game.current;if(n){if(which){before.current=n.paused;n.paused=true}else n.paused=before.current;n.fireHeld=false}keys.current.clear();setModal(which)}
 useEffect(()=>{let dead=false,raf=0,last=0,acc=0,ui=0;game.current=new PitGame(28);const resize=()=>scene.current?.resize();import('../../lib/pit-scene').then(({PitScene})=>{if(dead||!canvas.current)return;try{scene.current=new PitScene(canvas.current);setReady(true);const loop=(now:number)=>{const n=game.current!;acc+=last?Math.min(.1,(now-last)/1000):0;last=now;while(acc>=1/120){n.step(1/120,{x:+(keys.current.has('d')||keys.current.has('arrowright'))-+(keys.current.has('a')||keys.current.has('arrowleft')),z:+(keys.current.has('s')||keys.current.has('arrowdown'))-+(keys.current.has('w')||keys.current.has('arrowup'))});acc-=1/120}for(const e of n.events.splice(0))tone(e);scene.current!.render(n,now/1000);if(now-ui>60){setTick(t=>t+1);ui=now}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);window.addEventListener('resize',resize)}catch{setFailure('This pit needs WebGL 2. Enable hardware acceleration and reload.')}}).catch(()=>setFailure('The pit could not load. Please reload.'));return()=>{dead=true;cancelAnimationFrame(raf);window.removeEventListener('resize',resize);scene.current?.dispose();void audio.current?.close()}},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('[role=dialog],input'))return;const k=e.key.toLowerCase(),n=game.current;if(!n?.playing)return;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.current.add(k);if(e.repeat)return;if(k==='escape'||k==='p')pause();if(k==='q'||k===' ')n.burst();if(k==='f')open('fusion')};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const release=()=>{if(game.current)game.current.fireHeld=false};const blur=()=>{release();keys.current.clear();if(game.current?.playing)game.current.paused=true};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',release);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',release);window.removeEventListener('blur',blur)}},[]);
 void tick;
 return <main className="pit-shell"><header className="pit-header"><a className="pit-brand" href="/">← MAIN ARCADE</a><div><button aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{soundRef.current=!soundRef.current;setSound(soundRef.current)}}>{sound?<Volume2/>:<VolumeX/>}</button><button aria-label="How to play" onClick={()=>open('help')}><HelpCircle/></button></div></header>
 <div className="pit-layout"><aside className="pit-sidebar"><span className="pit-eyebrow">TWO FLUFFS. ONE LONG NIGHT.</span><h1>Stay close.<br/><em>Survive the night.</em></h1><p>Gather XP. Grow your arsenal.<br/>Outlast the predators together.</p><div className="pit-party"><div><span className="coat coat-0"/><b>Dora</b><small>White chinchilla · Dora</small></div><div><span className="coat coat-1"/><b>Enzo</b><small>Grey chinchilla · Enzo</small></div></div><div className="pit-stat"><span><Heart size={15}/> COURAGE</span><b>{Math.ceil(g?.hp??100)} / {g?.maxHp??100}</b></div><Progress className="pit-health" value={(g?.hp??100)/(g?.maxHp??100)*100}/><div className="pit-stat"><span>LEVEL {g?.level??1}</span><b>{g?.xp??0} / {g?.xpNext??35} XP</b></div><Progress className="pit-xp" value={(g?.xp??0)/(g?.xpNext??35)*100}/><div className="pit-score"><span>{Math.round(g?.score??0).toLocaleString()}<small>SCORE</small></span><span>{g?.bestCombo??0}<small>BEST CHAIN</small></span></div><div className="pit-control"><b>WASD</b><span>Move both friends</span><b>AUTO</b><span>Weapons aim and attack</span><b>Q / SPACE</b><span>Double Trouble</span><b>F</b><span>Open fusion lab</span></div><img className="pit-photo" src="/art/the-original-duo.jpg" alt="The real Dora and Enzo chinchillas cuddling"/></aside>
 <section className="pit-stage" aria-label="Chinchilla survival arena"><canvas ref={canvas} tabIndex={0} aria-label="Move with WASD or arrows, weapons attack automatically, Q to burst" onPointerDown={()=>canvas.current?.focus()} onContextMenu={e=>e.preventDefault()}/><div className="pit-topline"><span>NIGHT {g?.depth??1}</span><b>{Math.floor((g?.time??0)/60)}:{String(Math.floor((g?.time??0)%60)).padStart(2,'0')} / 3:00 · {g?.bossSpawned?'GUARDIAN':'SURVIVE'}</b><button aria-label="Pause" onClick={pause}><Pause size={16}/></button></div>

 {g?.playing&&g.combo>2&&<div className="pit-chain">{g.combo}<span>HIT CHAIN</span></div>}{g?.messageTime&&g.playing&&!g.choice.length?<div className="pit-message">{g.message}</div>:null}{g?.hurt? <div className="hurt-screen"/>:null}
 {!g?.playing&&!failure&&<div className="pit-overlay pit-intro"><span className="pit-eyebrow">A CHINCHILLA SURVIVAL ROGUELITE</span><h2>Little paws.<br/>Endless predators.</h2><p>Survive three minutes, then defeat the cougar.<br/>Move, collect, evolve, survive.</p><button className="pit-primary" disabled={!ready} onClick={start}>{ready?'Survive the night':'Opening the burrow…'}<ArrowDown size={18}/></button><div className="pit-kits" aria-label="Starting weapon pair">{KITS.map((k,i)=><button key={k.name} aria-pressed={kit===i} onClick={()=>{setKit(i);if(g&&!g.playing)g.orbs=KITS[i].balls.map(kind=>({kind,rank:1}))}}><b>{k.name}</b><small>{k.description}</small></button>)}</div><small>Weapons attack automatically. You guide both friends.</small></div>}
 {g?.playing&&g.paused&&!modal&&!g.lost&&!g.won&&<div className="pit-overlay"><h2>A little breather.</h2><button className="pit-primary" onClick={pause}>Keep surviving <Play size={18}/></button><button className="pit-text" onClick={start}>Start a fresh run</button></div>}
 {!!g?.choice.length&&!modal&&!g.paused&&<div className="pit-overlay pit-upgrade"><span className="pit-eyebrow">LEVEL {g.level} · PICK ONE</span><h2>A little more chaos.</h2>{g.choice.map(c=><button className="pit-choice" key={c.id} onClick={()=>g.choose(c.id)}><i style={{background:c.color}}/><span>{c.category&&<em className="pit-choice-tag">{c.category}</em>}<b>{c.name}</b><small>{c.description}</small></span><ChevronRight size={17}/></button>)}{!!g.fusionSuggestions().length&&<div className="pit-level-fusions"><span className="pit-eyebrow">FUSION OPPORTUNITIES</span>{g.fusionSuggestions().slice(0,2).map(r=><div key={r.result}><b style={{color:ORBS[r.result].color}}>{ORBS[r.result].name}</b><small>{ORBS[r.a].name} II + {ORBS[r.b].name} II</small>{r.ready?<button onClick={()=>{g.fuse(r.index);setTick(t=>t+1)}}>Fuse now · keep your level-up pick</button>:<p>{r.detail}{!r.next?' · Free a slot by fusing first.':''}</p>}</div>)}</div>}</div>}
 {(g?.lost||g?.won)&&<div className="pit-overlay"><Sparkles color="#e2c789"/><span className="pit-eyebrow">{g.won?'DAWN ARRIVES':'THE PREDATORS CAUGHT UP'}</span><h2>{g.won?'Another night together?':'Back on your paws.'}</h2><p>{g.kills} predators defeated · {Math.round(g.score).toLocaleString()} points<br/>Best chain: {g.bestCombo}</p><button className="pit-primary" onClick={()=>g.won?g.descend():start()}>{g.won?'Brave a harder night':'Try a new run'}<ArrowDown size={18}/></button></div>}
 {failure&&<div className="pit-overlay"><h2>The pit needs a moment.</h2><p>{failure}</p><button className="pit-primary" onClick={()=>location.reload()}>Reload</button></div>}
 </section>
 <aside className="pit-inventory"><span className="pit-eyebrow">YOUR SURVIVAL ARSENAL</span><h2>Small but mighty.</h2><button className="pit-arsenal-link" onClick={()=>open('arsenal')}>Browse all {Object.keys(ORBS).length} weapons →</button><p>All equipped weapons attack automatically.</p><div className="pit-orbs">{g?.orbs.map(o=><div key={o.kind} className="pit-orb-card"><i style={{background:ORBS[o.kind].color,boxShadow:`0 0 20px ${ORBS[o.kind].color}33`}}/><span><b>{ORBS[o.kind].name}</b><small>LEVEL {o.rank} / 5</small><p>{ORBS[o.kind].description}</p></span></div>)}</div><button className="pit-fusion" disabled={!g?.playing||g.lost||g.won||!!g.choice.length} onClick={()=>open('fusion')}><Combine size={18}/> Fusion lab <kbd>F</kbd></button><p className="pit-note">Two compatible weapons at level 2 become one evolved weapon.</p><section className="pit-passive-pouch"><span className="pit-eyebrow">PASSIVE ITEMS</span>{g&&Object.keys(g.passives).length?Object.entries(g.passives).map(([id,rank])=><div key={id} title={PASSIVES[id as PassiveKind].description}><b style={{color:PASSIVES[id as PassiveKind].color}}>{PASSIVES[id as PassiveKind].name}</b><small>RANK {rank} / 3</small><p>{PASSIVES[id as PassiveKind].description}</p></div>):<p>Choose passive items when you level up. They do not use weapon slots.</p>}</section><div className="pit-bond"><Sparkles/><h3>Double Trouble</h3><p>Blast nearby predators with a protective cloud of dust.</p><Progress value={g?.charge??0}/><button disabled={!g?.active||(g?.charge??0)<50} onClick={()=>g?.burst()}>Q · {Math.floor(g?.charge??0)} / 50 BOND</button></div><p className="pit-note">Weapons auto-target the nearest predator. Move toward green XP gems to collect them.</p></aside></div>
 <footer className="pit-footer">Keep moving. Collect green XP gems. Stay together.<span>Made for Dora & Enzo.</span></footer>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)open(null)}}><DialogContent className="pit-dialog"><DialogHeader><DialogTitle>{modal==='fusion'?'The fusion burrow':modal==='arsenal'?'The burrow arsenal':'A crash course in chaos'}</DialogTitle><DialogDescription>{modal==='arsenal'?'Twelve base weapons. Eight evolved forms. Find new weapons in level-up choices; compatible level 2 pairs fuse into evolved weapons. Combat is paused.':modal==='fusion'?'Raise both ingredients to level 2. Fusion consumes them, creates a level 1 evolved weapon, and frees a slot. Combat is paused.':'Move Dora and Enzo together with WASD or arrows. All equipped weapons automatically attack nearby predators. Collect green XP gems to level up; keep moving to avoid contact damage.'}</DialogDescription></DialogHeader>{modal==='arsenal'?<div className="pit-catalog">{(Object.entries(ORBS) as [OrbKind,typeof ORBS[OrbKind]][]).map(([kind,orb])=>{const recipe=RECIPES.find(r=>r.result===kind),owned=g?.orbs.find(o=>o.kind===kind);return <article key={kind}><h3 style={{color:orb.color}}>{orb.name}<small>{owned?'Equipped · Lv '+owned.rank:recipe?'Fusion':'Base weapon'}</small></h3><p>{orb.description}</p>{recipe&&<span>{ORBS[recipe.a].name} II + {ORBS[recipe.b].name} II</span>}</article>})}</div>:modal==='fusion'?RECIPES.map((r,i)=><div className="pit-recipe" key={r.result}><span>{ORBS[r.a].name} II + {ORBS[r.b].name} II</span><h3 style={{color:ORBS[r.result].color}}>{ORBS[r.result].name}</h3><p>{ORBS[r.result].description}</p><button disabled={!!g?.fusionReason(i)} onClick={()=>{g?.fuse(i);setTick(t=>t+1)}}>{g?.fusionReason(i)||'Evolve these weapons'}</button></div>):<div className="pit-help"><p>Foxes, owls, and snakes pursue the pair from every direction. Contact costs courage. Survive three minutes, then defeat the Mountain Cougar to reach dawn. Continue into a harder night with your current build.</p><p>Defeated predators drop green XP gems. Move close to draw them in. Each level offers three upgrades, including a step toward a compatible fusion when possible. Ready fusions can be made directly here without spending your upgrade pick. Equip up to four weapons; upgrade compatible ingredients to level 2, then press <b>F</b> to fuse them.</p><p><b>Q / Space</b> spends 50 bond on Double Trouble. <b>Esc / P</b> pauses. Progress lasts for the current run. Passive items appear at level-up, take no weapon slots, and stack to rank 3 for the current run.</p></div>}</DialogContent></Dialog>
 </main>
}
